// Catálogo de comunas de Chile — fuente: SUBDERE División Político Administrativa (DPA),
// validado con BCN "Nuestro País" e INE: 16 regiones / 56 provincias / 346 comunas.
// zonaId referencia a ZONAS en ./zonas (20 zonas agroclimáticas del legacy).

export interface ComunaEntry {
  comuna: string;
  zonaId: number;
  region: string;
}

export const COMUNAS: ComunaEntry[] = [
  { comuna: "Arica", zonaId: 1, region: "Arica y Parinacota" },
  { comuna: "Camarones", zonaId: 1, region: "Arica y Parinacota" },
  { comuna: "General Lagos", zonaId: 1, region: "Arica y Parinacota" },
  { comuna: "Putre", zonaId: 1, region: "Arica y Parinacota" },
  { comuna: "Alto Hospicio", zonaId: 1, region: "Tarapacá" },
  { comuna: "Camiña", zonaId: 1, region: "Tarapacá" },
  { comuna: "Colchane", zonaId: 1, region: "Tarapacá" },
  { comuna: "Huara", zonaId: 1, region: "Tarapacá" },
  { comuna: "Iquique", zonaId: 1, region: "Tarapacá" },
  { comuna: "Pica", zonaId: 1, region: "Tarapacá" },
  { comuna: "Pozo Almonte", zonaId: 1, region: "Tarapacá" },
  { comuna: "Antofagasta", zonaId: 2, region: "Antofagasta" },
  { comuna: "Calama", zonaId: 2, region: "Antofagasta" },
  { comuna: "María Elena", zonaId: 2, region: "Antofagasta" },
  { comuna: "Mejillones", zonaId: 2, region: "Antofagasta" },
  { comuna: "Ollagüe", zonaId: 2, region: "Antofagasta" },
  { comuna: "San Pedro de Atacama", zonaId: 2, region: "Antofagasta" },
  { comuna: "Sierra Gorda", zonaId: 2, region: "Antofagasta" },
  { comuna: "Taltal", zonaId: 2, region: "Antofagasta" },
  { comuna: "Tocopilla", zonaId: 2, region: "Antofagasta" },
  { comuna: "Alto del Carmen", zonaId: 2, region: "Atacama" },
  { comuna: "Caldera", zonaId: 2, region: "Atacama" },
  { comuna: "Chañaral", zonaId: 2, region: "Atacama" },
  { comuna: "Copiapó", zonaId: 2, region: "Atacama" },
  { comuna: "Diego de Almagro", zonaId: 2, region: "Atacama" },
  { comuna: "Freirina", zonaId: 2, region: "Atacama" },
  { comuna: "Huasco", zonaId: 2, region: "Atacama" },
  { comuna: "Tierra Amarilla", zonaId: 2, region: "Atacama" },
  { comuna: "Vallenar", zonaId: 2, region: "Atacama" },
  { comuna: "Andacollo", zonaId: 4, region: "Coquimbo" },
  { comuna: "Canela", zonaId: 4, region: "Coquimbo" },
  { comuna: "Combarbalá", zonaId: 4, region: "Coquimbo" },
  { comuna: "Coquimbo", zonaId: 3, region: "Coquimbo" },
  { comuna: "Illapel", zonaId: 4, region: "Coquimbo" },
  { comuna: "La Higuera", zonaId: 3, region: "Coquimbo" },
  { comuna: "La Serena", zonaId: 3, region: "Coquimbo" },
  { comuna: "Los Vilos", zonaId: 3, region: "Coquimbo" },
  { comuna: "Monte Patria", zonaId: 4, region: "Coquimbo" },
  { comuna: "Ovalle", zonaId: 4, region: "Coquimbo" },
  { comuna: "Paihuano", zonaId: 4, region: "Coquimbo" },
  { comuna: "Punitaqui", zonaId: 4, region: "Coquimbo" },
  { comuna: "Río Hurtado", zonaId: 4, region: "Coquimbo" },
  { comuna: "Salamanca", zonaId: 4, region: "Coquimbo" },
  { comuna: "Vicuña", zonaId: 4, region: "Coquimbo" },
  { comuna: "Algarrobo", zonaId: 5, region: "Valparaíso" },
  { comuna: "Cabildo", zonaId: 5, region: "Valparaíso" },
  { comuna: "Calera", zonaId: 5, region: "Valparaíso" },
  { comuna: "Calle Larga", zonaId: 6, region: "Valparaíso" },
  { comuna: "Cartagena", zonaId: 5, region: "Valparaíso" },
  { comuna: "Casablanca", zonaId: 5, region: "Valparaíso" },
  { comuna: "Catemu", zonaId: 6, region: "Valparaíso" },
  { comuna: "Concón", zonaId: 5, region: "Valparaíso" },
  { comuna: "El Quisco", zonaId: 5, region: "Valparaíso" },
  { comuna: "El Tabo", zonaId: 5, region: "Valparaíso" },
  { comuna: "Hijuelas", zonaId: 5, region: "Valparaíso" },
  { comuna: "Isla de Pascua", zonaId: 5, region: "Valparaíso" },
  { comuna: "Juan Fernández", zonaId: 5, region: "Valparaíso" },
  { comuna: "La Cruz", zonaId: 5, region: "Valparaíso" },
  { comuna: "La Ligua", zonaId: 5, region: "Valparaíso" },
  { comuna: "Limache", zonaId: 5, region: "Valparaíso" },
  { comuna: "Llay-Llay", zonaId: 6, region: "Valparaíso" },
  { comuna: "Los Andes", zonaId: 6, region: "Valparaíso" },
  { comuna: "Nogales", zonaId: 5, region: "Valparaíso" },
  { comuna: "Olmué", zonaId: 5, region: "Valparaíso" },
  { comuna: "Panquehue", zonaId: 6, region: "Valparaíso" },
  { comuna: "Papudo", zonaId: 5, region: "Valparaíso" },
  { comuna: "Petorca", zonaId: 5, region: "Valparaíso" },
  { comuna: "Puchuncaví", zonaId: 5, region: "Valparaíso" },
  { comuna: "Putaendo", zonaId: 6, region: "Valparaíso" },
  { comuna: "Quillota", zonaId: 5, region: "Valparaíso" },
  { comuna: "Quilpué", zonaId: 5, region: "Valparaíso" },
  { comuna: "Quintero", zonaId: 5, region: "Valparaíso" },
  { comuna: "Rinconada", zonaId: 6, region: "Valparaíso" },
  { comuna: "San Antonio", zonaId: 5, region: "Valparaíso" },
  { comuna: "San Esteban", zonaId: 6, region: "Valparaíso" },
  { comuna: "San Felipe", zonaId: 6, region: "Valparaíso" },
  { comuna: "Santa María", zonaId: 6, region: "Valparaíso" },
  { comuna: "Santo Domingo", zonaId: 5, region: "Valparaíso" },
  { comuna: "Valparaíso", zonaId: 5, region: "Valparaíso" },
  { comuna: "Villa Alemana", zonaId: 5, region: "Valparaíso" },
  { comuna: "Viña del Mar", zonaId: 5, region: "Valparaíso" },
  { comuna: "Zapallar", zonaId: 5, region: "Valparaíso" },
  { comuna: "Alhué", zonaId: 9, region: "Metropolitana" },
  { comuna: "Buin", zonaId: 8, region: "Metropolitana" },
  { comuna: "Calera de Tango", zonaId: 8, region: "Metropolitana" },
  { comuna: "Cerrillos", zonaId: 8, region: "Metropolitana" },
  { comuna: "Cerro Navia", zonaId: 8, region: "Metropolitana" },
  { comuna: "Colina", zonaId: 7, region: "Metropolitana" },
  { comuna: "Conchalí", zonaId: 8, region: "Metropolitana" },
  { comuna: "Curacaví", zonaId: 9, region: "Metropolitana" },
  { comuna: "El Bosque", zonaId: 8, region: "Metropolitana" },
  { comuna: "El Monte", zonaId: 8, region: "Metropolitana" },
  { comuna: "Estación Central", zonaId: 8, region: "Metropolitana" },
  { comuna: "Huechuraba", zonaId: 8, region: "Metropolitana" },
  { comuna: "Independencia", zonaId: 8, region: "Metropolitana" },
  { comuna: "Isla de Maipo", zonaId: 8, region: "Metropolitana" },
  { comuna: "La Cisterna", zonaId: 8, region: "Metropolitana" },
  { comuna: "La Florida", zonaId: 8, region: "Metropolitana" },
  { comuna: "La Granja", zonaId: 8, region: "Metropolitana" },
  { comuna: "La Pintana", zonaId: 8, region: "Metropolitana" },
  { comuna: "La Reina", zonaId: 8, region: "Metropolitana" },
  { comuna: "Lampa", zonaId: 7, region: "Metropolitana" },
  { comuna: "Las Condes", zonaId: 8, region: "Metropolitana" },
  { comuna: "Lo Barnechea", zonaId: 8, region: "Metropolitana" },
  { comuna: "Lo Espejo", zonaId: 8, region: "Metropolitana" },
  { comuna: "Lo Prado", zonaId: 8, region: "Metropolitana" },
  { comuna: "Macul", zonaId: 8, region: "Metropolitana" },
  { comuna: "Maipú", zonaId: 8, region: "Metropolitana" },
  { comuna: "María Pinto", zonaId: 9, region: "Metropolitana" },
  { comuna: "Melipilla", zonaId: 9, region: "Metropolitana" },
  { comuna: "Padre Hurtado", zonaId: 8, region: "Metropolitana" },
  { comuna: "Paine", zonaId: 8, region: "Metropolitana" },
  { comuna: "Pedro Aguirre Cerda", zonaId: 8, region: "Metropolitana" },
  { comuna: "Peñaflor", zonaId: 8, region: "Metropolitana" },
  { comuna: "Peñalolén", zonaId: 8, region: "Metropolitana" },
  { comuna: "Pirque", zonaId: 8, region: "Metropolitana" },
  { comuna: "Providencia", zonaId: 8, region: "Metropolitana" },
  { comuna: "Pudahuel", zonaId: 7, region: "Metropolitana" },
  { comuna: "Puente Alto", zonaId: 8, region: "Metropolitana" },
  { comuna: "Quilicura", zonaId: 8, region: "Metropolitana" },
  { comuna: "Quinta Normal", zonaId: 8, region: "Metropolitana" },
  { comuna: "Recoleta", zonaId: 8, region: "Metropolitana" },
  { comuna: "Renca", zonaId: 8, region: "Metropolitana" },
  { comuna: "San Bernardo", zonaId: 8, region: "Metropolitana" },
  { comuna: "San Joaquín", zonaId: 8, region: "Metropolitana" },
  { comuna: "San José de Maipo", zonaId: 8, region: "Metropolitana" },
  { comuna: "San Miguel", zonaId: 8, region: "Metropolitana" },
  { comuna: "San Pedro", zonaId: 9, region: "Metropolitana" },
  { comuna: "San Ramón", zonaId: 8, region: "Metropolitana" },
  { comuna: "Santiago", zonaId: 8, region: "Metropolitana" },
  { comuna: "Talagante", zonaId: 8, region: "Metropolitana" },
  { comuna: "Til Til", zonaId: 7, region: "Metropolitana" },
  { comuna: "Vitacura", zonaId: 8, region: "Metropolitana" },
  { comuna: "Ñuñoa", zonaId: 8, region: "Metropolitana" },
  { comuna: "Chimbarongo", zonaId: 10, region: "O'Higgins" },
  { comuna: "Chépica", zonaId: 10, region: "O'Higgins" },
  { comuna: "Codegua", zonaId: 10, region: "O'Higgins" },
  { comuna: "Coinco", zonaId: 10, region: "O'Higgins" },
  { comuna: "Coltauco", zonaId: 12, region: "O'Higgins" },
  { comuna: "Doñihue", zonaId: 12, region: "O'Higgins" },
  { comuna: "Graneros", zonaId: 10, region: "O'Higgins" },
  { comuna: "La Estrella", zonaId: 11, region: "O'Higgins" },
  { comuna: "Las Cabras", zonaId: 12, region: "O'Higgins" },
  { comuna: "Litueche", zonaId: 11, region: "O'Higgins" },
  { comuna: "Lolol", zonaId: 11, region: "O'Higgins" },
  { comuna: "Machalí", zonaId: 10, region: "O'Higgins" },
  { comuna: "Malloa", zonaId: 10, region: "O'Higgins" },
  { comuna: "Marchigüe", zonaId: 11, region: "O'Higgins" },
  { comuna: "Mostazal", zonaId: 10, region: "O'Higgins" },
  { comuna: "Nancagua", zonaId: 10, region: "O'Higgins" },
  { comuna: "Navidad", zonaId: 11, region: "O'Higgins" },
  { comuna: "Olivar", zonaId: 10, region: "O'Higgins" },
  { comuna: "Palmilla", zonaId: 10, region: "O'Higgins" },
  { comuna: "Paredones", zonaId: 11, region: "O'Higgins" },
  { comuna: "Peralillo", zonaId: 10, region: "O'Higgins" },
  { comuna: "Peumo", zonaId: 12, region: "O'Higgins" },
  { comuna: "Pichidegua", zonaId: 10, region: "O'Higgins" },
  { comuna: "Pichilemu", zonaId: 11, region: "O'Higgins" },
  { comuna: "Placilla", zonaId: 10, region: "O'Higgins" },
  { comuna: "Pumanque", zonaId: 11, region: "O'Higgins" },
  { comuna: "Quinta de Tilcoco", zonaId: 10, region: "O'Higgins" },
  { comuna: "Rancagua", zonaId: 10, region: "O'Higgins" },
  { comuna: "Rengo", zonaId: 10, region: "O'Higgins" },
  { comuna: "Requínoa", zonaId: 10, region: "O'Higgins" },
  { comuna: "San Fernando", zonaId: 10, region: "O'Higgins" },
  { comuna: "San Vicente", zonaId: 10, region: "O'Higgins" },
  { comuna: "Santa Cruz", zonaId: 10, region: "O'Higgins" },
  { comuna: "Cauquenes", zonaId: 14, region: "Maule" },
  { comuna: "Chanco", zonaId: 14, region: "Maule" },
  { comuna: "Colbún", zonaId: 14, region: "Maule" },
  { comuna: "Constitución", zonaId: 14, region: "Maule" },
  { comuna: "Curepto", zonaId: 14, region: "Maule" },
  { comuna: "Curicó", zonaId: 13, region: "Maule" },
  { comuna: "Empedrado", zonaId: 14, region: "Maule" },
  { comuna: "Hualañé", zonaId: 13, region: "Maule" },
  { comuna: "Licantén", zonaId: 13, region: "Maule" },
  { comuna: "Linares", zonaId: 14, region: "Maule" },
  { comuna: "Longaví", zonaId: 14, region: "Maule" },
  { comuna: "Maule", zonaId: 14, region: "Maule" },
  { comuna: "Molina", zonaId: 13, region: "Maule" },
  { comuna: "Parral", zonaId: 14, region: "Maule" },
  { comuna: "Pelarco", zonaId: 14, region: "Maule" },
  { comuna: "Pelluhue", zonaId: 14, region: "Maule" },
  { comuna: "Pencahue", zonaId: 14, region: "Maule" },
  { comuna: "Rauco", zonaId: 13, region: "Maule" },
  { comuna: "Retiro", zonaId: 14, region: "Maule" },
  { comuna: "Romeral", zonaId: 13, region: "Maule" },
  { comuna: "Río Claro", zonaId: 14, region: "Maule" },
  { comuna: "Sagrada Familia", zonaId: 13, region: "Maule" },
  { comuna: "San Clemente", zonaId: 14, region: "Maule" },
  { comuna: "San Javier", zonaId: 14, region: "Maule" },
  { comuna: "San Rafael", zonaId: 14, region: "Maule" },
  { comuna: "Talca", zonaId: 14, region: "Maule" },
  { comuna: "Teno", zonaId: 13, region: "Maule" },
  { comuna: "Vichuquén", zonaId: 13, region: "Maule" },
  { comuna: "Villa Alegre", zonaId: 14, region: "Maule" },
  { comuna: "Yerbas Buenas", zonaId: 14, region: "Maule" },
  { comuna: "Bulnes", zonaId: 15, region: "Ñuble" },
  { comuna: "Chillán", zonaId: 15, region: "Ñuble" },
  { comuna: "Chillán Viejo", zonaId: 15, region: "Ñuble" },
  { comuna: "Cobquecura", zonaId: 15, region: "Ñuble" },
  { comuna: "Coelemu", zonaId: 15, region: "Ñuble" },
  { comuna: "Coihueco", zonaId: 15, region: "Ñuble" },
  { comuna: "El Carmen", zonaId: 15, region: "Ñuble" },
  { comuna: "Ninhue", zonaId: 15, region: "Ñuble" },
  { comuna: "Pemuco", zonaId: 15, region: "Ñuble" },
  { comuna: "Pinto", zonaId: 15, region: "Ñuble" },
  { comuna: "Portezuelo", zonaId: 15, region: "Ñuble" },
  { comuna: "Quillón", zonaId: 15, region: "Ñuble" },
  { comuna: "Quirihue", zonaId: 15, region: "Ñuble" },
  { comuna: "Ránquil", zonaId: 15, region: "Ñuble" },
  { comuna: "San Carlos", zonaId: 15, region: "Ñuble" },
  { comuna: "San Fabián", zonaId: 15, region: "Ñuble" },
  { comuna: "San Ignacio", zonaId: 15, region: "Ñuble" },
  { comuna: "San Nicolás", zonaId: 15, region: "Ñuble" },
  { comuna: "Treguaco", zonaId: 15, region: "Ñuble" },
  { comuna: "Yungay", zonaId: 15, region: "Ñuble" },
  { comuna: "Ñiquén", zonaId: 15, region: "Ñuble" },
  { comuna: "Alto Biobío", zonaId: 16, region: "Biobío" },
  { comuna: "Antuco", zonaId: 16, region: "Biobío" },
  { comuna: "Arauco", zonaId: 17, region: "Biobío" },
  { comuna: "Cabrero", zonaId: 16, region: "Biobío" },
  { comuna: "Cañete", zonaId: 17, region: "Biobío" },
  { comuna: "Chiguayante", zonaId: 17, region: "Biobío" },
  { comuna: "Concepción", zonaId: 17, region: "Biobío" },
  { comuna: "Contulmo", zonaId: 17, region: "Biobío" },
  { comuna: "Coronel", zonaId: 17, region: "Biobío" },
  { comuna: "Curanilahue", zonaId: 17, region: "Biobío" },
  { comuna: "Florida", zonaId: 16, region: "Biobío" },
  { comuna: "Hualpén", zonaId: 17, region: "Biobío" },
  { comuna: "Hualqui", zonaId: 17, region: "Biobío" },
  { comuna: "Laja", zonaId: 16, region: "Biobío" },
  { comuna: "Lebu", zonaId: 17, region: "Biobío" },
  { comuna: "Los Angeles", zonaId: 16, region: "Biobío" },
  { comuna: "Los Álamos", zonaId: 17, region: "Biobío" },
  { comuna: "Lota", zonaId: 17, region: "Biobío" },
  { comuna: "Mulchén", zonaId: 16, region: "Biobío" },
  { comuna: "Nacimiento", zonaId: 16, region: "Biobío" },
  { comuna: "Negrete", zonaId: 16, region: "Biobío" },
  { comuna: "Penco", zonaId: 17, region: "Biobío" },
  { comuna: "Quilaco", zonaId: 16, region: "Biobío" },
  { comuna: "Quilleco", zonaId: 16, region: "Biobío" },
  { comuna: "San Pedro de la Paz", zonaId: 17, region: "Biobío" },
  { comuna: "San Rosendo", zonaId: 16, region: "Biobío" },
  { comuna: "Santa Bárbara", zonaId: 16, region: "Biobío" },
  { comuna: "Santa Juana", zonaId: 16, region: "Biobío" },
  { comuna: "Talcahuano", zonaId: 17, region: "Biobío" },
  { comuna: "Tirúa", zonaId: 17, region: "Biobío" },
  { comuna: "Tomé", zonaId: 17, region: "Biobío" },
  { comuna: "Tucapel", zonaId: 16, region: "Biobío" },
  { comuna: "Yumbel", zonaId: 16, region: "Biobío" },
  { comuna: "Angol", zonaId: 18, region: "Araucanía" },
  { comuna: "Carahue", zonaId: 18, region: "Araucanía" },
  { comuna: "Cholchol", zonaId: 18, region: "Araucanía" },
  { comuna: "Collipulli", zonaId: 18, region: "Araucanía" },
  { comuna: "Cunco", zonaId: 18, region: "Araucanía" },
  { comuna: "Curacautín", zonaId: 18, region: "Araucanía" },
  { comuna: "Curarrehue", zonaId: 18, region: "Araucanía" },
  { comuna: "Ercilla", zonaId: 18, region: "Araucanía" },
  { comuna: "Freire", zonaId: 18, region: "Araucanía" },
  { comuna: "Galvarino", zonaId: 18, region: "Araucanía" },
  { comuna: "Gorbea", zonaId: 18, region: "Araucanía" },
  { comuna: "Lautaro", zonaId: 18, region: "Araucanía" },
  { comuna: "Loncoche", zonaId: 18, region: "Araucanía" },
  { comuna: "Lonquimay", zonaId: 18, region: "Araucanía" },
  { comuna: "Los Sauces", zonaId: 18, region: "Araucanía" },
  { comuna: "Lumaco", zonaId: 18, region: "Araucanía" },
  { comuna: "Melipeuco", zonaId: 18, region: "Araucanía" },
  { comuna: "Nueva Imperial", zonaId: 18, region: "Araucanía" },
  { comuna: "Padre Las Casas", zonaId: 18, region: "Araucanía" },
  { comuna: "Perquenco", zonaId: 18, region: "Araucanía" },
  { comuna: "Pitrufquén", zonaId: 18, region: "Araucanía" },
  { comuna: "Pucón", zonaId: 18, region: "Araucanía" },
  { comuna: "Purén", zonaId: 18, region: "Araucanía" },
  { comuna: "Renaico", zonaId: 18, region: "Araucanía" },
  { comuna: "Saavedra", zonaId: 18, region: "Araucanía" },
  { comuna: "Temuco", zonaId: 18, region: "Araucanía" },
  { comuna: "Teodoro Schmidt", zonaId: 18, region: "Araucanía" },
  { comuna: "Toltén", zonaId: 18, region: "Araucanía" },
  { comuna: "Traiguén", zonaId: 18, region: "Araucanía" },
  { comuna: "Victoria", zonaId: 18, region: "Araucanía" },
  { comuna: "Vilcún", zonaId: 18, region: "Araucanía" },
  { comuna: "Villarrica", zonaId: 18, region: "Araucanía" },
  { comuna: "Corral", zonaId: 19, region: "Los Ríos" },
  { comuna: "Futrono", zonaId: 19, region: "Los Ríos" },
  { comuna: "La Unión", zonaId: 19, region: "Los Ríos" },
  { comuna: "Lago Ranco", zonaId: 19, region: "Los Ríos" },
  { comuna: "Lanco", zonaId: 19, region: "Los Ríos" },
  { comuna: "Los Lagos", zonaId: 19, region: "Los Ríos" },
  { comuna: "Mariquina", zonaId: 19, region: "Los Ríos" },
  { comuna: "Máfil", zonaId: 19, region: "Los Ríos" },
  { comuna: "Paillaco", zonaId: 19, region: "Los Ríos" },
  { comuna: "Panguipulli", zonaId: 19, region: "Los Ríos" },
  { comuna: "Río Bueno", zonaId: 19, region: "Los Ríos" },
  { comuna: "Valdivia", zonaId: 19, region: "Los Ríos" },
  { comuna: "Ancud", zonaId: 20, region: "Los Lagos" },
  { comuna: "Calbuco", zonaId: 20, region: "Los Lagos" },
  { comuna: "Castro", zonaId: 20, region: "Los Lagos" },
  { comuna: "Chaitén", zonaId: 20, region: "Los Lagos" },
  { comuna: "Chonchi", zonaId: 20, region: "Los Lagos" },
  { comuna: "Cochamó", zonaId: 20, region: "Los Lagos" },
  { comuna: "Curaco de Vélez", zonaId: 20, region: "Los Lagos" },
  { comuna: "Dalcahue", zonaId: 20, region: "Los Lagos" },
  { comuna: "Fresia", zonaId: 20, region: "Los Lagos" },
  { comuna: "Frutillar", zonaId: 20, region: "Los Lagos" },
  { comuna: "Futaleufú", zonaId: 20, region: "Los Lagos" },
  { comuna: "Hualaihué", zonaId: 20, region: "Los Lagos" },
  { comuna: "Llanquihue", zonaId: 20, region: "Los Lagos" },
  { comuna: "Los Muermos", zonaId: 20, region: "Los Lagos" },
  { comuna: "Maullín", zonaId: 20, region: "Los Lagos" },
  { comuna: "Osorno", zonaId: 20, region: "Los Lagos" },
  { comuna: "Palena", zonaId: 20, region: "Los Lagos" },
  { comuna: "Puerto Montt", zonaId: 20, region: "Los Lagos" },
  { comuna: "Puerto Octay", zonaId: 20, region: "Los Lagos" },
  { comuna: "Puerto Varas", zonaId: 20, region: "Los Lagos" },
  { comuna: "Puqueldón", zonaId: 20, region: "Los Lagos" },
  { comuna: "Purranque", zonaId: 20, region: "Los Lagos" },
  { comuna: "Puyehue", zonaId: 20, region: "Los Lagos" },
  { comuna: "Queilén", zonaId: 20, region: "Los Lagos" },
  { comuna: "Quellón", zonaId: 20, region: "Los Lagos" },
  { comuna: "Quemchi", zonaId: 20, region: "Los Lagos" },
  { comuna: "Quinchao", zonaId: 20, region: "Los Lagos" },
  { comuna: "Río Negro", zonaId: 20, region: "Los Lagos" },
  { comuna: "San Juan de la Costa", zonaId: 20, region: "Los Lagos" },
  { comuna: "San Pablo", zonaId: 20, region: "Los Lagos" },
  { comuna: "Aysén", zonaId: 20, region: "Aysén" },
  { comuna: "Chile Chico", zonaId: 20, region: "Aysén" },
  { comuna: "Cisnes", zonaId: 20, region: "Aysén" },
  { comuna: "Cochrane", zonaId: 20, region: "Aysén" },
  { comuna: "Coyhaique", zonaId: 20, region: "Aysén" },
  { comuna: "Guaitecas", zonaId: 20, region: "Aysén" },
  { comuna: "Lago Verde", zonaId: 20, region: "Aysén" },
  { comuna: "O'Higgins", zonaId: 20, region: "Aysén" },
  { comuna: "Río Ibáñez", zonaId: 20, region: "Aysén" },
  { comuna: "Tortel", zonaId: 20, region: "Aysén" },
  { comuna: "Antártica", zonaId: 20, region: "Magallanes" },
  { comuna: "Cabo de Hornos", zonaId: 20, region: "Magallanes" },
  { comuna: "Laguna Blanca", zonaId: 20, region: "Magallanes" },
  { comuna: "Porvenir", zonaId: 20, region: "Magallanes" },
  { comuna: "Primavera", zonaId: 20, region: "Magallanes" },
  { comuna: "Puerto Natales", zonaId: 20, region: "Magallanes" },
  { comuna: "Punta Arenas", zonaId: 20, region: "Magallanes" },
  { comuna: "Río Verde", zonaId: 20, region: "Magallanes" },
  { comuna: "San Gregorio", zonaId: 20, region: "Magallanes" },
  { comuna: "Timaukel", zonaId: 20, region: "Magallanes" },
  { comuna: "Torres del Paine", zonaId: 20, region: "Magallanes" },
];

function normalizar(texto: string): string {
  return texto.trim().toLowerCase();
}

const COMUNAS_POR_NOMBRE = new Map<string, ComunaEntry>(
  COMUNAS.map((c) => [normalizar(c.comuna), c]),
);

export function buscarComuna(comuna: string): ComunaEntry | null {
  return COMUNAS_POR_NOMBRE.get(normalizar(comuna)) ?? null;
}
