// Autogenerated from legacy app (datos.js / db_detalle.js). Do not edit manually.

export const CONSEJOS: Record<string, string[]> = {
  "Duraznero": [
   "Poda ANUAL obligatoria en junio-julio: el durazno produce en madera del año anterior (Bol. INIA 373).",
   "Cloca (Taphrina deformans): aplicar cobre ANTES de brotación (julio-agosto). Después ya no tiene solución.",
   "Raleo de frutos en noviembre es tan importante como la poda: sin raleo, frutos chicos y alternancia.",
   "Pintar tronco con cal blanca + cobre en invierno: refleja el sol, previene hongos.",
   "Riego por goteo ahorra 50% agua. Mulch de 10-15 cm bajo la copa conserva humedad."
  ],
  "Cerezo": [
   "Poda verde post-cosecha (dic-ene) es preferible a la poda invernal: cicatriza más rápido (INIA Quilamapu).",
   "Calcio foliar (CaCl₂ 0.5%) cada 10-15 días desde cuaja: PREVIENE la partidura por lluvia.",
   "Mallas antipájaros obligatorias: sin ellas pierde el 50-80% de la cosecha.",
   "Cosechar SIEMPRE con el cabito (pedúnculo): sin él la cereza dura solo 1 día.",
   "En Ñuble y zonas sur, la cosecha es 2-3 semanas más tarde que en O'Higgins."
  ],
  "Arandano": [
   "pH ÁCIDO 4.5-5.5 es la REGLA N°1. Un arándano en suelo neutro o alcalino no produce.",
   "NUNCA aplicar cal, ceniza ni guano de gallina: suben el pH y matan al arándano.",
   "Mulch ácido PERMANENTE: aserrín o corteza de pino. Descomponiéndose mantiene el pH bajo.",
   "En Ñuble: cosecha de diciembre a inicios de marzo. NO esperar mayo.",
   "Plantar 2+ variedades para polinización cruzada y mayor rendimiento.",
   "Drosophila suzukii: instalar trampas de vinagre de manzana desde noviembre (INIA)."
  ],
  "Ciruelo": [
   "Ciruelo japonés (Santa Rosa, Angeleno) necesita menos frío que el europeo (D'Agen): más adaptable en zona central.",
   "Verificar en vivero si la variedad necesita polinizador: muchas lo requieren.",
   "D'Agen es la mejor ciruela del mundo para deshidratar: alta en azúcar y pectina.",
   "Pintar tronco con cal + cobre en invierno: previene hongos y quemaduras solares.",
   "Sellar TODOS los cortes de poda: la enfermedad del Plateado (Chondrostereum) entra por heridas."
  ],
  "Damasco": [
   "Florece en agosto: mayor riesgo de helada tardía de todos los frutales. Use Tilton o Goldcot en zonas con heladas.",
   "Para proteger de heladas: bidones de agua negros bajo la copa liberan calor de noche.",
   "Damasco deshidratado al sol (orejones): la concentración de azúcar se multiplica por 4.",
   "El carozo del damasco contiene amigdalina (cianuro): NO comer la almendra interior.",
   "Variedad Tilton: más productiva Y tolerante a heladas. La más plantada en Chile."
  ],
  "Nectarino": [
   "El nectarino ES un duraznero sin pelusa: todo el manejo del Bol. INIA 373 aplica.",
   "Más sensible a cloca que el durazno: cobre preventivo en julio-agosto es OBLIGATORIO.",
   "Piel lisa se daña más fácil: cosechar con cuidado y no apilar en el cajón.",
   "Raleo más intenso que en durazno: el mercado exige calibre grande.",
   "Fantasia y Independence: pulpa amarilla aromática. Arctic Star: pulpa blanca dulce."
  ],
  "Manzano": [
   "NECESITA POLINIZADOR: plante 2+ variedades que florezcan al mismo tiempo. Gala + Fuji es combinación clásica.",
   "Calcio foliar MENSUAL (noviembre a febrero) previene el Bitter Pit (manchas marrones en poscosecha).",
   "Carpocapsa (gusano de la manzana): enemigo N°1. Trampas de feromona desde octubre obligatorias.",
   "La manzana mejora sabor semanas después de cosechada: almidón → azúcar en el frío.",
   "Variedades enanas (portainjerto M9) producen en 2-3 años y caben en patios chicos."
  ],
  "Peral": [
   "Cosechar VERDE FIRME y madurar en casa: en el árbol la pera se pone harinosa.",
   "NECESITA polinizador: Packham's + Williams es la combinación clásica.",
   "Fuego bacteriano (Erwinia): cortar 30 cm más abajo del síntoma y desinfectar la tijera ENTRE CADA CORTE.",
   "El peral vive 50+ años produciendo: es inversión de largo plazo.",
   "Pera asiática (Nashi) se cosecha MADURA del árbol (al revés de la europea): crocante como manzana."
  ],
  "Membrillo": [
   "Probablemente el frutal MÁS FÁCIL: tolera sequía, suelos pobres y casi cualquier condición.",
   "NO se come crudo: los taninos se descomponen con el calor de la cocción (mermelada, dulce).",
   "El aroma del membrillo perfuma toda la casa: úselo como ambientador natural.",
   "Es AUTOFÉRTIL: un solo árbol produce abundantemente sin necesitar otro.",
   "Vive 50+ años con casi cero cuidados. El dulce de membrillo casero tiene alto valor."
  ],
  "Limonero": [
   "Limonero perfecto para principiantes: produce mucho, durante años. NO en zonas con heladas fuertes (-3°C lo mata).",
   "Cochinilla = enemigo principal: aceite mineral mensual. El aceite ahoga a la cochinilla tapando sus poros (Bol. INIA 282).",
   "Hojas amarillas con venas verdes (clorosis): no es falta de hierro, es pH alto. Aplicar quelato EDDHA.",
   "NUNCA regar el tronco: Phytophthora (gomosis) entra por la corteza húmeda. Goteo a 30 cm del tronco.",
   "Variedad Meyer: semi-dulce, tolera -4°C, ideal para zona central protegida.",
   "Si bota hojas = ALERTA: algo está muy mal (raíz, frío, sequía extrema)."
  ],
  "Naranjo": [
   "La flor del naranjo (azahar) perfuma todo el jardín en primavera.",
   "W. Navel: mejor para mesa, sin pepas. Valencia: mejor para jugo (cosecha tardía ago-oct).",
   "El color naranja se desarrolla con frío nocturno: en zonas calurosas puede madurar pero quedar verde.",
   "Más sensible al frío que el limonero: -2°C ya produce daño. Proteger de heladas.",
   "La naranja puede quedarse semanas en el árbol sin perder calidad."
  ],
  "Mandarino": [
   "Árbol compacto (3-5 m): ideal para patios y espacios reducidos.",
   "Clemenules: sin semillas, fácil de pelar, la más popular de Chile.",
   "Más resistente al frío que el naranjo (-4°C vs -2°C): mejor opción en zona central.",
   "Si las mandarinas se rajan: RIEGO IRREGULAR. Regar parejo sin altibajos seco→mojado.",
   "Trips en floración: deja cicatrices plateadas en la fruta (daño estético, no sanitario)."
  ],
  "Pomelo": [
   "Pomelo necesita MUCHO ESPACIO: hasta 6-10 metros. Plante lejos de construcciones.",
   "Mejor sabor en INVIERNO: el frío reduce la naringina (amargo) y concentra azúcares.",
   "ATENCIÓN MÉDICA: el pomelo interactúa con muchos medicamentos (estatinas, antihistamínicos).",
   "Star Ruby: rosado, dulce, sin pepas. Marsh: blanco, clásico.",
   "El pomelo puede quedarse meses en el árbol sin perder calidad."
  ],
  "Nogal": [
   "Boro y zinc foliares en octubre = práctica MÁS IMPORTANTE para calidad de nuez (Bol. INIA 454).",
   "NECESITA polinizador: Chandler necesita Franquette o Serr cerca. Verificar con el vivero.",
   "Secar bien antes de guardar: húmedas se enmohecen y producen aflatoxinas (tóxicas).",
   "Nogal produce JUGLONA: NO plantar hortalizas bajo la copa (les es tóxica).",
   "Si la nuez está vacía o negra: faltó agua en enero-febrero (etapa de llenado).",
   "Árbol generacional: produce 100+ años. RM concentra 15.521 ha (ODEPA)."
  ],
  "Almendro": [
   "Florece en agosto: si su zona tiene heladas en ago-sep, plante Guara o Tuono (floración tardía).",
   "Guara es AUTOFÉRTIL: no necesita polinizador. Ideal para jardines con un solo árbol.",
   "Tolera SEQUÍA mejor que casi cualquier frutal: adaptado al mediterráneo seco.",
   "Almendras AMARGAS son TÓXICAS (amigdalina → cianuro): comprar SOLO en viveros certificados.",
   "La floración del almendro (agosto) es espectacular: blanca y masiva."
  ],
  "Higuera": [
   "Probablemente el frutal MÁS FÁCIL del mundo: crece en suelos pésimos, poca agua, abandono.",
   "Produce en 1-2 años: gratificación rápida.",
   "El higo fresco NO dura: comerlo rápido, deshidratar al sol o congelar. No es como manzana.",
   "El látex IRRITA la piel: use guantes al cosechar y podar.",
   "Brown Turkey y Kadota dan DOS cosechas: brevas (diciembre) e higos (febrero-marzo)."
  ],
  "Granado": [
   "RAJADO = RIEGO IRREGULAR. La regla N°1 del granado: regar PAREJO, nunca seco y después inundar.",
   "Wonderful: la variedad más plantada del mundo. Granos grandes, rojos, dulces.",
   "Las flores rojas son espectaculares: es ornamental Y productivo.",
   "Jugo de granada: altísimo en antocianinas (antioxidantes potentes).",
   "Quitar hijuelos de la base CADA INVIERNO: si no, se vuelve matorral improductivo."
  ],
  "Caqui": [
   "HAY DOS TIPOS: Fuyu (comer DURO, como manzana) y Hachiya (comer BLANDO, como gelatina). Pregunte en vivero.",
   "Truco para madurar Hachiya rápido: poner con manzanas o bananas en bolsa cerrada (gas etileno).",
   "Caqui brota MUY TARDE (octubre): si en septiembre parece muerto, es normal. No lo arranque.",
   "Muy ornamental en otoño: hojas rojas espectaculares antes de caer.",
   "Tolera -15°C en reposo: se puede plantar en zonas bastante frías.",
   "Caqui deshidratado (Hoshigaki): delicatessen japonesa, se masajea diariamente 4-6 semanas."
  ],
  "Vid": [
   "PODA INVERNAL OBLIGATORIA cada julio: sin poda, la vid no produce fruta de calidad (Bol. INIA 383).",
   "Oidio = enemigo N°1: azufre preventivo cada 15 días desde brotación. Sin azufre, pierde la cosecha.",
   "SIEMPRE plantar vid injertada sobre portainjerto americano: protege de Filoxera.",
   "El parrón domiciliario da sombra en verano + uva para la mesa.",
   "Deshoje en enero: expone racimos a luz y aire → color, salud y calidad.",
   "Crimson Seedless o Thompson: uva sin pepa. País o Italia: clásico parrón chileno."
  ],
  "Olivo": [
   "Olivo es para TODA LA VIDA: vive 100+ años. Plante uno y sus nietos lo disfrutarán.",
   "NUNCA plantar donde hubo tomate, papa, pimiento o berenjena: Verticilium del suelo mata al olivo.",
   "Boro foliar en floración (noviembre) = práctica MÁS IMPORTANTE para la cuaja.",
   "Olivo tiene VECERÍA (alternancia): un año mucho, otro poco. Poda de aclareo atenúa esto.",
   "Para aceitunas de mesa: cosechar VERDES y curar en salmuera (8% sal + laurel) por 2-6 meses.",
   "Arbequina: mejor variedad para aceite en espacio pequeño. Árbol chico, mucho aceite, autofértil.",
   "El aceite de oliva casero necesita 5-8 kg de aceitunas por litro."
  ],
  "Frutilla": [
   "Renueva las plantas cada 2-3 años: el rendimiento cae notoriamente después de la 3.ª temporada.",
   "Mulch permanente (paja, film negro): la diferencia entre frutilla limpia y frutilla podrida.",
   "Riego por goteo, NUNCA aspersión sobre el follaje: reduce Botrytis drásticamente.",
   "Cosechar CADA 2-3 días: la cosecha frecuente estimula la formación de más flores.",
   "Deshija los estolones en plena temporada: si los dejas todos, el fruto sale chico.",
   "Funciona perfectamente en maceta colgante o jardinera: ideal para balcón."
  ],
  "Frambuesa": [
   "Variedades remontantes (Heritage, Autumn Bliss): poda TOTAL en invierno. Sin complejidad.",
   "Chile es el 2.° exportador mundial: Biobío y Araucanía son las zonas de mayor volumen.",
   "Drosophila suzukii (mosca del vinagre): trampa de vinagre + detergente desde noviembre.",
   "La frambuesa necesita FRÍO para rendir bien: veranos frescos del sur son su hábitat ideal.",
   "Tutores o espaldera obligatorios: sin soporte los cañones caen y el fruto se pudre."
  ],
  "Mora": [
   "El frutal más RÚSTICO de todos: tolera suelos pobres, sequía moderada y abandono relativo.",
   "Elige Thornfree o Triple Crown: sin espinas, se trabaja cómodo y rinde igual.",
   "Fruto negro BRILLANTE = listo. Negro OPACO = se pasó. Cosechar diariamente en temporada.",
   "Vigila Drosophila suzukii igual que en frambuesa: trampa de vinagre desde noviembre.",
   "Una planta adulta rinde 3-5 kg/año con mínimo manejo. Productividad muy alta para el esfuerzo."
  ],
  "Kiwi": [
   "NECESITA planta macho: 1 macho por 6-8 hembras. Sin macho no hay fruto. La planta más olvidada.",
   "Hayward: variedad femenina estándar. Matua o Tomuri: masculinas que la acompañan.",
   "Chile es el 3.° exportador mundial: Talca y Curicó concentran el grueso de la producción.",
   "Psa (Pseudomonas): la enfermedad más destructiva del kiwi. Sin síntoma claro al inicio: vigilar.",
   "Cosechar firme en abril y dejar madurar en casa con una manzana (etileno acelera maduración).",
   "La poda de invierno es INTENSA: hasta 70% de la madera se elimina. No tengas miedo."
  ],
  "Avellano Europeo": [
   "Chile produce avellanas de alta calidad: Biobío y Araucanía concentran el 90% de la producción.",
   "NECESITA polinizador: plantar Daviana + Tonda Romana es la combinación clásica.",
   "El avellano se poliniza por viento: plantar 2+ variedades en radio de 50 metros.",
   "Cosecha fácil: los frutos caen solos. Usar malla bajo el árbol y recoger cada 2-3 días.",
   "Secar bien antes de guardar: con humedad se enmohece. Límite máximo 6% de humedad."
  ],
  "Níspero Japonés": [
   "El PRIMER fruto del año: listo en agosto-octubre cuando casi no hay otra fruta fresca.",
   "Árbol ornamental: hoja perenne grande y brillante, atractivo todo el año.",
   "La floración invernal (julio-agosto) es su talón de Aquiles: buscar ubicación protegida del frío.",
   "Autofértil: un solo árbol produce abundantemente sin necesitar otro.",
   "Níspero fresco no dura: consumir o procesar en mermelada en los primeros 3-5 días."
  ],
  "Chirimoya": [
   "Chile es el mayor productor mundial: La Serena, Ovalle y Quillota concentran la producción.",
   "Polinización manual con pincel en la mañana: multiplica la cuaja por 3-4 veces.",
   "NO tolera heladas: -2°C ya daña ramas. Buscar microclima costero protegido.",
   "Fruto maduro = pulpa cremosa blanca con sabor a vainilla-piña. Comerlo con cuchara.",
   "La chirimoya es autoincompatible: la flor no puede fecundarse con su propio polen."
  ],
  "Lúcuma": [
   "Fruto andino único: pulpa seca, harinosa, sabor a caramelo-maple. No tiene par en el mundo.",
   "La lúcuma chilena (variedad Seda) es la referencia mundial de sabor.",
   "NO tolera heladas: temperatura mínima -1°C ya daña la planta. Solo costa norte-centro.",
   "Árbol de LARGO plazo: primera cosecha a los 4-5 años. Vive y produce por décadas.",
   "La pulpa deshidratada en polvo es el producto con mayor valor comercial."
  ],
  "Papayo Chileno": [
   "Especie ÚNICA en el mundo: solo crece en Chile. Fruto en 8-12 meses desde semilla.",
   "Produce TODO EL AÑO en zonas sin heladas: sin pausa, sin estación seca.",
   "El virus de la mancha anular (PRSV) es incurable y se propaga por áfidos. Comprar solo plantas certificadas.",
   "La raíz NO tolera encharcamiento ni siquiera 48 horas: drenaje perfecto es obligatorio.",
   "Fruto inmaduro: se usa cocido como verdura. Maduro: dulce, suave, semillas negras."
  ],
  "Palto": [
   "La raíz muere a las 48 horas de encharcamiento: drenaje perfecto es LA condición N°1.",
   "Hass necesita polinizador tipo B (Fuerte o Edranol): sin él la producción es mínima.",
   "Quillota-La Cruz-Petorca: el triángulo del palto chileno. Las mejores paltas del país.",
   "Phytophthora cinnamomi: el hongo de raíz que más mata paltos. Solo con excelente drenaje se previene.",
   "Chile exporta principalmente Hass: cosecha oct-ene. Edranol y Fuerte: nov-feb.",
   "Cosechar FIRME y dejar madurar en casa (3-7 días). En el árbol puede quedarse meses sin dañarse."
  ]
};

