// Autogenerated from legacy app (datos.js / db_detalle.js). Do not edit manually.

export const GRUPO_DISTANCIA: Record<string, { dist: string; porM2: number }> = {
  "Baya (herbácea perenne)": {
   "dist": "0.3 – 0.4 m entre plantas",
   "porM2": 6
  },
  "Baya": {
   "dist": "1 – 1.5 m entre plantas",
   "porM2": 1
  },
  "Baya (arbusto caducifolio)": {
   "dist": "1 – 1.5 m entre plantas",
   "porM2": 1
  },
  "Baya (arbusto vigoroso)": {
   "dist": "2 – 2.5 m entre plantas",
   "porM2": 0.4
  },
  "Vid": {
   "dist": "2 – 3 m entre plantas (hilera)",
   "porM2": 0.3
  },
  "Trepadora": {
   "dist": "3 – 4 m entre plantas (con estructura)",
   "porM2": 0.15
  },
  "Cítrico": {
   "dist": "4 – 5 m entre árboles",
   "porM2": 0.05
  },
  "Carozo": {
   "dist": "4 – 5 m entre árboles",
   "porM2": 0.05
  },
  "Pomácea": {
   "dist": "4 – 5 m entre árboles",
   "porM2": 0.05
  },
  "Oleáceo": {
   "dist": "6 – 7 m entre árboles",
   "porM2": 0.03
  },
  "Fruto seco": {
   "dist": "6 – 8 m entre árboles",
   "porM2": 0.02
  },
  "Subtropical": {
   "dist": "5 – 7 m entre árboles",
   "porM2": 0.03
  },
  "Subtropical (perennifolio)": {
   "dist": "5 – 7 m entre árboles",
   "porM2": 0.03
  },
  "Otros (subtropical)": {
   "dist": "4 – 6 m entre árboles",
   "porM2": 0.04
  },
  "Otros": {
   "dist": "3 – 4 m entre plantas",
   "porM2": 0.1
  }
};

