// Autogenerated from legacy app (datos.js / db_detalle.js). Do not edit manually.

export type Dificultad = "Fácil" | "Moderado" | "Avanzado" | "Difícil" | "Alto";

export type GrupoFruta =
  | "Carozo" | "Pomácea" | "Cítrico" | "Baya" | "Fruto seco" | "Subtropical" | "Otros";

export interface EspecieFicha {
  riego: string;
  suelo: string;
  cosecha: string;
  plagas: string;
  cuidados: string;
}

export interface Especie {
  id: number;
  slug: string;
  dbKey: string;
  nombre: string;
  imagen: string;
  descripcion: string;
  clima: string;
  dificultad: Dificultad;
  grupo: string;
  ficha: EspecieFicha;
}

export const ESPECIES: Especie[] = [
  {
    id: 1,
    slug: "duraznero",
    dbKey: "Duraznero",
    nombre: "Durazno",
    imagen: "/frutas/duraznero.webp",
    descripcion: "Frutal de hueso muy cultivado en Chile central. Produce abundantemente con poda anual.",
    clima: "Templado, frío invernal y calor estival",
    dificultad: "Fácil",
    grupo: "Carozo",
    ficha: {
      "riego": "Cada 7–10 días en verano. Crítico en cuaja (oct–nov) y llenado de fruto (nov–dic). Reducir 10 días antes de cosechar.",
      "suelo": "Suelto, profundo, bien drenado. pH 6.0–7.0.",
      "cosecha": "Diciembre a febrero según variedad (Elegant Lady, O'Henry, Andross).",
      "plagas": "Cloca (hongo), oidio, monilia, pulgón verde, mosca de la fruta.",
      "cuidados": "Poda obligatoria cada invierno (julio–agosto). Ralear frutos en noviembre. Pintar tronco con cal blanca."
    }
  },
  {
    id: 2,
    slug: "ciruelo",
    dbKey: "Ciruelo",
    nombre: "Ciruela",
    imagen: "/frutas/ciruelo.webp",
    descripcion: "Frutal generoso y longevo. Producción alta una vez establecido con poca intervención.",
    clima: "Templado, tolera bien el frío",
    dificultad: "Fácil",
    grupo: "Carozo",
    ficha: {
      "riego": "Constante en crecimiento y maduración. Reducir 7 días antes de cosecha para concentrar sabor.",
      "suelo": "Bien drenado, tolera suelos algo arcillosos. pH 6.0–7.5.",
      "cosecha": "Diciembre a marzo según variedad (Santa Rosa, Black Amber, D'Agen para deshidratar).",
      "plagas": "Monilia, pulgón ceniciento, mosca de la fruta, cancrosis.",
      "cuidados": "Algunas variedades necesitan polinizador (consultar en vivero). Poda invernal. Ralear frutos."
    }
  },
  {
    id: 3,
    slug: "cerezo",
    dbKey: "Cerezo",
    nombre: "Cereza",
    imagen: "/frutas/cerezo.webp",
    descripcion: "Chile es uno de los mayores exportadores mundiales de cereza. Exige buen drenaje y frío invernal.",
    clima: "Templado-frío, veranos suaves",
    dificultad: "Moderado",
    grupo: "Carozo",
    ficha: {
      "riego": "Constante pero REDUCIR antes de maduración para evitar que las cerezas se partan. Crítico en cuaja.",
      "suelo": "Profundo, MUY bien drenado. pH 6.5–7.5. No tolera encharcamiento.",
      "cosecha": "Noviembre a enero. Cosechar CON el cabito (palito); sin él dura solo 1 día.",
      "plagas": "Mosca de la cereza, monilia, pulgón negro. Pájaros: proteger con mallas.",
      "cuidados": "Mallas anti-pájaros indispensables. Calcio foliar previene partidura por lluvia. Necesita polinizador (salvo Lapins)."
    }
  },
  {
    id: 4,
    slug: "damasco",
    dbKey: "Damasco",
    nombre: "Damasco",
    imagen: "/frutas/damasco.webp",
    descripcion: "Uno de los primeros frutos del verano. Florece en agosto y requiere protección ante heladas tardías.",
    clima: "Templado con inviernos fríos",
    dificultad: "Moderado",
    grupo: "Carozo",
    ficha: {
      "riego": "Regular desde brotación. Crítico en cuaja y crecimiento. Reducir antes de cosecha.",
      "suelo": "Suelto, bien drenado, profundo. pH 6.5–8.0.",
      "cosecha": "Noviembre a enero (uno de los primeros frutos del verano).",
      "plagas": "Monilia en floración, pulgón verde, mosca de la fruta. Virus Sharka sin cura: comprar en viveros certificados.",
      "cuidados": "Florece en agosto: proteger de heladas con bidones de agua. Ralear frutos en octubre."
    }
  },
  {
    id: 5,
    slug: "nectarino",
    dbKey: "Nectarino",
    nombre: "Nectarín",
    imagen: "/frutas/nectarino.webp",
    descripcion: "El durazno sin pelusa. Se cuida igual pero es más sensible a la cloca (hongo foliar).",
    clima: "Templado, frío invernal y calor estival",
    dificultad: "Fácil",
    grupo: "Carozo",
    ficha: {
      "riego": "Igual que durazno. Crítico en cuaja (oct–nov) y llenado del fruto (nov–dic).",
      "suelo": "Suelto, profundo, bien drenado. pH 6.0–7.0.",
      "cosecha": "Diciembre a febrero según variedad (Independence, Fantasia, Big Top).",
      "plagas": "Más sensible a cloca que durazno (cobre preventivo obligatorio en julio–agosto). Oidio, monilia, mosca de la fruta.",
      "cuidados": "Poda anual obligatoria. Ralear frutos en noviembre. Pintar tronco con cal blanca."
    }
  },
  {
    id: 6,
    slug: "manzano",
    dbKey: "Manzano",
    nombre: "Manzana",
    imagen: "/frutas/manzano.webp",
    descripcion: "Frutal clásico de larga vida (30–50 años). Necesita polinizador y frío invernal para producir bien.",
    clima: "Templado-frío",
    dificultad: "Moderado",
    grupo: "Pomácea",
    ficha: {
      "riego": "Cada 5–10 días en verano. Calcio foliar mensual desde noviembre previene Bitter Pit (manchas marrones).",
      "suelo": "Profundo, fértil, bien drenado. pH 6.0–7.0.",
      "cosecha": "Febrero a mayo según variedad (Gala temprana, Fuji y Granny Smith tardías).",
      "plagas": "Carpocapsa (gusano de la manzana, principal), sarna del manzano, oidio, pulgón lanígero.",
      "cuidados": "Necesita polinizador (plantar 2 variedades distintas). Ralear frutos en noviembre. Poda invernal."
    }
  },
  {
    id: 7,
    slug: "peral",
    dbKey: "Peral",
    nombre: "Pera",
    imagen: "/frutas/peral.webp",
    descripcion: "Se cosecha verde y madura en casa. Árbol longevo de hasta 50 años. Necesita polinizador.",
    clima: "Templado, tolera frío",
    dificultad: "Moderado",
    grupo: "Pomácea",
    ficha: {
      "riego": "Constante en crecimiento. Calcio foliar para firmeza del fruto.",
      "suelo": "Profundo, drenado. pH 6.0–7.5. Tolera mejor la arcilla que el manzano.",
      "cosecha": "Febrero a abril. Cosechar FIRME y verde: madura en casa o en frío, no en el árbol.",
      "plagas": "Fuego bacteriano (principal, brotes negros quemados), carpocapsa, psila del peral, sarna.",
      "cuidados": "Necesita polinizador. Ante fuego bacteriano: cortar 30 cm más abajo y desinfectar tijera con alcohol."
    }
  },
  {
    id: 8,
    slug: "membrillo",
    dbKey: "Membrillo",
    nombre: "Membrillo",
    imagen: "/frutas/membrillo.webp",
    descripcion: "Uno de los frutales más fáciles y longevos (50+ años). Ideal para mermelada y dulce casero.",
    clima: "Templado, muy tolerante",
    dificultad: "Fácil",
    grupo: "Pomácea",
    ficha: {
      "riego": "Regular pero tolera sequía moderada. Menos exigente que otros frutales de la familia.",
      "suelo": "Tolera gran variedad de suelos, incluso algo húmedos. pH 6.0–7.5.",
      "cosecha": "Abril a junio. Está listo cuando adquiere color amarillo intenso y aroma muy fuerte.",
      "plagas": "Fuego bacteriano, polilla oriental. Sanitariamente muy poco exigente.",
      "cuidados": "No se come crudo (astringente). Autofértil: no necesita polinizador. Olor perfuma el hogar."
    }
  },
  {
    id: 9,
    slug: "limonero",
    dbKey: "Limonero",
    nombre: "Limón",
    imagen: "/frutas/limonero.webp",
    descripcion: "Produce casi todo el año. Perfecto para principiantes en zonas templado-cálidas sin heladas fuertes.",
    clima: "Subtropical y templado cálido",
    dificultad: "Fácil",
    grupo: "Cítrico",
    ficha: {
      "riego": "Cada 4–10 días según temporada. Crítico en verano (cada 4 días). Siempreverde: nunca cortar del todo el riego.",
      "suelo": "Bien drenado, NO encharcado. pH 6.0–7.0.",
      "cosecha": "Casi todo el año, pico mayo–septiembre (100–400 kg por árbol adulto).",
      "plagas": "Cochinilla (principal: aceite mineral mensual), pulgón, mosca blanca, minador de hojas, clorosis férrica.",
      "cuidados": "No tolera heladas fuertes (-3 °C lo daña, -5 °C lo mata). Pintar tronco con cal blanca. Variedad Meyer es semi-dulce."
    }
  },
  {
    id: 10,
    slug: "naranjo",
    dbKey: "Naranjo",
    nombre: "Naranja",
    imagen: "/frutas/naranjo.webp",
    descripcion: "Cítrico de larga vida (40–60 años). La floración de azahar perfuma todo el jardín.",
    clima: "Subtropical y templado cálido",
    dificultad: "Fácil",
    grupo: "Cítrico",
    ficha: {
      "riego": "Cada 4–10 días según temporada. Más exigente en verano (cada 4–5 días).",
      "suelo": "Drenado, profundo, fértil. pH 6.0–7.0.",
      "cosecha": "Mayo a octubre según variedad (Navel temprana, Valencia tardía para jugo).",
      "plagas": "Cochinilla, pulgón, mosca blanca, clorosis férrica.",
      "cuidados": "No tolera heladas fuertes. Aceite mineral mensual contra cochinilla. Las naranjas pueden quedar semanas en el árbol sin perder calidad."
    }
  },
  {
    id: 11,
    slug: "mandarino",
    dbKey: "Mandarino",
    nombre: "Mandarina",
    imagen: "/frutas/mandarino.webp",
    descripcion: "Árbol compacto, ideal para patios. Más resistente al frío que el naranjo.",
    clima: "Subtropical-templado",
    dificultad: "Fácil",
    grupo: "Cítrico",
    ficha: {
      "riego": "Cada 4–10 días según temporada.",
      "suelo": "Drenado, fértil. pH 6.0–7.0.",
      "cosecha": "Abril a septiembre según variedad. Clemenules: sin semillas, fácil de pelar.",
      "plagas": "Cochinilla, pulgón, trips en floración, clorosis férrica.",
      "cuidados": "Árbol pequeño (3–5 m): ideal para espacios reducidos. Si las mandarinas se rajan: riegue de forma más uniforme."
    }
  },
  {
    id: 12,
    slug: "pomelo",
    dbKey: "Pomelo",
    nombre: "Pomelo",
    imagen: "/frutas/pomelo.webp",
    descripcion: "Cítrico grande y longevo. El fruto mejora su sabor con el frío invernal.",
    clima: "Subtropical y templado cálido",
    dificultad: "Fácil",
    grupo: "Cítrico",
    ficha: {
      "riego": "Cada 4–10 días. Mayor volumen por ser árbol grande (70–90 litros en verano).",
      "suelo": "Drenado, profundo. pH 6.0–7.0.",
      "cosecha": "Junio a octubre. Mejor sabor en invierno. Aguarda semanas en el árbol sin perder calidad.",
      "plagas": "Cochinilla, pulgón, mancha grasienta en hojas.",
      "cuidados": "Necesita mucho espacio (6–10 m). ATENCIÓN: el pomelo interactúa con algunos medicamentos."
    }
  },
  {
    id: 13,
    slug: "nogal",
    dbKey: "Nogal",
    nombre: "Nuez",
    imagen: "/frutas/nogal.webp",
    descripcion: "Árbol de gran tamaño y vida centenaria. Inversión generacional con alta demanda de nueces.",
    clima: "Templado con inviernos fríos",
    dificultad: "Fácil",
    grupo: "Fruto seco",
    ficha: {
      "riego": "Gran volumen por ser árbol grande. CRÍTICO en enero–febrero (llenado de nuez): nuez vacía = faltó agua.",
      "suelo": "Profundo (raíz pivotante), bien drenado, fértil. pH 6.5–7.5.",
      "cosecha": "Marzo a mayo. La cáscara verde exterior se abre sola al madurar.",
      "plagas": "Peste negra (Xanthomonas), polilla del nogal, pulgón del nogal.",
      "cuidados": "Mínimo 10 m de espacio. Necesita polinizador. Boro y zinc foliares en octubre son críticos. No plantar hortalizas bajo su copa (produce juglona)."
    }
  },
  {
    id: 14,
    slug: "almendro",
    dbKey: "Almendro",
    nombre: "Almendra",
    imagen: "/frutas/almendro.webp",
    descripcion: "Florece espectacularmente en agosto. Muy tolerante a la sequía una vez establecido.",
    clima: "Mediterráneo seco",
    dificultad: "Moderado",
    grupo: "Fruto seco",
    ficha: {
      "riego": "Tolera sequía pero crítico en cuaja y llenado. Reducir mucho en maduración.",
      "suelo": "Drenado, tolera pedregoso y pobre. pH 7.0–8.0. No tolera encharcamiento.",
      "cosecha": "Febrero a abril. Sacudir ramas: la cáscara verde seca y abierta indica madurez.",
      "plagas": "Monilia en floración (agosto), cloca, polilla de la almendra.",
      "cuidados": "Florece en agosto: proteger de heladas. Variedad Guara: autofértil, no necesita polinizador. Las almendras amargas son tóxicas."
    }
  },
  {
    id: 15,
    slug: "higuera",
    dbKey: "Higuera",
    nombre: "Higo",
    imagen: "/frutas/higuera.webp",
    descripcion: "Probablemente el frutal más fácil del mundo. Produce en 1–2 años y tolera casi cualquier condición.",
    clima: "Mediterráneo, muy tolerante",
    dificultad: "Fácil",
    grupo: "Otros",
    ficha: {
      "riego": "Moderado. Muy resistente a sequía una vez establecida. No encharcar.",
      "suelo": "Tolera casi todo: arcilloso, pedregoso, pobre. pH 6.0–8.5.",
      "cosecha": "Diciembre–enero (brevas, primera cosecha) + febrero–marzo (higos, cosecha principal). Usar guantes: el látex irrita la piel.",
      "plagas": "Mosca del higo, cochinilla cerosa, pájaros (mallas o bolsas individuales).",
      "cuidados": "Produce en 1–2 años. El higo fresco no dura: consumir rápido o deshidratar al sol. Algunas variedades dan dos cosechas al año."
    }
  },
  {
    id: 16,
    slug: "granado",
    dbKey: "Granado",
    nombre: "Granada",
    imagen: "/frutas/granado.webp",
    descripcion: "Flores rojas espectaculares. Tolerante a sequía y suelos salinos. La granada dura meses en el refrigerador.",
    clima: "Mediterráneo, calor seco",
    dificultad: "Fácil",
    grupo: "Otros",
    ficha: {
      "riego": "Constante y sin altibajos en maduración: sequía seguida de lluvia intensa = granadas rajadas.",
      "suelo": "Tolera gran variedad, incluso salino. pH 5.5–8.0.",
      "cosecha": "Marzo a mayo. Suena hueco al golpear con nudillo cuando está listo.",
      "plagas": "Rajado por riego irregular (principal problema), pulgón, barrenador del granado.",
      "cuidados": "Quitar hijuelos de la base cada invierno. Variedad Wonderful: la más plantada del mundo."
    }
  },
  {
    id: 17,
    slug: "caqui",
    dbKey: "Caqui",
    nombre: "Caqui",
    imagen: "/frutas/caqui.webp",
    descripcion: "Brota muy tarde (octubre). Hay dos tipos: Fuyu (se come duro) y Hachiya (se come completamente blando).",
    clima: "Templado a subtropical",
    dificultad: "Fácil",
    grupo: "Otros",
    ficha: {
      "riego": "Regular. El árbol brota muy tarde en primavera. Ramas frágiles: ralear frutos para evitar quiebres.",
      "suelo": "Profundo, drenado, fértil. pH 6.0–7.5.",
      "cosecha": "Marzo a junio. Fuyu: cosechar naranja firme (se come duro). Hachiya: esperar a que esté completamente blando.",
      "plagas": "Mosca de la fruta, cochinilla, antracnosis.",
      "cuidados": "Si come Hachiya verde: la boca se pega (astringente). Para acelerar la maduración poner con manzanas. Muy ornamental en otoño."
    }
  },
  {
    id: 18,
    slug: "vid",
    dbKey: "Vid",
    nombre: "Uva",
    imagen: "/frutas/vid.webp",
    descripcion: "Enredadera muy productiva. Necesita estructura (parrón o espaldera) y poda anual obligatoria.",
    clima: "Mediterráneo, veranos secos y calurosos",
    dificultad: "Moderado",
    grupo: "Otros",
    ficha: {
      "riego": "Por goteo, eficiente. Reducir en envero (cambio de color). Cortar riego 15–20 días antes de cosechar para concentrar azúcar.",
      "suelo": "Drenado, tolera pobre y pedregoso. pH 6.0–7.5. No le gusta suelo rico en nitrógeno.",
      "cosecha": "Febrero a abril según variedad. Azufre preventivo cada 15 días desde brotación es la clave.",
      "plagas": "Oidio (principal, azufre preventivo), mildiú, botrytis, chanchito blanco, filoxera en raíces.",
      "cuidados": "SIEMPRE plantar vid injertada sobre portainjerto (protege de filoxera). Poda invernal obligatoria cada año."
    }
  },
  {
    id: 19,
    slug: "arandano",
    dbKey: "Arandano",
    nombre: "Arándano",
    imagen: "/frutas/arandano.webp",
    descripcion: "Chile es el mayor exportador del hemisferio sur. Requiere suelo ácido obligatorio (pH 4.5–5.5).",
    clima: "Templado-frío",
    dificultad: "Moderado",
    grupo: "Baya",
    ficha: {
      "riego": "Frecuente pero poco volumen (raíces superficiales). Goteo ideal. NUNCA dejar secar.",
      "suelo": "ÁCIDO obligatorio: pH 4.5–5.5. Mezclar con turba/aserrín de pino. NUNCA usar cal, ceniza o guano de gallina.",
      "cosecha": "Noviembre a febrero según variedad. Cosechar 2–3 veces por semana.",
      "plagas": "Drosophila suzukii (mosca de alas manchadas, principal), botrytis, clorosis férrica si el pH sube de 5.5.",
      "cuidados": "Plantar 2+ variedades para mejor polinización. Mulch ácido permanente (aserrín de pino). Funciona muy bien en macetón con sustrato ácido."
    }
  },
  {
    id: 20,
    slug: "olivo",
    dbKey: "Olivo",
    nombre: "Aceituna",
    imagen: "/frutas/olivo.webp",
    descripcion: "Árbol milenario que vive 100+ años. Tolerante a casi todo. NUNCA plantar donde hubo tomate o papa.",
    clima: "Mediterráneo, veranos secos",
    dificultad: "Fácil",
    grupo: "Otros",
    ficha: {
      "riego": "Muy resistente a sequía. Riego moderado en crecimiento del fruto y llenado.",
      "suelo": "Tolera pobre, pedregoso y calcáreo. Drenaje OBLIGATORIO. pH 6.5–8.5.",
      "cosecha": "Abril–junio (verdes para mesa) o mayo–julio (negras para aceite). Cosechar con peine sobre malla.",
      "plagas": "Mosca del olivo (principal, trampas desde febrero), cochinilla, repilo (hongo foliar), Verticilium.",
      "cuidados": "NUNCA plantar donde hubo tomate, papa o pimiento (Verticilium mata al olivo). Boro foliar en floración es crítico para la cuaja."
    }
  },
  {
    id: 21,
    slug: "frutilla",
    dbKey: "Frutilla",
    nombre: "Frutilla",
    imagen: "/frutas/frutilla.webp",
    descripcion: "Fruto fácil, rápido y muy gratificante. Produce a los 2-3 meses de plantar. Ideal para macetas.",
    clima: "Templado, fresco; tolera calor con riego constante",
    dificultad: "Fácil",
    grupo: "Baya",
    ficha: {
      "riego": "Diario en verano (raíz superficial). Goteo al sustrato, nunca aspersión sobre el follaje.",
      "suelo": "Franco-arenoso, rico en materia orgánica, buen drenaje. pH 5.5–6.5.",
      "cosecha": "Oct–Ene según zona y fecha de plantación. Cosechar rojo uniforme cada 2–3 días.",
      "plagas": "Botrytis (moho gris), araña roja, babosas.",
      "cuidados": "Renueva las plantas cada 2–3 años. Usa mulch para mantener fruto limpio y evitar Botrytis."
    }
  },
  {
    id: 22,
    slug: "frambuesa",
    dbKey: "Frambuesa",
    nombre: "Frambuesa",
    imagen: "/frutas/frambuesa.webp",
    descripcion: "Arbusto frutal con altísimo rendimiento. Chile es el 2.º exportador mundial. Ideal para zonas con veranos frescos.",
    clima: "Templado-frío; veranos frescos son ideales",
    dificultad: "Moderado",
    grupo: "Baya",
    ficha: {
      "riego": "Constante en primavera-verano. Sensible a sequía y a encharcamiento por igual.",
      "suelo": "Franco, rico en materia orgánica, excelente drenaje. pH 5.5–6.5.",
      "cosecha": "Dic–Mar (y hasta abril en variedades remontantes). Cosechar cada 2 días.",
      "plagas": "Botrytis, roya, Drosophila suzukii (mosca del vinagre).",
      "cuidados": "Poda total en invierno en variedades remontantes. Necesita tutores o espalderas."
    }
  },
  {
    id: 23,
    slug: "mora",
    dbKey: "Mora",
    nombre: "Mora",
    imagen: "/frutas/mora.webp",
    descripcion: "El frutal más rústico de los berries. Vigoroso, tolerante y muy productivo desde el 2.º año.",
    clima: "Templado; muy adaptable desde zona central al sur",
    dificultad: "Fácil",
    grupo: "Baya",
    ficha: {
      "riego": "Moderado y constante en primavera-verano. Más tolerante a sequía que la frambuesa.",
      "suelo": "Franco-arcilloso, tolera suelos ordinarios. Drenaje correcto.",
      "cosecha": "Dic–Mar. Fruto se cosecha negro brillante, no negro opaco (ya pasó).",
      "plagas": "Botrytis, roya, Drosophila suzukii.",
      "cuidados": "Elige variedades sin espina (ej. Thornfree) para manejar sin guantes."
    }
  },
  {
    id: 24,
    slug: "kiwi",
    dbKey: "Kiwi",
    nombre: "Kiwi",
    imagen: "/frutas/kiwi.webp",
    descripcion: "Enredadera frutal de largo plazo (30+ años). Chile es el 3.º exportador mundial. Necesita polinizador macho.",
    clima: "Mediterráneo con veranos cálidos; 600–800 h frío",
    dificultad: "Moderado",
    grupo: "Otros",
    ficha: {
      "riego": "Frecuente en primavera-verano. Raíz superficial y carnosa: muy sensible a sequía.",
      "suelo": "Profundo, bien drenado, rico en materia orgánica. pH 6.0–6.5.",
      "cosecha": "Abril–mayo. Cosechar firme y madurar en casa (o en frío). NO en el árbol.",
      "plagas": "Psa (Pseudomonas syringae pv. actinidiae), Botrytis, ácaros.",
      "cuidados": "NECESITA planta macho (1 macho por cada 6–8 hembras). Poda severa en invierno obligatoria."
    }
  },
  {
    id: 25,
    slug: "avellano-europeo",
    dbKey: "Avellano Europeo",
    nombre: "Avellano",
    imagen: "/frutas/avellano-europeo.webp",
    descripcion: "Arbusto resistente que crece bien en Chile central y sur. Biobío y Araucanía concentran el 90% de la producción nacional.",
    clima: "Templado-frío; requiere 800–1200 h frío",
    dificultad: "Moderado",
    grupo: "Fruto seco",
    ficha: {
      "riego": "Moderado en primavera-verano. Tolera sequía moderada una vez establecido.",
      "suelo": "Bien drenado, tolera suelos de moderada fertilidad. pH 6.0–7.0.",
      "cosecha": "Mar–Abr. Los frutos caen solos al suelo cuando están listos.",
      "plagas": "Balanino (gorgojo), monilia, bacteriosis.",
      "cuidados": "Plantar 2+ variedades para polinización cruzada (polinización por viento)."
    }
  },
  {
    id: 26,
    slug: "nispero-japones",
    dbKey: "Níspero Japonés",
    nombre: "Níspero",
    imagen: "/frutas/nispero-japones.webp",
    descripcion: "El primer fruto del año: listo en agosto-octubre. Árbol ornamental de hoja perenne, tolera costa y calor.",
    clima: "Mediterráneo o semiárido; sensible a heladas invernales en flor",
    dificultad: "Fácil",
    grupo: "Subtropical",
    ficha: {
      "riego": "Moderado. Tolera sequía una vez establecido. Riego en verano para el llenado del fruto.",
      "suelo": "Tolera casi cualquier suelo con drenaje correcto. pH 6.0–7.5.",
      "cosecha": "Sep–Oct según zona. Cosechar dorado-anaranjado, no verde.",
      "plagas": "Fuego bacteriano, cochinilla, oídio.",
      "cuidados": "Floración invernal (jul-ago): el enemigo es la helada. Elegir ubicación protegida."
    }
  },
  {
    id: 27,
    slug: "chirimoya",
    dbKey: "Chirimoya",
    nombre: "Chirimoya",
    imagen: "/frutas/chirimoya.webp",
    descripcion: "Frutal tropical-subtropical nativo de los Andes. Chile es el mayor productor mundial. Solo viable en el norte-centro costero.",
    clima: "Semiárido-mediterráneo costero; sin heladas",
    dificultad: "Avanzado",
    grupo: "Subtropical",
    ficha: {
      "riego": "Constante en primavera-verano. Sensible a sequía en floración y cuaja.",
      "suelo": "Franco, bien drenado, profundo. pH 6.0–7.0.",
      "cosecha": "Abr–Jun. Cosechar verde-grisácea y dejar ablandar en casa (2–4 días).",
      "plagas": "Cochinilla harinosa, trips, Anomis illita (gusano del fruto).",
      "cuidados": "Requiere polinización manual (pincel) para maximizar cuaja: hacerlo en la mañana."
    }
  },
  {
    id: 28,
    slug: "lucuma",
    dbKey: "Lúcuma",
    nombre: "Lúcuma",
    imagen: "/frutas/lucuma.webp",
    descripcion: "Frutal andino de pulpa única, sabor a caramelo. Solo viable en la franja costera norte-centro sin heladas.",
    clima: "Semiárido costero; muy sensible al frío (-2°C la mata)",
    dificultad: "Moderado",
    grupo: "Subtropical",
    ficha: {
      "riego": "Constante pero sin encharcamiento. Muy sensible a asfixia radicular.",
      "suelo": "Franco, profundo, buen drenaje. pH 6.0–7.0.",
      "cosecha": "Feb–May. Cosechar cuando la piel cambia de verde a verde-amarillo.",
      "plagas": "Cochinilla, mosca de la fruta, Verticilium.",
      "cuidados": "NO tolera heladas: plantar en exposición norte protegida del frío."
    }
  },
  {
    id: 29,
    slug: "papayo-chileno",
    dbKey: "Papayo Chileno",
    nombre: "Papayo chileno",
    imagen: "/frutas/papayo-chileno.webp",
    descripcion: "Frutal nativo chileno de crecimiento muy rápido. Produce todo el año en zonas sin heladas. Único del mundo.",
    clima: "Mediterráneo costero sin heladas; muy sensible al frío",
    dificultad: "Moderado",
    grupo: "Subtropical",
    ficha: {
      "riego": "Constante pero con drenaje perfecto. La raíz NO tolera encharcamiento ni siquiera breve.",
      "suelo": "Suelto, bien drenado, fértil. pH 6.0–7.0.",
      "cosecha": "Todo el año en zonas sin heladas. Cosechar verde-amarillo y madurar en casa.",
      "plagas": "Virus de la mancha anular (fatal), mosca de la fruta.",
      "cuidados": "Evitar comprar plantas enfermas (virus incurable). Producción en 8–12 meses desde semilla."
    }
  },
  {
    id: 30,
    slug: "palto",
    dbKey: "Palto",
    nombre: "Palta",
    imagen: "/frutas/palto.webp",
    descripcion: "El frutal de mayor crecimiento en Chile. Quillota es el epicentro nacional. Sensible a heladas y raíz con poca tolerancia al encharcamiento.",
    clima: "Mediterráneo costero sin heladas fuertes",
    dificultad: "Avanzado",
    grupo: "Subtropical",
    ficha: {
      "riego": "Constante y ajustado. Raíz muy sensible a encharcamiento (Phytophthora). Goteo obligatorio.",
      "suelo": "Franco, profundo, EXCELENTE drenaje. pH 6.0–7.0. NO arcillas pesadas.",
      "cosecha": "Oct–Feb según variedad (Hass: oct-ene; Fuerte: nov-feb). Cosechar firme y madurar en casa.",
      "plagas": "Phytophthora (raíz), trips, chanchito blanco, Verticilium.",
      "cuidados": "Hass necesita polinizador (Fuerte o Edranol). La raíz muere a las 48 h de encharcamiento."
    }
  }
];

