// Autogenerated from legacy app (datos.js / db_detalle.js). Do not edit manually.

export interface FenologiaEntrada {
  brotacion: string;
  floracion: string;
  cuaja: string;
  cos_ini: string;
  cos_fin: string;
  notas: string;
}

export const FENOLOGIA: Record<string, Record<string, FenologiaEntrada | null>> = {
  "Duraznero": {
    "Norte": {"brotacion":"Jul-Ago","floracion":"Ago","cuaja":"Ago-Sep","cos_ini":"Nov","cos_fin":"Ene","notas":"Variedades bajo frío. Riego obligatorio."},
    "Valparaíso-Aconcagua": {"brotacion":"Ago","floracion":"Ago-Sep","cuaja":"Sep","cos_ini":"Dic","cos_fin":"Feb","notas":"Interior y costa. Quillota viable."},
    "Santiago-RM": {"brotacion":"Ago-Sep","floracion":"Sep","cuaja":"Sep-Oct","cos_ini":"Dic","cos_fin":"Feb","notas":"Rich Lady dic, O'Henry feb."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Sep","cuaja":"Oct","cos_ini":"Dic","cos_fin":"Mar","notas":"Excelente zona. 9.184 ha O'Higgins."},
    "Transición": {"brotacion":"Sep","floracion":"Sep-Oct","cuaja":"Oct","cos_ini":"Ene","cos_fin":"Mar","notas":"Marginal en Ñuble. Alta presión hongos."},
    "Sur": null
  },
  "Cerezo": {
    "Norte": null,
    "Valparaíso-Aconcagua": {"brotacion":"Ago","floracion":"Sep","cuaja":"Sep-Oct","cos_ini":"Nov","cos_fin":"Dic","notas":"Solo interior alto (San Felipe, Los Andes)."},
    "Santiago-RM": {"brotacion":"Ago-Sep","floracion":"Sep","cuaja":"Oct","cos_ini":"Nov","cos_fin":"Dic","notas":"Santina: 2da quin. nov. Lapins: 1ra-2da sem. dic."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Sep","cuaja":"Oct","cos_ini":"Nov","cos_fin":"Ene","notas":"8.249 ha O'Higgins. Santina: última sem. nov. Regina: 3ra sem. dic."},
    "Transición": {"brotacion":"Sep","floracion":"Sep-Oct","cuaja":"Oct-Nov","cos_ini":"Dic","cos_fin":"Ene","notas":"Ñuble 2.973 ha. Lapins: 3ra-4ta sem. dic."},
    "Sur": {"brotacion":"Sep-Oct","floracion":"Oct","cuaja":"Nov","cos_ini":"Ene","cos_fin":"Feb","notas":"Cosecha ene-feb. Mallas antipájaros obligatorias. Kordia."}
  },
  "Arandano": {
    "Norte": null,
    "Valparaíso-Aconcagua": {"brotacion":"Ago-Sep","floracion":"Sep-Oct","cuaja":"Oct","cos_ini":"Oct","cos_fin":"Dic","notas":"O'Neal fines oct. Suelo ácido obligatorio."},
    "Santiago-RM": {"brotacion":"Sep","floracion":"Oct","cuaja":"Oct-Nov","cos_ini":"Nov","cos_fin":"Ene","notas":"Nov-Ene. pH 4.5-5.5 obligatorio."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Nov","cos_fin":"Feb","notas":"Maule concentra 32.6% superficie nacional."},
    "Transición": {"brotacion":"Sep-Oct","floracion":"Oct","cuaja":"Nov","cos_ini":"Dic","cos_fin":"Mar","notas":"Ñuble 4.142 ha. DIC-FEB máximo. Ojo: NO en mayo."},
    "Sur": {"brotacion":"Oct","floracion":"Oct-Nov","cuaja":"Nov-Dic","cos_ini":"Ene","cos_fin":"Mar","notas":"Araucanía 11.7% sup. nacional. Ene-mar."}
  },
  "Ciruelo": {
    "Norte": {"brotacion":"Ago","floracion":"Ago-Sep","cuaja":"Sep","cos_ini":"Nov","cos_fin":"Ene","notas":"Variedades bajo frío posibles. Riego obligatorio."},
    "Valparaíso-Aconcagua": {"brotacion":"Ago-Sep","floracion":"Sep","cuaja":"Sep-Oct","cos_ini":"Dic","cos_fin":"Feb","notas":"Interior viable. Santa Rosa, Angeleno."},
    "Santiago-RM": {"brotacion":"Sep","floracion":"Sep","cuaja":"Oct","cos_ini":"Dic","cos_fin":"Mar","notas":"Angeleno: fines ene. D'Agen (deshidratado): feb-mar."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Sep-Oct","cuaja":"Oct","cos_ini":"Ene","cos_fin":"Mar","notas":"Excelente zona para ciruelo japonés y europeo."},
    "Transición": {"brotacion":"Sep-Oct","floracion":"Oct","cuaja":"Oct-Nov","cos_ini":"Feb","cos_fin":"Mar","notas":"Ciruelo europeo (D'Agen) mejor que japonés en Ñuble."},
    "Sur": null
  },
  "Damasco": {
    "Norte": {"brotacion":"Jul","floracion":"Jul-Ago","cuaja":"Ago","cos_ini":"Oct","cos_fin":"Nov","notas":"Muy temprano, poco riesgo helada. RIESGO por horas frío."},
    "Valparaíso-Aconcagua": {"brotacion":"Jul-Ago","floracion":"Ago","cuaja":"Ago-Sep","cos_ini":"Nov","cos_fin":"Dic","notas":"Valparaíso concentra 33.2% sup. nacional (ODEPA 2026)."},
    "Santiago-RM": {"brotacion":"Ago","floracion":"Ago-Sep","cuaja":"Sep","cos_ini":"Nov","cos_fin":"Dic","notas":"Florece MUY temprano: riesgo helada tardía. Tilton es tolerante."},
    "Centro-Sur": {"brotacion":"Ago","floracion":"Ago-Sep","cuaja":"Sep-Oct","cos_ini":"Dic","cos_fin":"Ene","notas":"Buena zona. Tilton y Moorpark."},
    "Transición": {"brotacion":"Ago-Sep","floracion":"Sep","cuaja":"Oct","cos_ini":"Dic","cos_fin":"Ene","notas":"RIESGO ALTO: heladas en floración (ago-sep) frecuentes."},
    "Sur": null
  },
  "Nectarino": {
    "Norte": {"brotacion":"Jul-Ago","floracion":"Ago","cuaja":"Sep","cos_ini":"Nov","cos_fin":"Ene","notas":"Variedades bajo frío. Riego obligatorio."},
    "Valparaíso-Aconcagua": {"brotacion":"Ago","floracion":"Ago-Sep","cuaja":"Sep","cos_ini":"Dic","cos_fin":"Feb","notas":"Interior viable. Fantasia, Independence."},
    "Santiago-RM": {"brotacion":"Ago-Sep","floracion":"Sep","cuaja":"Sep-Oct","cos_ini":"Dic","cos_fin":"Feb","notas":"Manejo idéntico al duraznero (Bol. INIA 373)."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Sep","cuaja":"Oct","cos_ini":"Dic","cos_fin":"Mar","notas":"O'Higgins concentra producción. Big Top: feb."},
    "Transición": {"brotacion":"Sep","floracion":"Sep-Oct","cuaja":"Oct","cos_ini":"Ene","cos_fin":"Mar","notas":"Marginal. Pocas plantaciones. Alta presión hongos."},
    "Sur": null
  },
  "Manzano": {
    "Norte": {"brotacion":"Ago","floracion":"Sep","cuaja":"Sep-Oct","cos_ini":"Ene","cos_fin":"Mar","notas":"Solo variedades bajo frío. Riego obligatorio."},
    "Valparaíso-Aconcagua": {"brotacion":"Sep","floracion":"Sep-Oct","cuaja":"Oct","cos_ini":"Feb","cos_fin":"Abr","notas":"Casablanca 102 ha (CIREN). Polinizador obligatorio."},
    "Santiago-RM": {"brotacion":"Sep","floracion":"Oct","cuaja":"Oct-Nov","cos_ini":"Feb","cos_fin":"May","notas":"Gala: feb-mar. Fuji y Granny Smith: abr-may."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Oct","cuaja":"Oct-Nov","cos_ini":"Feb","cos_fin":"May","notas":"Curicó-Romeral es la gran zona manzanera de Chile."},
    "Transición": {"brotacion":"Sep-Oct","floracion":"Oct","cuaja":"Nov","cos_ini":"Mar","cos_fin":"May","notas":"Buena zona. Cosecha 2-3 semanas más tarde."},
    "Sur": {"brotacion":"Oct","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Mar","cos_fin":"Jun","notas":"Posible con variedades rústicas. Araucanía viable."}
  },
  "Peral": {
    "Norte": {"brotacion":"Ago","floracion":"Sep","cuaja":"Oct","cos_ini":"Ene","cos_fin":"Mar","notas":"Limitado por horas frío. Polinizador obligatorio."},
    "Valparaíso-Aconcagua": {"brotacion":"Sep","floracion":"Sep-Oct","cuaja":"Oct","cos_ini":"Feb","cos_fin":"Abr","notas":"Interior posible. Packham's, Williams."},
    "Santiago-RM": {"brotacion":"Sep","floracion":"Oct","cuaja":"Oct-Nov","cos_ini":"Feb","cos_fin":"Abr","notas":"Packham's y Williams. Cosechar VERDE FIRME."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Oct","cuaja":"Oct-Nov","cos_ini":"Feb","cos_fin":"May","notas":"Buena zona. Cosecha firme: madura en casa."},
    "Transición": {"brotacion":"Sep-Oct","floracion":"Oct","cuaja":"Nov","cos_ini":"Mar","cos_fin":"May","notas":"Posible. Tardía. Riesgo fuego bacteriano en lluvias."},
    "Sur": {"brotacion":"Oct","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Mar","cos_fin":"Jun","notas":"Marginal. Variedades rústicas. RIESGO alta lluvia."}
  },
  "Membrillo": {
    "Norte": {"brotacion":"Ago-Sep","floracion":"Sep-Oct","cuaja":"Oct","cos_ini":"Mar","cos_fin":"May","notas":"Poco exigente. Autofértil. Viable con riego."},
    "Valparaíso-Aconcagua": {"brotacion":"Sep","floracion":"Oct","cuaja":"Oct-Nov","cos_ini":"Abr","cos_fin":"Jun","notas":"Fácil. Tolera sequía. Cosecha de otoño."},
    "Santiago-RM": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Abr","cos_fin":"Jun","notas":"Muy fácil. Aroma perfuma la casa. Autofértil."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Abr","cos_fin":"Jun","notas":"Excelente zona. Ideal para dulce de membrillo."},
    "Transición": {"brotacion":"Sep-Oct","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"May","cos_fin":"Jun","notas":"Viable. Muy resistente a heladas y lluvia."},
    "Sur": {"brotacion":"Oct","floracion":"Nov","cuaja":"Nov-Dic","cos_ini":"May","cos_fin":"Jul","notas":"Viable. Tolera lluvias y frío. Muy tolerante."}
  },
  "Limonero": {
    "Norte": {"brotacion":"Todo año","floracion":"Sep-Nov","cuaja":"Nov-Dic","cos_ini":"Mar","cos_fin":"Sep","notas":"Excelente. Produce casi todo el año. Riego obligatorio."},
    "Valparaíso-Aconcagua": {"brotacion":"Todo año","floracion":"Sep-Nov","cuaja":"Nov-Dic","cos_ini":"Abr","cos_fin":"Sep","notas":"Quillota zona cítrica principal. 316 ha (CIREN)."},
    "Santiago-RM": {"brotacion":"Todo año","floracion":"Sep-Nov","cuaja":"Nov-Dic","cos_ini":"Abr","cos_fin":"Sep","notas":"Microclimas protegidos. Meyer: tolera -4°C."},
    "Centro-Sur": {"brotacion":"Todo año","floracion":"Oct-Nov","cuaja":"Nov-Dic","cos_ini":"May","cos_fin":"Sep","notas":"Solo Lago Rapel y microclimas protegidos."},
    "Transición": null,
    "Sur": null
  },
  "Naranjo": {
    "Norte": {"brotacion":"Todo año","floracion":"Sep-Oct","cuaja":"Oct-Nov","cos_ini":"May","cos_fin":"Oct","notas":"Excelente. Azahar perfuma todo. W. Navel: may-jul."},
    "Valparaíso-Aconcagua": {"brotacion":"Todo año","floracion":"Sep-Oct","cuaja":"Oct-Nov","cos_ini":"May","cos_fin":"Sep","notas":"Quillota 258 ha (CIREN). W. Navel y Valencia."},
    "Santiago-RM": {"brotacion":"Todo año","floracion":"Sep-Oct","cuaja":"Oct-Nov","cos_ini":"Jun","cos_fin":"Oct","notas":"Microclimas protegidos. Más sensible al frío que limonero."},
    "Centro-Sur": {"brotacion":"Todo año","floracion":"Oct","cuaja":"Nov","cos_ini":"Jun","cos_fin":"Oct","notas":"Solo Lago Rapel y microclimas. Muy limitado."},
    "Transición": null,
    "Sur": null
  },
  "Mandarino": {
    "Norte": {"brotacion":"Todo año","floracion":"Sep-Oct","cuaja":"Oct-Nov","cos_ini":"Abr","cos_fin":"Ago","notas":"Excelente. Más tolerante al frío que naranjo (-4°C)."},
    "Valparaíso-Aconcagua": {"brotacion":"Todo año","floracion":"Sep-Oct","cuaja":"Oct-Nov","cos_ini":"May","cos_fin":"Sep","notas":"Quillota 64 ha. Clemenules: sin semillas, fácil pelar."},
    "Santiago-RM": {"brotacion":"Todo año","floracion":"Sep-Oct","cuaja":"Oct-Nov","cos_ini":"May","cos_fin":"Sep","notas":"Más resistente al frío que naranjo. Árbol compacto."},
    "Centro-Sur": {"brotacion":"Todo año","floracion":"Oct","cuaja":"Nov","cos_ini":"Jun","cos_fin":"Sep","notas":"Solo microclimas muy protegidos."},
    "Transición": null,
    "Sur": null
  },
  "Pomelo": {
    "Norte": {"brotacion":"Todo año","floracion":"Sep-Oct","cuaja":"Oct-Nov","cos_ini":"Jun","cos_fin":"Oct","notas":"Viable con riego. Mejor sabor con frío invernal."},
    "Valparaíso-Aconcagua": {"brotacion":"Todo año","floracion":"Sep-Oct","cuaja":"Oct-Nov","cos_ini":"Jun","cos_fin":"Oct","notas":"Quillota 35 ha. Star Ruby y Marsh. Espacio: 6-10 m."},
    "Santiago-RM": {"brotacion":"Todo año","floracion":"Oct","cuaja":"Nov","cos_ini":"Jul","cos_fin":"Oct","notas":"Marginal. Solo microclimas muy protegidos. RIESGO."},
    "Centro-Sur": null,
    "Transición": null,
    "Sur": null
  },
  "Nogal": {
    "Norte": {"brotacion":"Ago-Sep","floracion":"Sep","cuaja":"Oct","cos_ini":"Mar","cos_fin":"Abr","notas":"Coquimbo viable: Illapel y Salamanca (Bol. INIA 454)."},
    "Valparaíso-Aconcagua": {"brotacion":"Sep","floracion":"Sep-Oct","cuaja":"Oct","cos_ini":"Mar","cos_fin":"Abr","notas":"Valparaíso 6.306 ha (ODEPA). Chandler es la variedad líder."},
    "Santiago-RM": {"brotacion":"Sep","floracion":"Sep-Oct","cuaja":"Oct","cos_ini":"Mar","cos_fin":"Abr","notas":"RM concentra 15.521 ha, mayor sup. nacional (ODEPA)."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Oct","cuaja":"Oct-Nov","cos_ini":"Mar","cos_fin":"May","notas":"O'Higgins 7.785 ha, Maule 8.928 ha. ViLab: cosecha abr."},
    "Transición": {"brotacion":"Sep-Oct","floracion":"Oct","cuaja":"Nov","cos_ini":"Abr","cos_fin":"May","notas":"Ñuble-Biobío 12.800 ha (Chilenut 2025). Riesgo peste negra."},
    "Sur": {"brotacion":"Oct","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Abr","cos_fin":"May","notas":"Araucanía: zona emergente. Muy tardío. Riesgo bacteriosis."}
  },
  "Almendro": {
    "Norte": {"brotacion":"Jul","floracion":"Jul-Ago","cuaja":"Ago-Sep","cos_ini":"Ene","cos_fin":"Mar","notas":"Floración muy temprana. Riego obligatorio."},
    "Valparaíso-Aconcagua": {"brotacion":"Jul-Ago","floracion":"Ago","cuaja":"Sep","cos_ini":"Feb","cos_fin":"Mar","notas":"Interior viable. Guara: autofértil, flor tardía."},
    "Santiago-RM": {"brotacion":"Ago","floracion":"Ago","cuaja":"Sep","cos_ini":"Feb","cos_fin":"Mar","notas":"Florece MUY temprano. RIESGO helada tardía. Guara o Tuono."},
    "Centro-Sur": {"brotacion":"Ago","floracion":"Ago-Sep","cuaja":"Sep-Oct","cos_ini":"Feb","cos_fin":"Abr","notas":"Excelente zona. Guara: autofértil, la más plantada en Chile."},
    "Transición": {"brotacion":"Ago-Sep","floracion":"Sep","cuaja":"Oct","cos_ini":"Mar","cos_fin":"Abr","notas":"RIESGO ALTO: heladas en floración (sep) frecuentes en Ñuble."},
    "Sur": null
  },
  "Higuera": {
    "Norte": {"brotacion":"Ago","floracion":"Sep-Oct","cuaja":"Oct","cos_ini":"Dic","cos_fin":"Mar","notas":"Hasta 2 cosechas posibles. Calor seco ideal."},
    "Valparaíso-Aconcagua": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Dic","cos_fin":"Mar","notas":"Brevas dic-ene (1ra cosecha), higos feb-mar (2da)."},
    "Santiago-RM": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Dic","cos_fin":"Mar","notas":"Brevas + higos. Dos cosechas. Usar guantes con látex."},
    "Centro-Sur": {"brotacion":"Sep-Oct","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Ene","cos_fin":"Mar","notas":"1-2 cosechas según variedad. Brown Turkey, Kadota."},
    "Transición": {"brotacion":"Oct","floracion":"Nov","cuaja":"Nov-Dic","cos_ini":"Feb","cos_fin":"Mar","notas":"Solo 1 cosecha (higos). Sin higos brevas en esta zona."},
    "Sur": {"brotacion":"Oct","floracion":"Nov","cuaja":"Dic","cos_ini":"Feb","cos_fin":"Mar","notas":"Marginal. Falta calor para madurar bien. RIESGO."}
  },
  "Granado": {
    "Norte": {"brotacion":"Ago-Sep","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Feb","cos_fin":"Abr","notas":"Excelente. Calor seco ideal. Wonderful: la mejor variedad."},
    "Valparaíso-Aconcagua": {"brotacion":"Sep","floracion":"Nov","cuaja":"Nov-Dic","cos_ini":"Mar","cos_fin":"May","notas":"Viable. Riego constante para evitar rajado."},
    "Santiago-RM": {"brotacion":"Sep-Oct","floracion":"Nov-Dic","cuaja":"Dic","cos_ini":"Mar","cos_fin":"May","notas":"Viable. Lago Rapel excelente. Riego PAREJO."},
    "Centro-Sur": {"brotacion":"Oct","floracion":"Nov-Dic","cuaja":"Dic","cos_ini":"Abr","cos_fin":"May","notas":"Posible. Menos calor = maduración más lenta."},
    "Transición": {"brotacion":"Oct","floracion":"Dic","cuaja":"Dic-Ene","cos_ini":"Abr","cos_fin":"Jun","notas":"Marginal. Falta calor. RIESGO rajado por lluvia."},
    "Sur": null
  },
  "Caqui": {
    "Norte": {"brotacion":"Sep","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Mar","cos_fin":"May","notas":"Viable con riego. Fuyu y Hachiya."},
    "Valparaíso-Aconcagua": {"brotacion":"Sep-Oct","floracion":"Nov","cuaja":"Nov-Dic","cos_ini":"Abr","cos_fin":"Jun","notas":"Quillota: caqui registrado (CIREN). Fuyu: abr-may."},
    "Santiago-RM": {"brotacion":"Oct","floracion":"Nov","cuaja":"Dic","cos_ini":"Abr","cos_fin":"Jun","notas":"Brota MUY TARDE (oct): normal. Cosecha otoño-invierno."},
    "Centro-Sur": {"brotacion":"Oct","floracion":"Nov-Dic","cuaja":"Dic","cos_ini":"May","cos_fin":"Jun","notas":"Viable. Fuyu: comer duro. Hachiya: esperar blando total."},
    "Transición": {"brotacion":"Oct","floracion":"Nov-Dic","cuaja":"Dic","cos_ini":"May","cos_fin":"Jul","notas":"Posible. Tolera frío en reposo (-15°C)."},
    "Sur": {"brotacion":"Oct-Nov","floracion":"Dic","cuaja":"Dic-Ene","cos_ini":"Jun","cos_fin":"Jul","notas":"Marginal pero posible. Tolera frío extremo en reposo."}
  },
  "Vid": {
    "Norte": {"brotacion":"Ago","floracion":"Oct","cuaja":"Oct-Nov","cos_ini":"Dic","cos_fin":"Feb","notas":"Uva mesa temprana. Valle Copiapó y Limarí. Bol. INIA 383."},
    "Valparaíso-Aconcagua": {"brotacion":"Sep","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Ene","cos_fin":"Mar","notas":"San Felipe: uva mesa. Casablanca: vinífera fría."},
    "Santiago-RM": {"brotacion":"Sep","floracion":"Nov","cuaja":"Nov-Dic","cos_ini":"Feb","cos_fin":"Abr","notas":"Isla de Maipo, Pirque: vinífera. Ñuble: vid tradicional."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Nov","cuaja":"Nov-Dic","cos_ini":"Feb","cos_fin":"Abr","notas":"Santa Cruz, Cauquenes: vinífera. Curicó: uva mesa."},
    "Transición": {"brotacion":"Sep-Oct","floracion":"Nov","cuaja":"Dic","cos_ini":"Mar","cos_fin":"Abr","notas":"Itata: vid tradicional (País, Moscatel). Bol. INIA 383."},
    "Sur": null
  },
  "Olivo": {
    "Norte": {"brotacion":"Sep","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Mar","cos_fin":"Jun","notas":"Excelente. Copiapó, Huasco, Ovalle. ODEPA 2026."},
    "Valparaíso-Aconcagua": {"brotacion":"Sep","floracion":"Nov","cuaja":"Nov-Dic","cos_ini":"Abr","cos_fin":"Jun","notas":"Hijuelas, Casablanca. Arbequina ideal para aceite."},
    "Santiago-RM": {"brotacion":"Sep-Oct","floracion":"Nov","cuaja":"Dic","cos_ini":"Abr","cos_fin":"Jul","notas":"RM 4.951 ha (ODEPA 2026). Melipilla, San Pedro, Til Til."},
    "Centro-Sur": {"brotacion":"Oct","floracion":"Nov","cuaja":"Dic","cos_ini":"May","cos_fin":"Jul","notas":"San Javier, Cauquenes, Marchigüe. Aceite may-jul."},
    "Transición": {"brotacion":"Oct","floracion":"Nov-Dic","cuaja":"Dic","cos_ini":"May","cos_fin":"Jul","notas":"Marginal. Exceso lluvia aumenta riesgo repilo."},
    "Sur": null
  },
  "Frutilla": {
    "Norte": null,
    "Valparaíso-Aconcagua": {"brotacion":"Mar/Ago","floracion":"Sep","cuaja":"Oct","cos_ini":"Nov","cos_fin":"Ene","notas":"Zona muy favorable, clima mediterráneo costero."},
    "Santiago-RM": {"brotacion":"Mar/Ago","floracion":"Sep","cuaja":"Oct","cos_ini":"Nov","cos_fin":"Ene","notas":"Excelente producción en RM."},
    "Centro-Sur": {"brotacion":"Mar/Ago","floracion":"Sep-Oct","cuaja":"Oct-Nov","cos_ini":"Nov","cos_fin":"Feb","notas":"Zona clásica productora (O'Higgins-Maule)."},
    "Transición": {"brotacion":"Mar/Ago","floracion":"Oct","cuaja":"Nov","cos_ini":"Dic","cos_fin":"Feb","notas":"Buena adaptación en Ñuble-Biobío."},
    "Sur": {"brotacion":"Sep","floracion":"Nov","cuaja":"Dic","cos_ini":"Ene","cos_fin":"Mar","notas":"Viable con protección. Base histórica de 'Frutillar'."}
  },
  "Frambuesa": {
    "Norte": null,
    "Valparaíso-Aconcagua": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Dic","cos_fin":"Feb","notas":"Viable en sectores de interior más frescos."},
    "Santiago-RM": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Dic","cos_fin":"Mar","notas":"Buena producción en RM con riego adecuado."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Dic","cos_fin":"Mar","notas":"Zona productora clásica (Maule-Biobío)."},
    "Transición": {"brotacion":"Sep","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Ene","cos_fin":"Abr","notas":"Excelente clima: veranos frescos ideales."},
    "Sur": {"brotacion":"Sep-Oct","floracion":"Nov","cuaja":"Dic","cos_ini":"Ene","cos_fin":"Abr","notas":"Muy buena adaptación en el sur de Chile."}
  },
  "Mora": {
    "Norte": null,
    "Valparaíso-Aconcagua": null,
    "Santiago-RM": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Dic","cos_fin":"Mar","notas":"Buena producción en RM."},
    "Centro-Sur": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Dic","cos_fin":"Mar","notas":"Zona muy favorable (Maule-Biobío)."},
    "Transición": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Dic","cos_fin":"Mar","notas":"Excelente adaptación en Ñuble-Biobío."},
    "Sur": {"brotacion":"Sep-Oct","floracion":"Nov","cuaja":"Dic","cos_ini":"Ene","cos_fin":"Abr","notas":"Muy buena adaptación en el sur."}
  },
  "Kiwi": {
    "Norte": null,
    "Valparaíso-Aconcagua": {"brotacion":"Sep","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Abr","cos_fin":"May","notas":"RIESGO: viable solo en sectores de interior frescos."},
    "Santiago-RM": {"brotacion":"Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Abr","cos_fin":"May","notas":"RIESGO en RM; mejor en sectores no muy calurosos."},
    "Centro-Sur": {"brotacion":"Ago-Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Abr","cos_fin":"May","notas":"Zona muy favorable: Maule y Biobío, polo productivo nacional."},
    "Transición": {"brotacion":"Ago-Sep","floracion":"Oct","cuaja":"Nov","cos_ini":"Abr","cos_fin":"May","notas":"Excelente adaptación en Ñuble-Biobío."},
    "Sur": {"brotacion":"Sep","floracion":"Oct-Nov","cuaja":"Nov","cos_ini":"Abr","cos_fin":"Jun","notas":"RIESGO: exceso de humedad favorece Psa y Botrytis."}
  },
  "Avellano Europeo": {
    "Norte": null,
    "Valparaíso-Aconcagua": null,
    "Santiago-RM": {"brotacion":"Ago-Sep","floracion":"Jun-Jul","cuaja":"Oct","cos_ini":"Mar","cos_fin":"Abr","notas":"Viable en RM, mejor en sectores frescos."},
    "Centro-Sur": {"brotacion":"Ago-Sep","floracion":"Jun-Jul","cuaja":"Oct","cos_ini":"Mar","cos_fin":"Abr","notas":"Buena adaptación en Maule-Biobío."},
    "Transición": {"brotacion":"Ago-Sep","floracion":"Jun-Jul","cuaja":"Oct-Nov","cos_ini":"Mar","cos_fin":"Abr","notas":"Polo productivo nacional: Biobío-Araucanía."},
    "Sur": null
  },
  "Níspero Japonés": {
    "Norte": {"brotacion":"May-Jun","floracion":"Jul-Ago","cuaja":"Sep","cos_ini":"Sep","cos_fin":"Oct","notas":"Muy buena adaptación en clima desértico-semiárido con riego."},
    "Valparaíso-Aconcagua": {"brotacion":"May-Jun","floracion":"Jul-Ago","cuaja":"Ago-Sep","cos_ini":"Sep","cos_fin":"Oct","notas":"Zona muy favorable, clima mediterráneo costero."},
    "Santiago-RM": {"brotacion":"May-Jun","floracion":"Jul-Ago","cuaja":"Ago-Sep","cos_ini":"Sep","cos_fin":"Nov","notas":"Buena adaptación en RM."},
    "Centro-Sur": {"brotacion":"Jun","floracion":"Ago","cuaja":"Sep","cos_ini":"Oct","cos_fin":"Nov","notas":"Viable, algo más tardío que en el norte-centro."},
    "Transición": null,
    "Sur": null
  },
  "Chirimoya": {
    "Norte": null,
    "Valparaíso-Aconcagua": {"brotacion":"Sep-Oct","floracion":"Oct-Nov","cuaja":"Dic-Ene","cos_ini":"Abr","cos_fin":"Jun","notas":"Zona muy favorable: polo productivo La Serena-Quillota."},
    "Santiago-RM": null,
    "Centro-Sur": null,
    "Transición": null,
    "Sur": null
  },
  "Lúcuma": {
    "Norte": null,
    "Valparaíso-Aconcagua": {"brotacion":"Sep-Oct","floracion":"Nov","cuaja":"Dic-Ene","cos_ini":"Feb","cos_fin":"May","notas":"Zona favorable: franja costera Coquimbo-Valparaíso."},
    "Santiago-RM": null,
    "Centro-Sur": null,
    "Transición": null,
    "Sur": null
  },
  "Papayo Chileno": {
    "Norte": null,
    "Valparaíso-Aconcagua": {"brotacion":"Sep-Oct","floracion":"Dic","cuaja":"Ene-Feb","cos_ini":"Todo año","cos_fin":"Todo año","notas":"94% de la superficie nacional entre Coquimbo-Valparaíso."},
    "Santiago-RM": null,
    "Centro-Sur": null,
    "Transición": null,
    "Sur": null
  },
  "Palto": {
    "Norte": null,
    "Valparaíso-Aconcagua": {"brotacion":"Ago","floracion":"Sep","cuaja":"Oct-Nov","cos_ini":"Oct","cos_fin":"Feb","notas":"Zona muy favorable: epicentro nacional (Quillota-La Cruz-Petorca)."},
    "Santiago-RM": null,
    "Centro-Sur": null,
    "Transición": null,
    "Sur": null
  }
};

export const MACROZONA_MAP: Record<number, string> = {
  "1": "Norte",
  "2": "Norte",
  "3": "Norte",
  "4": "Norte",
  "5": "Valparaíso-Aconcagua",
  "6": "Valparaíso-Aconcagua",
  "7": "Santiago-RM",
  "8": "Santiago-RM",
  "9": "Santiago-RM",
  "10": "Centro-Sur",
  "11": "Centro-Sur",
  "12": "Centro-Sur",
  "13": "Centro-Sur",
  "14": "Centro-Sur",
  "15": "Transición",
  "16": "Transición",
  "17": "Transición",
  "18": "Sur",
  "19": "Sur",
  "20": "Sur"
};

