// Autogenerated from legacy app (datos.js / db_detalle.js). Do not edit manually.
export interface ZonaClimatica {
  id: number;
  nombre: string;
  region: string;
  clima: string;
  txMax: number;
  tnMin: number;
  pp: number;
  hf: string;
  heladas: string;
  sequia: string;
}


export interface ZonaClimatica {
  id: number;
  nombre: string;
  region: string;
  clima: string;
  txMax: number;
  tnMin: number;
  pp: number;
  hf: string;
  heladas: string;
  sequia: string;
}

export const ZONAS: Record<number, ZonaClimatica> = {
  1: {
    "id": 1,
    "nombre": "Arica - Azapa",
    "region": "Arica y Parinacota",
    "clima": "Desértico costero",
    "txMax": 27,
    "tnMin": 12,
    "pp": 1,
    "hf": "0–50",
    "heladas": "Sin heladas",
    "sequia": "Extremo"
  },
  2: {
    "id": 2,
    "nombre": "Copiapó Valle",
    "region": "Atacama",
    "clima": "Desértico interior",
    "txMax": 31,
    "tnMin": 4,
    "pp": 15,
    "hf": "100–300",
    "heladas": "5–15 días",
    "sequia": "Extremo"
  },
  3: {
    "id": 3,
    "nombre": "La Serena Costa",
    "region": "Coquimbo",
    "clima": "Semiárido costero",
    "txMax": 24,
    "tnMin": 8,
    "pp": 80,
    "hf": "50–200",
    "heladas": "0–5 días",
    "sequia": "Alto"
  },
  4: {
    "id": 4,
    "nombre": "Ovalle - Limarí",
    "region": "Coquimbo",
    "clima": "Semiárido interior",
    "txMax": 30,
    "tnMin": 3,
    "pp": 100,
    "hf": "200–500",
    "heladas": "10–25 días",
    "sequia": "Alto"
  },
  5: {
    "id": 5,
    "nombre": "Valparaíso - Quillota",
    "region": "Valparaíso",
    "clima": "Mediterráneo costero",
    "txMax": 27,
    "tnMin": 5,
    "pp": 350,
    "hf": "300–600",
    "heladas": "5–15 días",
    "sequia": "Medio-Alto"
  },
  6: {
    "id": 6,
    "nombre": "San Felipe - Los Andes",
    "region": "Valparaíso",
    "clima": "Mediterráneo interior",
    "txMax": 32,
    "tnMin": 1,
    "pp": 250,
    "hf": "600–900",
    "heladas": "20–40 días",
    "sequia": "Medio"
  },
  7: {
    "id": 7,
    "nombre": "Santiago Norte",
    "region": "Metropolitana",
    "clima": "Mediterráneo central",
    "txMax": 31,
    "tnMin": 1,
    "pp": 300,
    "hf": "500–800",
    "heladas": "15–30 días",
    "sequia": "Medio"
  },
  8: {
    "id": 8,
    "nombre": "Santiago Sur - Buin",
    "region": "Metropolitana",
    "clima": "Mediterráneo central",
    "txMax": 30,
    "tnMin": 1,
    "pp": 330,
    "hf": "500–900",
    "heladas": "15–35 días",
    "sequia": "Medio"
  },
  9: {
    "id": 9,
    "nombre": "Melipilla - Costa RM",
    "region": "Metropolitana",
    "clima": "Mediterráneo costero int.",
    "txMax": 29,
    "tnMin": 3,
    "pp": 380,
    "hf": "400–700",
    "heladas": "10–25 días",
    "sequia": "Medio"
  },
  10: {
    "id": 10,
    "nombre": "Rancagua - Cachapoal",
    "region": "O'Higgins",
    "clima": "Mediterráneo central",
    "txMax": 30,
    "tnMin": 1,
    "pp": 420,
    "hf": "600–1000",
    "heladas": "20–40 días",
    "sequia": "Medio"
  },
  11: {
    "id": 11,
    "nombre": "Pichilemu Costa",
    "region": "O'Higgins",
    "clima": "Mediterráneo costero",
    "txMax": 23,
    "tnMin": 5,
    "pp": 500,
    "hf": "400–700",
    "heladas": "5–15 días",
    "sequia": "Medio-Bajo"
  },
  12: {
    "id": 12,
    "nombre": "Lago Rapel",
    "region": "O'Higgins",
    "clima": "Mediterráneo interior lac.",
    "txMax": 30,
    "tnMin": 2,
    "pp": 450,
    "hf": "500–800",
    "heladas": "15–30 días",
    "sequia": "Medio"
  },
  13: {
    "id": 13,
    "nombre": "Curicó - Teno",
    "region": "Maule",
    "clima": "Mediterráneo central",
    "txMax": 30,
    "tnMin": 1,
    "pp": 550,
    "hf": "700–1100",
    "heladas": "25–45 días",
    "sequia": "Medio"
  },
  14: {
    "id": 14,
    "nombre": "Talca - Linares",
    "region": "Maule",
    "clima": "Mediterráneo central-sur",
    "txMax": 30,
    "tnMin": 1,
    "pp": 650,
    "hf": "700–1100",
    "heladas": "25–45 días",
    "sequia": "Medio-Bajo"
  },
  15: {
    "id": 15,
    "nombre": "Chillán - Ñuble",
    "region": "Ñuble",
    "clima": "Mediterráneo transición",
    "txMax": 29,
    "tnMin": 1,
    "pp": 800,
    "hf": "800–1200",
    "heladas": "30–50 días",
    "sequia": "Bajo-Medio"
  },
  16: {
    "id": 16,
    "nombre": "Los Ángeles Interior",
    "region": "Biobío",
    "clima": "Mediterráneo-templado",
    "txMax": 28,
    "tnMin": 1,
    "pp": 1000,
    "hf": "900–1300",
    "heladas": "35–55 días",
    "sequia": "Bajo"
  },
  17: {
    "id": 17,
    "nombre": "Concepción Costa",
    "region": "Biobío",
    "clima": "Oceánico templado",
    "txMax": 23,
    "tnMin": 5,
    "pp": 1100,
    "hf": "500–800",
    "heladas": "5–15 días",
    "sequia": "Bajo"
  },
  18: {
    "id": 18,
    "nombre": "Temuco - Araucanía",
    "region": "Araucanía",
    "clima": "Templado lluvioso",
    "txMax": 25,
    "tnMin": 2,
    "pp": 1200,
    "hf": "1000–1500",
    "heladas": "40–60 días",
    "sequia": "Muy bajo"
  },
  19: {
    "id": 19,
    "nombre": "Valdivia - Los Ríos",
    "region": "Los Ríos",
    "clima": "Templado lluvioso",
    "txMax": 22,
    "tnMin": 3,
    "pp": 1800,
    "hf": "1000–1500",
    "heladas": "30–50 días",
    "sequia": "Nulo"
  },
  20: {
    "id": 20,
    "nombre": "Osorno - Los Lagos",
    "region": "Los Lagos",
    "clima": "Templado lluvioso",
    "txMax": 21,
    "tnMin": 3,
    "pp": 1300,
    "hf": "1100–1600",
    "heladas": "35–55 días",
    "sequia": "Nulo"
  }
};

export const COMUNAS_ZONA: Record<string, [number, string]> = {
    "Arica": [
    1,
    "Arica y Parinacota"
  ],
    "Camarones": [
    1,
    "Arica y Parinacota"
  ],
    "Iquique": [
    1,
    "Tarapacá"
  ],
    "Alto Hospicio": [
    1,
    "Tarapacá"
  ],
    "Pozo Almonte": [
    1,
    "Tarapacá"
  ],
    "Camiña": [
    1,
    "Tarapacá"
  ],
    "Colchane": [
    1,
    "Tarapacá"
  ],
    "Huara": [
    1,
    "Tarapacá"
  ],
    "Pica": [
    1,
    "Tarapacá"
  ],
    "Antofagasta": [
    2,
    "Antofagasta"
  ],
    "Mejillones": [
    2,
    "Antofagasta"
  ],
    "Sierra Gorda": [
    2,
    "Antofagasta"
  ],
    "Taltal": [
    2,
    "Antofagasta"
  ],
    "Calama": [
    2,
    "Antofagasta"
  ],
    "Ollagüe": [
    2,
    "Antofagasta"
  ],
    "San Pedro de Atacama": [
    2,
    "Antofagasta"
  ],
    "Tocopilla": [
    2,
    "Antofagasta"
  ],
    "María Elena": [
    2,
    "Antofagasta"
  ],
    "Copiapó": [
    2,
    "Atacama"
  ],
    "Tierra Amarilla": [
    2,
    "Atacama"
  ],
    "Vallenar": [
    2,
    "Atacama"
  ],
    "Alto del Carmen": [
    2,
    "Atacama"
  ],
    "Freirina": [
    2,
    "Atacama"
  ],
    "Huasco": [
    2,
    "Atacama"
  ],
    "La Serena": [
    3,
    "Coquimbo"
  ],
    "Coquimbo": [
    3,
    "Coquimbo"
  ],
    "La Higuera": [
    3,
    "Coquimbo"
  ],
    "Los Vilos": [
    3,
    "Coquimbo"
  ],
    "Vicuña": [
    4,
    "Coquimbo"
  ],
    "Paihuano": [
    4,
    "Coquimbo"
  ],
    "Andacollo": [
    4,
    "Coquimbo"
  ],
    "Ovalle": [
    4,
    "Coquimbo"
  ],
    "Río Hurtado": [
    4,
    "Coquimbo"
  ],
    "Monte Patria": [
    4,
    "Coquimbo"
  ],
    "Combarbalá": [
    4,
    "Coquimbo"
  ],
    "Punitaqui": [
    4,
    "Coquimbo"
  ],
    "Illapel": [
    4,
    "Coquimbo"
  ],
    "Salamanca": [
    4,
    "Coquimbo"
  ],
    "Canela": [
    4,
    "Coquimbo"
  ],
    "Valparaíso": [
    5,
    "Valparaíso"
  ],
    "Viña del Mar": [
    5,
    "Valparaíso"
  ],
    "Quilpué": [
    5,
    "Valparaíso"
  ],
    "Villa Alemana": [
    5,
    "Valparaíso"
  ],
    "Limache": [
    5,
    "Valparaíso"
  ],
    "Olmué": [
    5,
    "Valparaíso"
  ],
    "Quillota": [
    5,
    "Valparaíso"
  ],
    "La Cruz": [
    5,
    "Valparaíso"
  ],
    "Calera": [
    5,
    "Valparaíso"
  ],
    "Nogales": [
    5,
    "Valparaíso"
  ],
    "Hijuelas": [
    5,
    "Valparaíso"
  ],
    "La Ligua": [
    5,
    "Valparaíso"
  ],
    "Cabildo": [
    5,
    "Valparaíso"
  ],
    "Petorca": [
    5,
    "Valparaíso"
  ],
    "Papudo": [
    5,
    "Valparaíso"
  ],
    "Zapallar": [
    5,
    "Valparaíso"
  ],
    "San Antonio": [
    5,
    "Valparaíso"
  ],
    "Casablanca": [
    5,
    "Valparaíso"
  ],
    "San Felipe": [
    6,
    "Valparaíso"
  ],
    "Los Andes": [
    6,
    "Valparaíso"
  ],
    "Putaendo": [
    6,
    "Valparaíso"
  ],
    "Santa María": [
    6,
    "Valparaíso"
  ],
    "Catemu": [
    6,
    "Valparaíso"
  ],
    "Panquehue": [
    6,
    "Valparaíso"
  ],
    "Llay-Llay": [
    6,
    "Valparaíso"
  ],
    "Rinconada": [
    6,
    "Valparaíso"
  ],
    "Calle Larga": [
    6,
    "Valparaíso"
  ],
    "San Esteban": [
    6,
    "Valparaíso"
  ],
    "Colina": [
    7,
    "Metropolitana"
  ],
    "Lampa": [
    7,
    "Metropolitana"
  ],
    "Til Til": [
    7,
    "Metropolitana"
  ],
    "Pudahuel": [
    7,
    "Metropolitana"
  ],
    "Santiago": [
    8,
    "Metropolitana"
  ],
    "Maipú": [
    8,
    "Metropolitana"
  ],
    "La Florida": [
    8,
    "Metropolitana"
  ],
    "Peñalolén": [
    8,
    "Metropolitana"
  ],
    "La Reina": [
    8,
    "Metropolitana"
  ],
    "Las Condes": [
    8,
    "Metropolitana"
  ],
    "Providencia": [
    8,
    "Metropolitana"
  ],
    "Ñuñoa": [
    8,
    "Metropolitana"
  ],
    "San Bernardo": [
    8,
    "Metropolitana"
  ],
    "Buin": [
    8,
    "Metropolitana"
  ],
    "Paine": [
    8,
    "Metropolitana"
  ],
    "Calera de Tango": [
    8,
    "Metropolitana"
  ],
    "Talagante": [
    8,
    "Metropolitana"
  ],
    "Peñaflor": [
    8,
    "Metropolitana"
  ],
    "El Monte": [
    8,
    "Metropolitana"
  ],
    "Isla de Maipo": [
    8,
    "Metropolitana"
  ],
    "Padre Hurtado": [
    8,
    "Metropolitana"
  ],
    "Puente Alto": [
    8,
    "Metropolitana"
  ],
    "Pirque": [
    8,
    "Metropolitana"
  ],
    "San José de Maipo": [
    8,
    "Metropolitana"
  ],
    "Melipilla": [
    9,
    "Metropolitana"
  ],
    "San Pedro": [
    9,
    "Metropolitana"
  ],
    "Alhué": [
    9,
    "Metropolitana"
  ],
    "María Pinto": [
    9,
    "Metropolitana"
  ],
    "Curacaví": [
    9,
    "Metropolitana"
  ],
    "Rancagua": [
    10,
    "O'Higgins"
  ],
    "Machalí": [
    10,
    "O'Higgins"
  ],
    "Graneros": [
    10,
    "O'Higgins"
  ],
    "Codegua": [
    10,
    "O'Higgins"
  ],
    "Requínoa": [
    10,
    "O'Higgins"
  ],
    "Rengo": [
    10,
    "O'Higgins"
  ],
    "Malloa": [
    10,
    "O'Higgins"
  ],
    "Quinta de Tilcoco": [
    10,
    "O'Higgins"
  ],
    "Olivar": [
    10,
    "O'Higgins"
  ],
    "San Vicente": [
    10,
    "O'Higgins"
  ],
    "Coinco": [
    10,
    "O'Higgins"
  ],
    "San Fernando": [
    10,
    "O'Higgins"
  ],
    "Chimbarongo": [
    10,
    "O'Higgins"
  ],
    "Nancagua": [
    10,
    "O'Higgins"
  ],
    "Santa Cruz": [
    10,
    "O'Higgins"
  ],
    "Pichilemu": [
    11,
    "O'Higgins"
  ],
    "Marchigüe": [
    11,
    "O'Higgins"
  ],
    "Litueche": [
    11,
    "O'Higgins"
  ],
    "La Estrella": [
    11,
    "O'Higgins"
  ],
    "Navidad": [
    11,
    "O'Higgins"
  ],
    "Paredones": [
    11,
    "O'Higgins"
  ],
    "Coltauco": [
    12,
    "O'Higgins"
  ],
    "Doñihue": [
    12,
    "O'Higgins"
  ],
    "Las Cabras": [
    12,
    "O'Higgins"
  ],
    "Peumo": [
    12,
    "O'Higgins"
  ],
    "Curicó": [
    13,
    "Maule"
  ],
    "Teno": [
    13,
    "Maule"
  ],
    "Romeral": [
    13,
    "Maule"
  ],
    "Molina": [
    13,
    "Maule"
  ],
    "Sagrada Familia": [
    13,
    "Maule"
  ],
    "Rauco": [
    13,
    "Maule"
  ],
    "Licantén": [
    13,
    "Maule"
  ],
    "Vichuquén": [
    13,
    "Maule"
  ],
    "Hualañé": [
    13,
    "Maule"
  ],
    "Talca": [
    14,
    "Maule"
  ],
    "San Clemente": [
    14,
    "Maule"
  ],
    "Pelarco": [
    14,
    "Maule"
  ],
    "Río Claro": [
    14,
    "Maule"
  ],
    "San Rafael": [
    14,
    "Maule"
  ],
    "Maule": [
    14,
    "Maule"
  ],
    "Curepto": [
    14,
    "Maule"
  ],
    "Constitución": [
    14,
    "Maule"
  ],
    "Linares": [
    14,
    "Maule"
  ],
    "San Javier": [
    14,
    "Maule"
  ],
    "Parral": [
    14,
    "Maule"
  ],
    "Cauquenes": [
    14,
    "Maule"
  ],
    "Longaví": [
    14,
    "Maule"
  ],
    "Retiro": [
    14,
    "Maule"
  ],
    "Villa Alegre": [
    14,
    "Maule"
  ],
    "Yerbas Buenas": [
    14,
    "Maule"
  ],
    "Colbún": [
    14,
    "Maule"
  ],
    "Chillán": [
    15,
    "Ñuble"
  ],
    "Chillán Viejo": [
    15,
    "Ñuble"
  ],
    "San Carlos": [
    15,
    "Ñuble"
  ],
    "Coihueco": [
    15,
    "Ñuble"
  ],
    "Bulnes": [
    15,
    "Ñuble"
  ],
    "Yungay": [
    15,
    "Ñuble"
  ],
    "Quillón": [
    15,
    "Ñuble"
  ],
    "San Nicolás": [
    15,
    "Ñuble"
  ],
    "Pemuco": [
    15,
    "Ñuble"
  ],
    "El Carmen": [
    15,
    "Ñuble"
  ],
    "Pinto": [
    15,
    "Ñuble"
  ],
    "San Fabián": [
    15,
    "Ñuble"
  ],
    "Ñiquén": [
    15,
    "Ñuble"
  ],
    "Cobquecura": [
    15,
    "Ñuble"
  ],
    "Quirihue": [
    15,
    "Ñuble"
  ],
    "Ninhue": [
    15,
    "Ñuble"
  ],
    "Portezuelo": [
    15,
    "Ñuble"
  ],
    "Coelemu": [
    15,
    "Ñuble"
  ],
    "Treguaco": [
    15,
    "Ñuble"
  ],
    "Ránquil": [
    15,
    "Ñuble"
  ],
    "San Ignacio": [
    15,
    "Ñuble"
  ],
    "Los Ángeles": [
    16,
    "Biobío"
  ],
    "Mulchén": [
    16,
    "Biobío"
  ],
    "Nacimiento": [
    16,
    "Biobío"
  ],
    "Santa Bárbara": [
    16,
    "Biobío"
  ],
    "Quilleco": [
    16,
    "Biobío"
  ],
    "Yumbel": [
    16,
    "Biobío"
  ],
    "Cabrero": [
    16,
    "Biobío"
  ],
    "Tucapel": [
    16,
    "Biobío"
  ],
    "Antuco": [
    16,
    "Biobío"
  ],
    "San Rosendo": [
    16,
    "Biobío"
  ],
    "Laja": [
    16,
    "Biobío"
  ],
    "Concepción": [
    17,
    "Biobío"
  ],
    "Chiguayante": [
    17,
    "Biobío"
  ],
    "San Pedro de la Paz": [
    17,
    "Biobío"
  ],
    "Tomé": [
    17,
    "Biobío"
  ],
    "Penco": [
    17,
    "Biobío"
  ],
    "Hualqui": [
    17,
    "Biobío"
  ],
    "Coronel": [
    17,
    "Biobío"
  ],
    "Lota": [
    17,
    "Biobío"
  ],
    "Arauco": [
    17,
    "Biobío"
  ],
    "Lebu": [
    17,
    "Biobío"
  ],
    "Cañete": [
    17,
    "Biobío"
  ],
    "Temuco": [
    18,
    "Araucanía"
  ],
    "Padre Las Casas": [
    18,
    "Araucanía"
  ],
    "Freire": [
    18,
    "Araucanía"
  ],
    "Pitrufquén": [
    18,
    "Araucanía"
  ],
    "Vilcún": [
    18,
    "Araucanía"
  ],
    "Lautaro": [
    18,
    "Araucanía"
  ],
    "Victoria": [
    18,
    "Araucanía"
  ],
    "Angol": [
    18,
    "Araucanía"
  ],
    "Collipulli": [
    18,
    "Araucanía"
  ],
    "Traiguén": [
    18,
    "Araucanía"
  ],
    "Perquenco": [
    18,
    "Araucanía"
  ],
    "Nueva Imperial": [
    18,
    "Araucanía"
  ],
    "Carahue": [
    18,
    "Araucanía"
  ],
    "Villarrica": [
    18,
    "Araucanía"
  ],
    "Pucón": [
    18,
    "Araucanía"
  ],
    "Valdivia": [
    19,
    "Los Ríos"
  ],
    "La Unión": [
    19,
    "Los Ríos"
  ],
    "Paillaco": [
    19,
    "Los Ríos"
  ],
    "Río Bueno": [
    19,
    "Los Ríos"
  ],
    "Los Lagos": [
    19,
    "Los Ríos"
  ],
    "Máfil": [
    19,
    "Los Ríos"
  ],
    "Lanco": [
    19,
    "Los Ríos"
  ],
    "Futrono": [
    19,
    "Los Ríos"
  ],
    "Lago Ranco": [
    19,
    "Los Ríos"
  ],
    "Osorno": [
    20,
    "Los Lagos"
  ],
    "Purranque": [
    20,
    "Los Lagos"
  ],
    "Frutillar": [
    20,
    "Los Lagos"
  ],
    "Puerto Varas": [
    20,
    "Los Lagos"
  ],
    "Puerto Montt": [
    20,
    "Los Lagos"
  ],
    "Llanquihue": [
    20,
    "Los Lagos"
  ],
    "Río Negro": [
    20,
    "Los Lagos"
  ],
    "San Pablo": [
    20,
    "Los Lagos"
  ],
    "Puerto Octay": [
    20,
    "Los Lagos"
  ],
    "Puyehue": [
    20,
    "Los Lagos"
  ],
    "Coyhaique": [
    20,
    "Aysén"
  ],
    "Lago Verde": [
    20,
    "Aysén"
  ],
    "Aysén": [
    20,
    "Aysén"
  ],
    "Cisnes": [
    20,
    "Aysén"
  ],
    "Guaitecas": [
    20,
    "Aysén"
  ],
    "Cochrane": [
    20,
    "Aysén"
  ],
    "O'Higgins": [
    20,
    "Aysén"
  ],
    "Tortel": [
    20,
    "Aysén"
  ],
    "Chile Chico": [
    20,
    "Aysén"
  ],
    "Río Ibáñez": [
    20,
    "Aysén"
  ],
    "Punta Arenas": [
    20,
    "Magallanes"
  ],
    "Laguna Blanca": [
    20,
    "Magallanes"
  ],
    "Río Verde": [
    20,
    "Magallanes"
  ],
    "San Gregorio": [
    20,
    "Magallanes"
  ],
    "Cabo de Hornos": [
    20,
    "Magallanes"
  ],
    "Antártica": [
    20,
    "Magallanes"
  ],
    "Puerto Natales": [
    20,
    "Magallanes"
  ],
    "Torres del Paine": [
    20,
    "Magallanes"
  ],
    "Porvenir": [
    20,
    "Magallanes"
  ],
    "Primavera": [
    20,
    "Magallanes"
  ],
    "Timaukel": [
    20,
    "Magallanes"
  ]
};

