import { COMUNAS } from "./comunas";

// Autogenerated from legacy app (datos.js / db_detalle.js). Do not edit manually.
export interface ZonaClimatica {
  id: number;
  nombre: string;
  region: string;
  clima: string;
  txMax: number;
  tnMin: number;
  pp: number;
  hf: string;
  heladas: string;
  sequia: string;
}

export const ZONAS: Record<number, ZonaClimatica> = {
  1: {
    "id": 1,
    "nombre": "Arica - Azapa",
    "region": "Arica y Parinacota",
    "clima": "Desértico costero",
    "txMax": 27,
    "tnMin": 12,
    "pp": 1,
    "hf": "0–50",
    "heladas": "Sin heladas",
    "sequia": "Extremo"
  },
  2: {
    "id": 2,
    "nombre": "Copiapó Valle",
    "region": "Atacama",
    "clima": "Desértico interior",
    "txMax": 31,
    "tnMin": 4,
    "pp": 15,
    "hf": "100–300",
    "heladas": "5–15 días",
    "sequia": "Extremo"
  },
  3: {
    "id": 3,
    "nombre": "La Serena Costa",
    "region": "Coquimbo",
    "clima": "Semiárido costero",
    "txMax": 24,
    "tnMin": 8,
    "pp": 80,
    "hf": "50–200",
    "heladas": "0–5 días",
    "sequia": "Alto"
  },
  4: {
    "id": 4,
    "nombre": "Ovalle - Limarí",
    "region": "Coquimbo",
    "clima": "Semiárido interior",
    "txMax": 30,
    "tnMin": 3,
    "pp": 100,
    "hf": "200–500",
    "heladas": "10–25 días",
    "sequia": "Alto"
  },
  5: {
    "id": 5,
    "nombre": "Valparaíso - Quillota",
    "region": "Valparaíso",
    "clima": "Mediterráneo costero",
    "txMax": 27,
    "tnMin": 5,
    "pp": 350,
    "hf": "300–600",
    "heladas": "5–15 días",
    "sequia": "Medio-Alto"
  },
  6: {
    "id": 6,
    "nombre": "San Felipe - Los Andes",
    "region": "Valparaíso",
    "clima": "Mediterráneo interior",
    "txMax": 32,
    "tnMin": 1,
    "pp": 250,
    "hf": "600–900",
    "heladas": "20–40 días",
    "sequia": "Medio"
  },
  7: {
    "id": 7,
    "nombre": "Santiago Norte",
    "region": "Metropolitana",
    "clima": "Mediterráneo central",
    "txMax": 31,
    "tnMin": 1,
    "pp": 300,
    "hf": "500–800",
    "heladas": "15–30 días",
    "sequia": "Medio"
  },
  8: {
    "id": 8,
    "nombre": "Santiago Sur - Buin",
    "region": "Metropolitana",
    "clima": "Mediterráneo central",
    "txMax": 30,
    "tnMin": 1,
    "pp": 330,
    "hf": "500–900",
    "heladas": "15–35 días",
    "sequia": "Medio"
  },
  9: {
    "id": 9,
    "nombre": "Melipilla - Costa RM",
    "region": "Metropolitana",
    "clima": "Mediterráneo costero int.",
    "txMax": 29,
    "tnMin": 3,
    "pp": 380,
    "hf": "400–700",
    "heladas": "10–25 días",
    "sequia": "Medio"
  },
  10: {
    "id": 10,
    "nombre": "Rancagua - Cachapoal",
    "region": "O'Higgins",
    "clima": "Mediterráneo central",
    "txMax": 30,
    "tnMin": 1,
    "pp": 420,
    "hf": "600–1000",
    "heladas": "20–40 días",
    "sequia": "Medio"
  },
  11: {
    "id": 11,
    "nombre": "Pichilemu Costa",
    "region": "O'Higgins",
    "clima": "Mediterráneo costero",
    "txMax": 23,
    "tnMin": 5,
    "pp": 500,
    "hf": "400–700",
    "heladas": "5–15 días",
    "sequia": "Medio-Bajo"
  },
  12: {
    "id": 12,
    "nombre": "Lago Rapel",
    "region": "O'Higgins",
    "clima": "Mediterráneo interior lac.",
    "txMax": 30,
    "tnMin": 2,
    "pp": 450,
    "hf": "500–800",
    "heladas": "15–30 días",
    "sequia": "Medio"
  },
  13: {
    "id": 13,
    "nombre": "Curicó - Teno",
    "region": "Maule",
    "clima": "Mediterráneo central",
    "txMax": 30,
    "tnMin": 1,
    "pp": 550,
    "hf": "700–1100",
    "heladas": "25–45 días",
    "sequia": "Medio"
  },
  14: {
    "id": 14,
    "nombre": "Talca - Linares",
    "region": "Maule",
    "clima": "Mediterráneo central-sur",
    "txMax": 30,
    "tnMin": 1,
    "pp": 650,
    "hf": "700–1100",
    "heladas": "25–45 días",
    "sequia": "Medio-Bajo"
  },
  15: {
    "id": 15,
    "nombre": "Chillán - Ñuble",
    "region": "Ñuble",
    "clima": "Mediterráneo transición",
    "txMax": 29,
    "tnMin": 1,
    "pp": 800,
    "hf": "800–1200",
    "heladas": "30–50 días",
    "sequia": "Bajo-Medio"
  },
  16: {
    "id": 16,
    "nombre": "Los Ángeles Interior",
    "region": "Biobío",
    "clima": "Mediterráneo-templado",
    "txMax": 28,
    "tnMin": 1,
    "pp": 1000,
    "hf": "900–1300",
    "heladas": "35–55 días",
    "sequia": "Bajo"
  },
  17: {
    "id": 17,
    "nombre": "Concepción Costa",
    "region": "Biobío",
    "clima": "Oceánico templado",
    "txMax": 23,
    "tnMin": 5,
    "pp": 1100,
    "hf": "500–800",
    "heladas": "5–15 días",
    "sequia": "Bajo"
  },
  18: {
    "id": 18,
    "nombre": "Temuco - Araucanía",
    "region": "Araucanía",
    "clima": "Templado lluvioso",
    "txMax": 25,
    "tnMin": 2,
    "pp": 1200,
    "hf": "1000–1500",
    "heladas": "40–60 días",
    "sequia": "Muy bajo"
  },
  19: {
    "id": 19,
    "nombre": "Valdivia - Los Ríos",
    "region": "Los Ríos",
    "clima": "Templado lluvioso",
    "txMax": 22,
    "tnMin": 3,
    "pp": 1800,
    "hf": "1000–1500",
    "heladas": "30–50 días",
    "sequia": "Nulo"
  },
  20: {
    "id": 20,
    "nombre": "Osorno - Los Lagos",
    "region": "Los Lagos",
    "clima": "Templado lluvioso",
    "txMax": 21,
    "tnMin": 3,
    "pp": 1300,
    "hf": "1100–1600",
    "heladas": "35–55 días",
    "sequia": "Nulo"
  }
};

// Derivado de COMUNAS (lib/agronomy/comunas.ts) — única fuente de verdad:
// nombre de comuna -> [zonaId, region].
export const COMUNAS_ZONA: Record<string, [number, string]> = Object.fromEntries(
  COMUNAS.map((c) => [c.comuna, [c.zonaId, c.region] as [number, string]]),
);


