-- 0032: Base de Datos Técnica de Suelo y Riego GARDENFOOD
-- Generado por scripts/generar_riego_seed.py desde el xlsx de la guía.
-- Ningún valor es inventado: todo sale literal de BD Riego,
-- BD Etapas y Tablas y factores (A-G).

create table if not exists public.gf_riego_suelos (
  clave text primary key,
  nombre text not null,
  tecnico text not null,
  agua_min_mm numeric not null,
  agua_max_mm numeric not null,
  factor numeric not null,
  manejo text not null
);
insert into public.gf_riego_suelos (clave, nombre, tecnico, agua_min_mm, agua_max_mm, factor, manejo) values
('G', 'Gruesa (arenosa)', 'Gruesa (arenosa)', 50, 100, 0.7, 'Suelo que se seca rápido: riegue MÁS SEGUIDO y con MENOS agua cada vez. Un riego grande se le escapa hacia abajo y se pierde. Ponga mulch (paja, pasto seco, hojas) de 10 cm bajo la copa y agregue compost cada año: es lo que más le sube la retención de agua.'),
('MG', 'Moderadamente gruesa', 'Moderadamente gruesa', 108, 142, 0.85, 'Suelo cómodo pero algo suelto. Riegue en dos tiempos (mitad del agua, esperar 20 minutos, la otra mitad) para que no escurra. Mulch de 8-10 cm y compost anual.'),
('M', 'Media (franca)', 'Media (franca)', 125, 175, 1, 'El mejor suelo para frutales: retiene bien y drena bien. Mantenga el mulch y no lo pise cuando está mojado, porque se compacta. Riegue en el borde de la copa, no pegado al tronco.'),
('F', 'Fina (arcillosa)', 'Fina (arcillosa)', 133, 200, 1.15, 'Suelo que retiene mucha agua: riegue MENOS SEGUIDO y con MÁS agua cada vez, pero LENTO. Si el agua se empoza, pare y espere. El riesgo real acá no es la sequía, es la asfixia de raíces: nunca riegue si al apretar el suelo queda pegajoso y resbaloso.');

create table if not exists public.gf_riego_humedad (
  nivel integer primary key,
  nombre text not null,
  pct_min numeric not null,
  pct_max numeric not null,
  factor_riego numeric not null,
  factor_control numeric not null,
  significado text not null
);
insert into public.gf_riego_humedad (nivel, nombre, pct_min, pct_max, factor_riego, factor_control, significado) values
(1, '0-25 % — muy seco', 0, 25, 1.3, 0, 'RIEGUE HOY. El suelo está en déficit fuerte: el árbol ya está sufriendo.'),
(2, '25-50 % — seco (punto de riego)', 25, 50, 1, 0, 'RIEGUE HOY. Este es el momento correcto para regar frutales.'),
(3, '50-75 % — húmedo', 50, 75, 0, 0.35, 'NO RIEGUE todavía. Queda agua disponible en la zona de raíces.'),
(4, '75-100 % — muy húmedo', 75, 100, 0, 0.6, 'NO RIEGUE. El suelo está casi lleno de agua.'),
(5, '100 % — capacidad de campo', 100, 100, 0, 0.75, 'NO RIEGUE. El suelo está lleno. Si sigue así 3 días, revise el drenaje.');

create table if not exists public.gf_riego_edad (
  n integer primary key,
  nombre text not null,
  factor_litros numeric not null,
  factor_dias numeric not null
);
insert into public.gf_riego_edad (n, nombre, factor_litros, factor_dias) values
(1, 'Recién plantado (0-1 año)', 0.3, 0.55),
(2, 'Joven (2-3 años)', 0.55, 0.75),
(3, 'En producción inicial (4-5 años)', 0.8, 0.9),
(4, 'Adulto (6 años o más)', 1, 1);

create table if not exists public.gf_riego_especies (
  especie text primary key,
  excel_nombre text not null,
  nombre_cientifico text not null,
  grupo text not null,
  mantencion_l numeric not null,
  suelo text not null,
  ph text not null,
  copa_ref_m numeric not null
);
insert into public.gf_riego_especies (especie, excel_nombre, nombre_cientifico, grupo, mantencion_l, suelo, ph, copa_ref_m) values
('Duraznero', 'Duraznero', 'Prunus persica', 'Carozo', 11, 'Suelto, profundo, que drene bien (que el agua no se quede estancada).', '6.0 a 7.0 (ligeramente ácido a neutro)', 2),
('Ciruelo', 'Ciruelo', 'Prunus domestica / Prunus salicina', 'Carozo', 15, 'Bien drenado, tolera suelos un poco más arcillosos', '6.0 a 7.5', 2),
('Cerezo', 'Cerezo', 'Prunus avium', 'Carozo', 15, 'Profundo, suelto, MUY bien drenado (no tolera agua estancada)', '6.5 a 7.5', 2),
('Damasco', 'Damasco', 'Prunus armeniaca', 'Carozo', 16, 'Suelto, bien drenado, profundo', '6.5 a 8.0', 2),
('Nectarino', 'Nectarino', 'Prunus persica var. nucipersica', 'Carozo', 15, 'Suelto, profundo, drenado', '6.0 a 7.0', 2),
('Manzano', 'Manzano', 'Malus domestica', 'Pomácea', 19, 'Profundo, fértil, drenado. Tolera variedad de suelos', '6.0 a 7.0', 2),
('Peral', 'Peral', 'Pyrus communis', 'Pomácea', 19, 'Profundo, drenado, tolera arcilla mejor que manzano', '6.0 a 7.5', 2),
('Membrillo', 'Membrillo', 'Cydonia oblonga', 'Pomácea', 15, 'Tolera variedad, prefiere algo húmedo', '6.0 a 7.5', 2),
('Limonero', 'Limonero', 'Citrus × limon', 'Cítrico', 15, 'Drenado, NO encharcado', '6.0 a 7.0', 2),
('Naranjo', 'Naranjo', 'Citrus × sinensis', 'Cítrico', 22, 'Drenado, profundo, fértil', '6.0 a 7.0', 2),
('Mandarino', 'Mandarino', 'Citrus reticulata', 'Cítrico', 15, 'Drenado, fértil', '6.0 a 7.0', 2),
('Pomelo', 'Pomelo', 'Citrus × paradisi', 'Cítrico', 22, 'Drenado, profundo', '6.0 a 7.0', 2),
('Nogal', 'Nogal', 'Juglans regia', 'Fruto seco', 30, 'Profundo (raíz pivotante), drenado, fértil', '6.5 a 7.5', 2),
('Almendro', 'Almendro', 'Prunus dulcis', 'Fruto seco', 21, 'Drenado, tolera secos y pedregosos', '7.0 a 8.0 (tolera algo calcáreo)', 2),
('Higuera', 'Higuera', 'Ficus carica', 'Otros', 15, 'Tolera CASI TODO: arcilloso, pedregoso, pobre', '6.0 a 8.5 (tolerantísimo)', 2),
('Granado', 'Granado', 'Punica granatum', 'Otros', 15, 'Tolera variedad, prefiere drenado. Aguanta salinidad', '5.5 a 8.0 (MUY tolerante)', 2),
('Caqui', 'Caqui', 'Diospyros kaki', 'Otros', 15, 'Profundo, drenado, fértil', '6.0 a 7.5', 2),
('Vid', 'Vid', 'Vitis vinifera', 'Vid', 11, 'Drenado, tolera suelos pobres y pedregosos. NO le gusta rico en nitrógeno', '6.0 a 7.5', 2.5),
('Arandano', 'Arandano', 'Vaccinium corymbosum', 'Baya', 4, 'ÁCIDO (pH 4.5-5.5), suelto, con materia orgánica. Es EXIGENTE en suelo', '4.5 a 5.5 (ÁCIDO — esto es CRÍTICO)', 1.5),
('Olivo', 'Olivo', 'Olea europaea', 'Oleáceo', 15, 'Tolera suelos pobres, pedregosos, calcáreos. Drenaje es OBLIGATORIO', '6.5 a 8.5 (tolerantísimo)', 3),
('Frutilla', 'Frutilla', 'Fragaria × ananassa', 'Berries', 2, 'Suelto, arenoso-franco, MUY bien drenado y rico en materia orgánica. La raíz es superficial (20-30 cm): se seca rápido.', '5.5 a 6.5', 0.3),
('Frambuesa', 'Frambuesa', 'Rubus idaeus', 'Berries', 6, 'Franco arenoso, profundo y bien drenado. No tolera el agua estancada ni un minuto.', '5.5 a 6.5', 1),
('Mora', 'Mora', 'Rubus fruticosus', 'Berries', 8, 'Se adapta a casi cualquier suelo con tal de que drene. Es el berry más rústico.', '5.5 a 7.0', 1.5),
('Kiwi', 'Kiwi', 'Actinidia deliciosa', 'Enredadera frutal', 30, 'Franco arenoso profundo, con drenaje perfecto. Raíz superficial y muy sensible a la asfixia: 48 horas con agua estancada la matan.', '5.5 a 6.5 (no tolera suelos calcáreos)', 3.5),
('Avellano Europeo', 'Avellano', 'Corylus avellana', 'Frutos secos', 15, 'Franco, profundo y bien drenado. Tolera bien el frío y la lluvia de invierno del sur.', '6.0 a 7.5', 3.5),
('Níspero Japonés', 'Níspero', 'Eriobotrya japonica', 'Siempreverde', 19, 'Se adapta bien, con tal de que drene. Tolera la costa y el viento salino.', '6.0 a 7.5', 3.5),
('Lúcuma', 'Lúcuma', 'Pouteria lucuma', 'Siempreverde subtropical', 22, 'Suelto y MUY bien drenado. Es más sensible al exceso de agua que a la falta.', '6.0 a 7.0', 4),
('Palto', 'Palta', 'Persea americana', 'Siempreverde subtropical', 26, 'Suelto, profundo y con drenaje EXCELENTE. Raíz superficial y muy sensible a la asfixia y a Phytophthora. En suelo pesado, plante sobre camellón.', '5.5 a 7.0', 4),
('Chirimoya', 'Chirimoya', 'Annona cherimola', 'Subtropical', 15, 'Franco, profundo y bien drenado. No tolera heladas ni suelo pesado.', '6.5 a 7.5', 4),
('Papayo Chileno', 'Papayo chileno', 'Vasconcellea pubescens', 'Nativo subtropical', 11, 'Suelto y muy bien drenado. El cuello del tallo se pudre si le queda agua encima.', '6.0 a 7.0', 2.5);

create table if not exists public.gf_riego_zonas (
  clave text primary key,
  nombre text not null,
  donde_queda text not null,
  eto_verano text not null,
  factor_clima numeric not null,
  desfase integer not null,
  significado text not null
);
insert into public.gf_riego_zonas (clave, nombre, donde_queda, eto_verano, factor_clima, desfase, significado) values
('N1', 'Norte y valles transversales', 'Copiapó, Vallenar, Ovalle, Illapel, interior de Coquimbo', '6 a 7', 1.3, -1, 'Acá todo pasa antes: la flor puede adelantarse entre tres y cuatro semanas respecto del valle central.'),
('N2', 'Costa norte', 'La Serena, Tongoy, Los Vilos, Papudo', '4 a 5', 0.95, 0, 'La camanchaca y el mar bajan la demanda pese a la latitud. La fenología se adelanta una o dos semanas.'),
('C1', 'Valle central interior', 'Aconcagua, Santiago, Melipilla, Rancagua, San Fernando, Curicó', '6 a 6,5', 1, 0, 'Es la zona de referencia de la base de datos: acá el calendario original calza tal cual.'),
('C2', 'Costa central', 'Casablanca, Litoral de Valparaíso y O''Higgins, Pichilemu', '4 a 4,5', 0.78, 0, 'Menos calor y más humedad: el mismo árbol pide bastante menos agua que a 60 km hacia el interior.'),
('S1', 'Centro sur', 'Talca, Linares, Cauquenes, Chillán, Ñuble, Los Ángeles', '5 a 5,5', 0.88, 0, 'La fenología va una a dos semanas más atrás que en Santiago: si el calendario no calza, confíe en lo que ve en el árbol.'),
('S2', 'Sur', 'Temuco, Villarrica, Valdivia, Osorno, Puerto Montt', '4 a 4,8', 0.72, 1, 'Acá todo pasa después: la flor se atrasa entre tres y cuatro semanas. Además llueve en verano, así que muchas veces el test de la bola le va a decir que no riegue.'),
('P1', 'Precordillera y zonas de altura', 'Curacautín, Las Trancas, secano de altura, valles cordilleranos', '4,5 a 5,5', 0.9, 1, 'El frío atrasa la brotación y acorta la temporada. Cuide más las heladas tardías que el riego.'),
('V1', 'Verano muy caluroso y seco, sobre 32 °C, prácticamente sin lluvia', 'Para quien no conoce su zona o está fuera de Chile', '—', 1.3, 0, 'Se usa solo la demanda de agua descrita; el calendario queda en el del valle central.'),
('V2', 'Verano caluroso y seco, entre 28 y 32 °C', 'Para quien no conoce su zona o está fuera de Chile', '—', 1, 0, 'Se usa solo la demanda de agua descrita; el calendario queda en el del valle central.'),
('V3', 'Verano templado, entre 24 y 28 °C, con alguna lluvia', 'Para quien no conoce su zona o está fuera de Chile', '—', 0.88, 0, 'Se usa solo la demanda de agua descrita; el calendario queda en el del valle central.'),
('V4', 'Verano fresco, bajo 24 °C, o con neblina de mar casi todos los días', 'Para quien no conoce su zona o está fuera de Chile', '—', 0.75, 0, 'Se usa solo la demanda de agua descrita; el calendario queda en el del valle central.');

create table if not exists public.gf_riego_kc (
  codigo text primary key,
  descripcion text not null,
  kc numeric
);
insert into public.gf_riego_kc (codigo, descripcion, kc) values
('CAL', 'Prefiero que lo decida el calendario del mes', NULL),
('BRO', 'Yemas hinchadas o brotes nuevos saliendo', 0.45),
('FLO', 'En flor', 0.55),
('CUA', 'Frutos recién cuajados, del tamaño de una arveja', 0.7),
('CRE', 'Frutos creciendo, todavía verdes y duros', 0.9),
('MAD', 'Frutos tomando color, madurando o en cosecha', 0.85),
('POS', 'Ya cosechó, el árbol sigue con hojas', 0.65),
('REP', 'Sin hojas, o parado sin crecer (invierno)', 0.2);

create table if not exists public.gf_riego_mensual (
  especie text not null,
  mes integer not null check (mes between 1 and 12),
  etapa text not null,
  dias_min numeric not null,
  dias_max numeric not null,
  litros_min numeric not null,
  litros_max numeric not null,
  reposo integer not null default 0,
  primary key (especie, mes)
);
insert into public.gf_riego_mensual (especie, mes, etapa, dias_min, dias_max, litros_min, litros_max, reposo) values
('Duraznero', 1, 'Maduración', 3, 4, 60, 80, 0),
('Duraznero', 2, 'Maduración → Postcosecha', 5, 7, 45, 60, 0),
('Duraznero', 3, 'Postcosecha', 7, 10, 30, 40, 0),
('Duraznero', 4, 'Postcosecha', 7, 10, 30, 40, 0),
('Duraznero', 5, 'Reposo', 15, 15, 15, 20, 0),
('Duraznero', 6, 'Reposo', 15, 15, 15, 20, 0),
('Duraznero', 7, 'Reposo', 15, 15, 15, 20, 0),
('Duraznero', 8, 'Reposo', 15, 15, 15, 20, 0),
('Duraznero', 9, 'Brotación', 7, 10, 20, 30, 0),
('Duraznero', 10, 'Brotación → Floración → Cuaja', 6, 7, 30, 40, 0),
('Duraznero', 11, 'Cuaja → Crecimiento de fruto', 4, 5, 45, 60, 0),
('Duraznero', 12, 'Crecimiento de fruto → Maduración', 3, 4, 55, 75, 0),
('Ciruelo', 1, 'Maduración', 3, 4, 60, 70, 0),
('Ciruelo', 2, 'Maduración → Postcosecha', 6, 7, 45, 50, 0),
('Ciruelo', 3, 'Postcosecha', 10, 10, 30, 30, 0),
('Ciruelo', 4, 'Postcosecha', 10, 10, 30, 30, 0),
('Ciruelo', 5, 'Reposo', 20, 20, 0, 0, 1),
('Ciruelo', 6, 'Reposo', 20, 20, 0, 0, 1),
('Ciruelo', 7, 'Reposo', 20, 20, 0, 0, 1),
('Ciruelo', 8, 'Brotación', 10, 10, 20, 30, 0),
('Ciruelo', 9, 'Brotación → Floración', 8, 8, 25, 30, 0),
('Ciruelo', 10, 'Floración → Cuaja', 6, 7, 35, 35, 0),
('Ciruelo', 11, 'Cuaja → Crecimiento', 4, 6, 45, 50, 0),
('Ciruelo', 12, 'Crecimiento → Maduración', 4, 4, 55, 65, 0),
('Cerezo', 1, 'Postcosecha', 7, 10, 40, 40, 0),
('Cerezo', 2, 'Postcosecha', 7, 10, 40, 40, 0),
('Cerezo', 3, 'Postcosecha', 7, 10, 40, 40, 0),
('Cerezo', 4, 'Reposo', 20, 20, 0, 0, 1),
('Cerezo', 5, 'Reposo', 20, 20, 0, 0, 1),
('Cerezo', 6, 'Reposo', 20, 20, 0, 0, 1),
('Cerezo', 7, 'Reposo', 20, 20, 0, 0, 1),
('Cerezo', 8, 'Brotación', 10, 10, 20, 20, 0),
('Cerezo', 9, 'Brotación → Floración', 8, 8, 25, 25, 0),
('Cerezo', 10, 'Cuaja → Crecimiento', 4, 6, 45, 45, 0),
('Cerezo', 11, 'Crecimiento → Pinta y maduración', 4, 5, 45, 45, 0),
('Cerezo', 12, 'Pinta y maduración → Postcosecha', 6, 8, 40, 40, 0),
('Damasco', 1, 'Postcosecha', 10, 10, 30, 30, 0),
('Damasco', 2, 'Postcosecha', 10, 10, 30, 30, 0),
('Damasco', 3, 'Postcosecha', 10, 10, 30, 30, 0),
('Damasco', 4, 'Reposo', 20, 20, 0, 0, 1),
('Damasco', 5, 'Reposo', 20, 20, 0, 0, 1),
('Damasco', 6, 'Reposo', 20, 20, 0, 0, 1),
('Damasco', 7, 'Reposo', 20, 20, 0, 0, 1),
('Damasco', 8, 'Brotación → Floración', 8, 8, 22, 22, 0),
('Damasco', 9, 'Floración → Cuaja', 6, 7, 30, 30, 0),
('Damasco', 10, 'Cuaja → Crecimiento', 4, 6, 40, 40, 0),
('Damasco', 11, 'Crecimiento → Maduración', 4, 4, 48, 48, 0),
('Damasco', 12, 'Maduración → Postcosecha', 7, 7, 40, 40, 0),
('Nectarino', 1, 'Maduración', 3, 4, 60, 80, 0),
('Nectarino', 2, 'Maduración → Postcosecha', 5, 7, 45, 60, 0),
('Nectarino', 3, 'Postcosecha', 7, 10, 30, 40, 0),
('Nectarino', 4, 'Postcosecha', 7, 10, 30, 40, 0),
('Nectarino', 5, 'Reposo', 20, 20, 0, 0, 1),
('Nectarino', 6, 'Reposo', 20, 20, 0, 0, 1),
('Nectarino', 7, 'Reposo', 20, 20, 0, 0, 1),
('Nectarino', 8, 'Reposo', 20, 20, 0, 0, 1),
('Nectarino', 9, 'Brotación', 7, 10, 20, 30, 0),
('Nectarino', 10, 'Floración → Cuaja', 5, 6, 35, 45, 0),
('Nectarino', 11, 'Cuaja → Crecimiento', 4, 5, 45, 60, 0),
('Nectarino', 12, 'Crecimiento → Maduración', 3, 4, 55, 75, 0);
insert into public.gf_riego_mensual (especie, mes, etapa, dias_min, dias_max, litros_min, litros_max, reposo) values
('Manzano', 1, 'Crecimiento', 5, 7, 50, 70, 0),
('Manzano', 2, 'Maduración', 7, 7, 50, 50, 0),
('Manzano', 3, 'Maduración', 7, 7, 50, 50, 0),
('Manzano', 4, 'Maduración → Postcosecha', 8, 8, 40, 40, 0),
('Manzano', 5, 'Postcosecha', 10, 10, 30, 30, 0),
('Manzano', 6, 'Reposo', 20, 20, 0, 0, 1),
('Manzano', 7, 'Reposo', 20, 20, 0, 0, 1),
('Manzano', 8, 'Reposo', 20, 20, 0, 0, 1),
('Manzano', 9, 'Brotación', 10, 10, 25, 25, 0),
('Manzano', 10, 'Floración → Cuaja', 7, 7, 35, 35, 0),
('Manzano', 11, 'Cuaja → Crecimiento', 6, 7, 45, 55, 0),
('Manzano', 12, 'Crecimiento', 5, 7, 50, 70, 0),
('Peral', 1, 'Crecimiento', 5, 7, 50, 60, 0),
('Peral', 2, 'Maduración', 7, 7, 50, 50, 0),
('Peral', 3, 'Maduración', 7, 7, 50, 50, 0),
('Peral', 4, 'Postcosecha', 10, 10, 30, 30, 0),
('Peral', 5, 'Postcosecha', 10, 10, 30, 30, 0),
('Peral', 6, 'Reposo', 20, 20, 0, 0, 1),
('Peral', 7, 'Reposo', 20, 20, 0, 0, 1),
('Peral', 8, 'Reposo', 20, 20, 0, 0, 1),
('Peral', 9, 'Brotación', 10, 10, 25, 25, 0),
('Peral', 10, 'Floración → Cuaja', 7, 7, 35, 35, 0),
('Peral', 11, 'Cuaja → Crecimiento', 6, 7, 45, 50, 0),
('Peral', 12, 'Crecimiento', 5, 7, 50, 60, 0),
('Membrillo', 1, 'Crecimiento', 7, 7, 40, 40, 0),
('Membrillo', 2, 'Crecimiento', 7, 7, 40, 40, 0),
('Membrillo', 3, 'Maduración', 7, 10, 30, 40, 0),
('Membrillo', 4, 'Maduración', 7, 10, 30, 40, 0),
('Membrillo', 5, 'Maduración → Postcosecha', 11, 12, 25, 30, 0),
('Membrillo', 6, 'Postcosecha', 15, 15, 20, 20, 0),
('Membrillo', 7, 'Reposo', 20, 20, 0, 0, 1),
('Membrillo', 8, 'Reposo', 20, 20, 0, 0, 1),
('Membrillo', 9, 'Brotación', 10, 10, 20, 20, 0),
('Membrillo', 10, 'Floración', 7, 10, 25, 25, 0),
('Membrillo', 11, 'Cuaja', 7, 7, 30, 30, 0),
('Membrillo', 12, 'Crecimiento', 7, 7, 40, 40, 0),
('Limonero', 1, 'Verano', 4, 7, 50, 70, 0),
('Limonero', 2, 'Verano', 4, 7, 50, 70, 0),
('Limonero', 3, 'Otoño', 10, 10, 30, 40, 0),
('Limonero', 4, 'Otoño', 10, 10, 30, 40, 0),
('Limonero', 5, 'Otoño', 10, 10, 30, 40, 0),
('Limonero', 6, 'Invierno', 15, 15, 20, 30, 0),
('Limonero', 7, 'Invierno', 15, 15, 20, 30, 0),
('Limonero', 8, 'Invierno', 15, 15, 20, 30, 0),
('Limonero', 9, 'Primavera', 7, 10, 30, 40, 0),
('Limonero', 10, 'Primavera', 7, 10, 30, 40, 0),
('Limonero', 11, 'Primavera', 7, 10, 30, 40, 0),
('Limonero', 12, 'Verano', 4, 7, 50, 70, 0),
('Naranjo', 1, 'Verano', 4, 7, 60, 80, 0),
('Naranjo', 2, 'Verano', 4, 7, 60, 80, 0),
('Naranjo', 3, 'Otoño', 10, 10, 40, 40, 0),
('Naranjo', 4, 'Otoño', 10, 10, 40, 40, 0),
('Naranjo', 5, 'Otoño', 10, 10, 40, 40, 0),
('Naranjo', 6, 'Invierno', 15, 15, 30, 30, 0),
('Naranjo', 7, 'Invierno', 15, 15, 30, 30, 0),
('Naranjo', 8, 'Invierno', 15, 15, 30, 30, 0),
('Naranjo', 9, 'Primavera', 7, 10, 40, 40, 0),
('Naranjo', 10, 'Primavera', 7, 10, 40, 40, 0),
('Naranjo', 11, 'Primavera', 7, 10, 40, 40, 0),
('Naranjo', 12, 'Verano', 4, 7, 60, 80, 0);
insert into public.gf_riego_mensual (especie, mes, etapa, dias_min, dias_max, litros_min, litros_max, reposo) values
('Mandarino', 1, 'Verano', 4, 7, 50, 60, 0),
('Mandarino', 2, 'Verano', 4, 7, 50, 60, 0),
('Mandarino', 3, 'Otoño', 10, 10, 30, 30, 0),
('Mandarino', 4, 'Otoño', 10, 10, 30, 30, 0),
('Mandarino', 5, 'Otoño', 10, 10, 30, 30, 0),
('Mandarino', 6, 'Invierno', 15, 15, 20, 20, 0),
('Mandarino', 7, 'Invierno', 15, 15, 20, 20, 0),
('Mandarino', 8, 'Invierno', 15, 15, 20, 20, 0),
('Mandarino', 9, 'Primavera', 7, 10, 30, 30, 0),
('Mandarino', 10, 'Primavera', 7, 10, 30, 30, 0),
('Mandarino', 11, 'Primavera', 7, 10, 30, 30, 0),
('Mandarino', 12, 'Verano', 4, 7, 50, 60, 0),
('Pomelo', 1, 'Verano', 4, 7, 70, 90, 0),
('Pomelo', 2, 'Verano', 4, 7, 70, 90, 0),
('Pomelo', 3, 'Otoño', 10, 10, 40, 40, 0),
('Pomelo', 4, 'Otoño', 10, 10, 40, 40, 0),
('Pomelo', 5, 'Otoño', 10, 10, 40, 40, 0),
('Pomelo', 6, 'Invierno', 15, 15, 30, 30, 0),
('Pomelo', 7, 'Invierno', 15, 15, 30, 30, 0),
('Pomelo', 8, 'Invierno', 15, 15, 30, 30, 0),
('Pomelo', 9, 'Primavera', 7, 10, 40, 40, 0),
('Pomelo', 10, 'Primavera', 7, 10, 40, 40, 0),
('Pomelo', 11, 'Primavera', 7, 10, 40, 40, 0),
('Pomelo', 12, 'Verano', 4, 7, 70, 90, 0),
('Nogal', 1, 'Llenado', 5, 7, 100, 150, 0),
('Nogal', 2, 'Llenado', 5, 7, 100, 150, 0),
('Nogal', 3, 'Maduración', 7, 10, 80, 80, 0),
('Nogal', 4, 'Maduración → Postcosecha', 11, 12, 65, 65, 0),
('Nogal', 5, 'Postcosecha', 15, 15, 50, 50, 0),
('Nogal', 6, 'Reposo', 20, 20, 0, 0, 1),
('Nogal', 7, 'Reposo', 20, 20, 0, 0, 1),
('Nogal', 8, 'Reposo', 20, 20, 0, 0, 1),
('Nogal', 9, 'Brotación', 10, 15, 40, 60, 0),
('Nogal', 10, 'Brotación → Floración', 10, 12, 45, 60, 0),
('Nogal', 11, 'Crecimiento fruto', 7, 10, 80, 120, 0),
('Nogal', 12, 'Crecimiento fruto', 7, 10, 80, 120, 0),
('Almendro', 1, 'Llenado', 7, 7, 50, 50, 0),
('Almendro', 2, 'Maduración', 10, 15, 30, 30, 0),
('Almendro', 3, 'Maduración', 10, 15, 30, 30, 0),
('Almendro', 4, 'Postcosecha-reposo', 20, 20, 0, 0, 1),
('Almendro', 5, 'Postcosecha-reposo', 20, 20, 0, 0, 1),
('Almendro', 6, 'Postcosecha-reposo', 20, 20, 0, 0, 1),
('Almendro', 7, 'Postcosecha-reposo', 20, 20, 0, 0, 1),
('Almendro', 8, 'Brotación → Floración', 10, 12, 28, 28, 0),
('Almendro', 9, 'Brotación → Floración → Cuaja', 9, 12, 32, 32, 0),
('Almendro', 10, 'Cuaja → Crecimiento', 7, 10, 45, 50, 0),
('Almendro', 11, 'Crecimiento', 7, 10, 50, 60, 0),
('Almendro', 12, 'Crecimiento → Llenado', 7, 8, 50, 55, 0),
('Higuera', 1, 'Maduración 1ra cosecha', 5, 7, 40, 40, 0),
('Higuera', 2, 'Maduración 2da cosecha', 5, 7, 40, 40, 0),
('Higuera', 3, 'Maduración 2da cosecha', 5, 7, 40, 40, 0),
('Higuera', 4, 'Postcosecha', 15, 15, 20, 20, 0),
('Higuera', 5, 'Postcosecha', 15, 15, 20, 20, 0),
('Higuera', 6, 'Reposo', 20, 20, 0, 0, 1),
('Higuera', 7, 'Reposo', 20, 20, 0, 0, 1),
('Higuera', 8, 'Reposo', 20, 20, 0, 0, 1),
('Higuera', 9, 'Brotación', 10, 15, 20, 20, 0),
('Higuera', 10, 'Brotación', 10, 15, 20, 20, 0),
('Higuera', 11, 'Crecimiento', 7, 10, 30, 40, 0),
('Higuera', 12, 'Crecimiento → Maduración 1ra cosecha', 6, 8, 35, 40, 0);
insert into public.gf_riego_mensual (especie, mes, etapa, dias_min, dias_max, litros_min, litros_max, reposo) values
('Granado', 1, 'Crecimiento', 5, 7, 40, 50, 0),
('Granado', 2, 'Crecimiento', 5, 7, 40, 50, 0),
('Granado', 3, 'Maduración', 7, 10, 30, 40, 0),
('Granado', 4, 'Maduración', 7, 10, 30, 40, 0),
('Granado', 5, 'Maduración → Postcosecha', 11, 12, 25, 30, 0),
('Granado', 6, 'Postcosecha', 15, 15, 20, 20, 0),
('Granado', 7, 'Reposo', 20, 20, 0, 0, 1),
('Granado', 8, 'Reposo', 20, 20, 0, 0, 1),
('Granado', 9, 'Brotación', 10, 15, 20, 20, 0),
('Granado', 10, 'Brotación', 10, 15, 20, 20, 0),
('Granado', 11, 'Floración', 7, 10, 30, 30, 0),
('Granado', 12, 'Floración → Crecimiento', 6, 8, 35, 40, 0),
('Caqui', 1, 'Crecimiento', 5, 7, 50, 60, 0),
('Caqui', 2, 'Crecimiento', 5, 7, 50, 60, 0),
('Caqui', 3, 'Maduración', 7, 10, 40, 40, 0),
('Caqui', 4, 'Maduración', 7, 10, 40, 40, 0),
('Caqui', 5, 'Maduración', 7, 10, 40, 40, 0),
('Caqui', 6, 'Postcosecha', 15, 15, 20, 20, 0),
('Caqui', 7, 'Reposo', 20, 20, 0, 0, 1),
('Caqui', 8, 'Reposo', 20, 20, 0, 0, 1),
('Caqui', 9, 'Brotación', 10, 15, 25, 25, 0),
('Caqui', 10, 'Brotación', 10, 15, 25, 25, 0),
('Caqui', 11, 'Floración', 7, 10, 30, 30, 0),
('Caqui', 12, 'Crecimiento', 5, 7, 50, 60, 0),
('Vid', 1, 'Envero-maduración', 7, 10, 20, 30, 0),
('Vid', 2, 'Envero-maduración', 7, 10, 20, 30, 0),
('Vid', 3, 'Maduración final', 20, 20, 0, 0, 1),
('Vid', 4, 'Postcosecha-reposo', 20, 20, 0, 0, 1),
('Vid', 5, 'Postcosecha-reposo', 20, 20, 0, 0, 1),
('Vid', 6, 'Postcosecha-reposo', 20, 20, 0, 0, 1),
('Vid', 7, 'Postcosecha-reposo', 20, 20, 0, 0, 1),
('Vid', 8, 'Postcosecha-reposo', 20, 20, 0, 0, 1),
('Vid', 9, 'Brotación', 10, 10, 15, 20, 0),
('Vid', 10, 'Crecimiento brotes', 7, 10, 20, 30, 0),
('Vid', 11, 'Floración → Cuaja-crecimiento', 6, 8, 28, 35, 0),
('Vid', 12, 'Cuaja-crecimiento', 5, 7, 30, 40, 0),
('Arandano', 1, 'Maduración', 2, 3, 10, 15, 0),
('Arandano', 2, 'Maduración → Postcosecha', 4, 4, 9, 12, 0),
('Arandano', 3, 'Postcosecha', 5, 5, 8, 8, 0),
('Arandano', 4, 'Postcosecha', 5, 5, 8, 8, 0),
('Arandano', 5, 'Reposo', 10, 15, 5, 5, 0),
('Arandano', 6, 'Reposo', 10, 15, 5, 5, 0),
('Arandano', 7, 'Reposo', 10, 15, 5, 5, 0),
('Arandano', 8, 'Reposo', 10, 15, 5, 5, 0),
('Arandano', 9, 'Brotación', 3, 5, 5, 10, 0),
('Arandano', 10, 'Floración', 3, 5, 8, 10, 0),
('Arandano', 11, 'Cuaja-crecimiento', 2, 3, 10, 15, 0),
('Arandano', 12, 'Cuaja-crecimiento → Maduración', 2, 3, 10, 15, 0),
('Olivo', 1, 'Crecimiento', 7, 10, 50, 50, 0),
('Olivo', 2, 'Crecimiento', 7, 10, 50, 50, 0),
('Olivo', 3, 'Envero-maduración', 10, 15, 30, 40, 0),
('Olivo', 4, 'Envero-maduración', 10, 15, 30, 40, 0),
('Olivo', 5, 'Envero-maduración', 10, 15, 30, 40, 0),
('Olivo', 6, 'Postcosecha', 15, 20, 20, 20, 0),
('Olivo', 7, 'Postcosecha', 15, 20, 20, 20, 0),
('Olivo', 8, 'Reposo', 20, 20, 0, 0, 1),
('Olivo', 9, 'Brotación', 15, 15, 20, 30, 0),
('Olivo', 10, 'Brotación', 15, 15, 20, 30, 0),
('Olivo', 11, 'Floración', 10, 15, 30, 30, 0),
('Olivo', 12, 'Cuaja', 10, 10, 40, 40, 0);
insert into public.gf_riego_mensual (especie, mes, etapa, dias_min, dias_max, litros_min, litros_max, reposo) values
('Frutilla', 1, 'Fructificación y cosecha', 2, 2, 3, 4, 0),
('Frutilla', 2, 'Postcosecha', 4, 5, 2, 3, 0),
('Frutilla', 3, 'Postcosecha', 4, 5, 2, 3, 0),
('Frutilla', 4, 'Establecimiento', 2, 3, 2, 2, 0),
('Frutilla', 5, 'Establecimiento', 2, 3, 2, 2, 0),
('Frutilla', 6, 'Reposo', 20, 20, 0, 0, 1),
('Frutilla', 7, 'Reposo', 20, 20, 0, 0, 1),
('Frutilla', 8, 'Crecimiento vegetativo', 3, 4, 2, 3, 0),
('Frutilla', 9, 'Crecimiento vegetativo', 3, 4, 2, 3, 0),
('Frutilla', 10, 'Floración', 2, 3, 2, 4, 0),
('Frutilla', 11, 'Fructificación y cosecha', 2, 2, 3, 4, 0),
('Frutilla', 12, 'Fructificación y cosecha', 2, 2, 3, 4, 0),
('Frambuesa', 1, 'Fructificación', 2, 3, 20, 28, 0),
('Frambuesa', 2, 'Fructificación', 2, 3, 20, 28, 0),
('Frambuesa', 3, 'Postcosecha', 7, 8, 10, 15, 0),
('Frambuesa', 4, 'Postcosecha', 7, 8, 10, 15, 0),
('Frambuesa', 5, 'Reposo', 20, 20, 0, 0, 1),
('Frambuesa', 6, 'Reposo', 20, 20, 0, 0, 1),
('Frambuesa', 7, 'Reposo', 20, 20, 0, 0, 1),
('Frambuesa', 8, 'Reposo', 20, 20, 0, 0, 1),
('Frambuesa', 9, 'Brotación', 5, 6, 8, 12, 0),
('Frambuesa', 10, 'Crecimiento de cañas', 4, 5, 12, 18, 0),
('Frambuesa', 11, 'Crecimiento de cañas → Floración', 4, 4, 14, 19, 0),
('Frambuesa', 12, 'Floración → Fructificación', 2, 4, 18, 24, 0),
('Mora', 1, 'Fructificación', 3, 4, 25, 35, 0),
('Mora', 2, 'Fructificación', 3, 4, 25, 35, 0),
('Mora', 3, 'Postcosecha', 8, 10, 12, 18, 0),
('Mora', 4, 'Postcosecha', 8, 10, 12, 18, 0),
('Mora', 5, 'Reposo', 20, 20, 0, 0, 1),
('Mora', 6, 'Reposo', 20, 20, 0, 0, 1),
('Mora', 7, 'Reposo', 20, 20, 0, 0, 1),
('Mora', 8, 'Reposo', 20, 20, 0, 0, 1),
('Mora', 9, 'Brotación', 6, 7, 10, 15, 0),
('Mora', 10, 'Brotación → Crecimiento', 6, 6, 12, 18, 0),
('Mora', 11, 'Crecimiento → Floración', 4, 6, 16, 22, 0),
('Mora', 12, 'Floración', 4, 5, 18, 25, 0),
('Kiwi', 1, 'Cuaja y crecimiento', 3, 4, 90, 120, 0),
('Kiwi', 2, 'Llenado de fruto', 3, 4, 100, 130, 0),
('Kiwi', 3, 'Llenado de fruto', 3, 4, 100, 130, 0),
('Kiwi', 4, 'Cosecha y postcosecha', 7, 8, 50, 70, 0),
('Kiwi', 5, 'Cosecha y postcosecha', 7, 8, 50, 70, 0),
('Kiwi', 6, 'Reposo', 20, 20, 0, 0, 1),
('Kiwi', 7, 'Reposo', 20, 20, 0, 0, 1),
('Kiwi', 8, 'Reposo', 20, 20, 0, 0, 1),
('Kiwi', 9, 'Brotación', 5, 6, 40, 60, 0),
('Kiwi', 10, 'Brotación', 5, 6, 40, 60, 0),
('Kiwi', 11, 'Floración', 4, 5, 60, 80, 0),
('Kiwi', 12, 'Cuaja y crecimiento', 3, 4, 90, 120, 0),
('Avellano Europeo', 1, 'Llenado de nuez', 5, 7, 60, 80, 0),
('Avellano Europeo', 2, 'Maduración y caída', 8, 10, 40, 55, 0),
('Avellano Europeo', 3, 'Maduración y caída', 8, 10, 40, 55, 0),
('Avellano Europeo', 4, 'Postcosecha', 12, 15, 25, 35, 0),
('Avellano Europeo', 5, 'Postcosecha', 12, 15, 25, 35, 0),
('Avellano Europeo', 6, 'Reposo', 20, 20, 0, 0, 1),
('Avellano Europeo', 7, 'Floración invernal', 12, 15, 20, 30, 0),
('Avellano Europeo', 8, 'Floración invernal', 12, 15, 20, 30, 0),
('Avellano Europeo', 9, 'Crecimiento vegetativo', 8, 10, 35, 50, 0),
('Avellano Europeo', 10, 'Crecimiento vegetativo', 8, 10, 35, 50, 0),
('Avellano Europeo', 11, 'Llenado de nuez', 5, 7, 60, 80, 0),
('Avellano Europeo', 12, 'Llenado de nuez', 5, 7, 60, 80, 0);
insert into public.gf_riego_mensual (especie, mes, etapa, dias_min, dias_max, litros_min, litros_max, reposo) values
('Níspero Japonés', 1, 'Verano', 6, 8, 50, 65, 0),
('Níspero Japonés', 2, 'Verano', 6, 8, 50, 65, 0),
('Níspero Japonés', 3, 'Verano', 6, 8, 50, 65, 0),
('Níspero Japonés', 4, 'Floración', 12, 15, 25, 35, 0),
('Níspero Japonés', 5, 'Floración', 12, 15, 25, 35, 0),
('Níspero Japonés', 6, 'Floración', 12, 15, 25, 35, 0),
('Níspero Japonés', 7, 'Crecimiento de fruto', 8, 10, 35, 50, 0),
('Níspero Japonés', 8, 'Crecimiento de fruto', 8, 10, 35, 50, 0),
('Níspero Japonés', 9, 'Maduración y cosecha', 6, 8, 45, 60, 0),
('Níspero Japonés', 10, 'Maduración y cosecha', 6, 8, 45, 60, 0),
('Níspero Japonés', 11, 'Postcosecha y brotación', 7, 9, 40, 55, 0),
('Níspero Japonés', 12, 'Postcosecha y brotación', 7, 9, 40, 55, 0),
('Lúcuma', 1, 'Cuaja y crecimiento', 6, 8, 55, 75, 0),
('Lúcuma', 2, 'Cuaja y crecimiento', 6, 8, 55, 75, 0),
('Lúcuma', 3, 'Maduración', 8, 12, 45, 60, 0),
('Lúcuma', 4, 'Maduración', 8, 12, 45, 60, 0),
('Lúcuma', 5, 'Maduración', 8, 12, 45, 60, 0),
('Lúcuma', 6, 'Maduración', 8, 12, 45, 60, 0),
('Lúcuma', 7, 'Cosecha', 12, 15, 30, 45, 0),
('Lúcuma', 8, 'Cosecha', 12, 15, 30, 45, 0),
('Lúcuma', 9, 'Floración', 8, 10, 40, 55, 0),
('Lúcuma', 10, 'Floración', 8, 10, 40, 55, 0),
('Lúcuma', 11, 'Floración', 8, 10, 40, 55, 0),
('Lúcuma', 12, 'Cuaja y crecimiento', 6, 8, 55, 75, 0),
('Palto', 1, 'Crecimiento de fruto', 4, 5, 90, 120, 0),
('Palto', 2, 'Crecimiento de fruto', 4, 5, 90, 120, 0),
('Palto', 3, 'Maduración', 6, 8, 70, 90, 0),
('Palto', 4, 'Maduración', 6, 8, 70, 90, 0),
('Palto', 5, 'Maduración', 6, 8, 70, 90, 0),
('Palto', 6, 'Invierno', 12, 15, 35, 50, 0),
('Palto', 7, 'Invierno', 12, 15, 35, 50, 0),
('Palto', 8, 'Invierno', 12, 15, 35, 50, 0),
('Palto', 9, 'Floración', 6, 8, 50, 70, 0),
('Palto', 10, 'Floración', 6, 8, 50, 70, 0),
('Palto', 11, 'Floración → Cuaja', 6, 7, 60, 80, 0),
('Palto', 12, 'Cuaja → Crecimiento de fruto', 4, 6, 80, 105, 0),
('Chirimoya', 1, 'Cuaja y crecimiento', 5, 7, 60, 85, 0),
('Chirimoya', 2, 'Cuaja y crecimiento', 5, 7, 60, 85, 0),
('Chirimoya', 3, 'Maduración', 7, 9, 50, 70, 0),
('Chirimoya', 4, 'Maduración', 7, 9, 50, 70, 0),
('Chirimoya', 5, 'Maduración', 7, 9, 50, 70, 0),
('Chirimoya', 6, 'Cosecha y reposo', 15, 20, 20, 30, 0),
('Chirimoya', 7, 'Cosecha y reposo', 15, 20, 20, 30, 0),
('Chirimoya', 8, 'Cosecha y reposo', 15, 20, 20, 30, 0),
('Chirimoya', 9, 'Brotación y floración', 7, 9, 40, 60, 0),
('Chirimoya', 10, 'Brotación y floración', 7, 9, 40, 60, 0),
('Chirimoya', 11, 'Brotación y floración', 7, 9, 40, 60, 0),
('Chirimoya', 12, 'Brotación y floración → Cuaja y crecimiento', 6, 8, 50, 72, 0),
('Papayo Chileno', 1, 'Floración y cuaja continua', 4, 5, 35, 50, 0),
('Papayo Chileno', 2, 'Floración y cuaja continua', 4, 5, 35, 50, 0),
('Papayo Chileno', 3, 'Maduración', 6, 8, 30, 40, 0),
('Papayo Chileno', 4, 'Maduración', 6, 8, 30, 40, 0),
('Papayo Chileno', 5, 'Maduración', 6, 8, 30, 40, 0),
('Papayo Chileno', 6, 'Invierno', 12, 15, 15, 25, 0),
('Papayo Chileno', 7, 'Invierno', 12, 15, 15, 25, 0),
('Papayo Chileno', 8, 'Invierno', 12, 15, 15, 25, 0),
('Papayo Chileno', 9, 'Crecimiento de primavera', 5, 6, 25, 35, 0),
('Papayo Chileno', 10, 'Crecimiento de primavera', 5, 6, 25, 35, 0),
('Papayo Chileno', 11, 'Crecimiento de primavera', 5, 6, 25, 35, 0),
('Papayo Chileno', 12, 'Floración y cuaja continua', 4, 5, 35, 50, 0);

create table if not exists public.gf_riego_etapas (
  especie text not null,
  codigo text not null,
  etapa_programa text not null,
  meses_originales text not null,
  coincide_exacta boolean not null,
  dias_min numeric not null,
  dias_max numeric not null,
  litros_min numeric not null,
  litros_max numeric not null,
  primary key (especie, codigo)
);
insert into public.gf_riego_etapas (especie, codigo, etapa_programa, meses_originales, coincide_exacta, dias_min, dias_max, litros_min, litros_max) values
('Duraznero', 'BRO', 'Brotación (Sep-Oct)', 'Septiembre - Octubre', TRUE, 7, 10, 20, 30),
('Duraznero', 'FLO', 'Floración (Oct)', 'Octubre', TRUE, 5, 7, 30, 40),
('Duraznero', 'CUA', 'Cuaja (Oct-Nov)', 'Octubre - Noviembre', TRUE, 5, 5, 40, 50),
('Duraznero', 'CRE', 'Crecimiento de fruto (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 3, 5, 50, 70),
('Duraznero', 'MAD', 'Maduración (Dic-Feb)', 'Diciembre - Febrero', TRUE, 3, 4, 60, 80),
('Duraznero', 'POS', 'Postcosecha (Feb-Abr)', 'Febrero - Abril', TRUE, 7, 10, 30, 40),
('Duraznero', 'REP', 'Reposo (May-Ago)', 'Mayo - Agosto', TRUE, 15, 15, 15, 20),
('Ciruelo', 'BRO', 'Brotación (Ago-Sep)', 'Agosto - Septiembre', TRUE, 10, 10, 20, 30),
('Ciruelo', 'FLO', 'Floración (Sep-Oct)', 'Septiembre - Octubre', TRUE, 7, 7, 30, 30),
('Ciruelo', 'CUA', 'Cuaja (Oct-Nov)', 'Octubre - Noviembre', TRUE, 5, 7, 40, 40),
('Ciruelo', 'CRE', 'Crecimiento (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 4, 5, 50, 60),
('Ciruelo', 'MAD', 'Maduración (Dic-Feb)', 'Diciembre - Febrero', TRUE, 3, 4, 60, 70),
('Ciruelo', 'POS', 'Postcosecha (Feb-Abr)', 'Febrero - Abril', TRUE, 10, 10, 30, 30),
('Ciruelo', 'REP', 'Reposo (May-Jul)', 'Mayo - Julio', TRUE, 20, 20, 0, 0),
('Cerezo', 'BRO', 'Brotación (Ago-Sep)', 'Agosto - Septiembre', TRUE, 10, 10, 20, 20),
('Cerezo', 'FLO', 'Floración (Sep)', 'Septiembre', TRUE, 7, 7, 30, 30),
('Cerezo', 'CUA', 'Cuaja (Oct)', 'Octubre', TRUE, 5, 7, 40, 40),
('Cerezo', 'CRE', 'Crecimiento (Oct-Nov)', 'Octubre - Noviembre', TRUE, 4, 5, 50, 50),
('Cerezo', 'MAD', 'Pinta y maduración (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 5, 5, 40, 40),
('Cerezo', 'POS', 'Postcosecha (Dic-Mar)', 'Diciembre - Marzo', TRUE, 7, 10, 40, 40),
('Cerezo', 'REP', 'Reposo (Abr-Jul)', 'Abril - Julio', TRUE, 20, 20, 0, 0),
('Damasco', 'BRO', 'Brotación (Ago)', 'Agosto', TRUE, 10, 10, 20, 20),
('Damasco', 'FLO', 'Floración (Ago-Sep)', 'Agosto - Septiembre', TRUE, 7, 7, 25, 25),
('Damasco', 'CUA', 'Cuaja (Sep-Oct)', 'Septiembre - Octubre', TRUE, 5, 7, 35, 35),
('Damasco', 'CRE', 'Crecimiento (Oct-Nov)', 'Octubre - Noviembre', TRUE, 4, 5, 45, 45),
('Damasco', 'MAD', 'Maduración (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 4, 4, 50, 50),
('Damasco', 'POS', 'Postcosecha (Dic-Mar)', 'Diciembre - Marzo', TRUE, 10, 10, 30, 30),
('Damasco', 'REP', 'Reposo (Abr-Jul)', 'Abril - Julio', TRUE, 20, 20, 0, 0),
('Nectarino', 'BRO', 'Brotación (Sep)', 'Septiembre', TRUE, 7, 10, 20, 30),
('Nectarino', 'FLO', 'Floración (Oct)', 'Octubre', TRUE, 5, 7, 30, 40),
('Nectarino', 'CUA', 'Cuaja (Oct-Nov)', 'Octubre - Noviembre', TRUE, 5, 5, 40, 50),
('Nectarino', 'CRE', 'Crecimiento (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 3, 5, 50, 70),
('Nectarino', 'MAD', 'Maduración (Dic-Feb)', 'Diciembre - Febrero', TRUE, 3, 4, 60, 80),
('Nectarino', 'POS', 'Postcosecha (Feb-Abr)', 'Febrero - Abril', TRUE, 7, 10, 30, 40),
('Nectarino', 'REP', 'Reposo (May-Ago)', 'Mayo - Agosto', TRUE, 20, 20, 0, 0),
('Manzano', 'BRO', 'Brotación (Sep)', 'Septiembre', TRUE, 10, 10, 25, 25),
('Manzano', 'FLO', 'Floración (Oct)', 'Octubre', TRUE, 7, 7, 30, 30),
('Manzano', 'CUA', 'Cuaja (Oct-Nov)', 'Octubre - Noviembre', TRUE, 7, 7, 40, 40),
('Manzano', 'CRE', 'Crecimiento (Nov-Ene)', 'Noviembre - Enero', TRUE, 5, 7, 50, 70),
('Manzano', 'MAD', 'Maduración (Feb-Abr)', 'Febrero - Abril', TRUE, 7, 7, 50, 50),
('Manzano', 'POS', 'Postcosecha (Abr-May)', 'Abril - Mayo', TRUE, 10, 10, 30, 30),
('Manzano', 'REP', 'Reposo (Jun-Ago)', 'Junio - Agosto', TRUE, 20, 20, 0, 0),
('Peral', 'BRO', 'Brotación (Sep)', 'Septiembre', TRUE, 10, 10, 25, 25),
('Peral', 'FLO', 'Floración (Oct)', 'Octubre', TRUE, 7, 7, 30, 30),
('Peral', 'CUA', 'Cuaja (Oct-Nov)', 'Octubre - Noviembre', TRUE, 7, 7, 40, 40),
('Peral', 'CRE', 'Crecimiento (Nov-Ene)', 'Noviembre - Enero', TRUE, 5, 7, 50, 60),
('Peral', 'MAD', 'Maduración (Feb-Mar)', 'Febrero - Marzo', TRUE, 7, 7, 50, 50),
('Peral', 'POS', 'Postcosecha (Abr-May)', 'Abril - Mayo', TRUE, 10, 10, 30, 30),
('Peral', 'REP', 'Reposo (Jun-Ago)', 'Junio - Agosto', TRUE, 20, 20, 0, 0),
('Membrillo', 'BRO', 'Brotación (Sep)', 'Septiembre', TRUE, 10, 10, 20, 20),
('Membrillo', 'FLO', 'Floración (Oct)', 'Octubre', TRUE, 7, 10, 25, 25),
('Membrillo', 'CUA', 'Cuaja (Nov)', 'Noviembre', TRUE, 7, 7, 30, 30),
('Membrillo', 'CRE', 'Crecimiento (Dic-Feb)', 'Diciembre - Febrero', TRUE, 7, 7, 40, 40),
('Membrillo', 'MAD', 'Maduración (Mar-May)', 'Marzo - Mayo', TRUE, 7, 10, 30, 40),
('Membrillo', 'POS', 'Postcosecha (May-Jun)', 'Mayo - Junio', TRUE, 15, 15, 20, 20),
('Membrillo', 'REP', 'Reposo (Jun-Ago)', 'Junio - Agosto', TRUE, 20, 20, 0, 0),
('Limonero', 'BRO', 'Primavera (Sep-Nov)', 'Septiembre - Noviembre', TRUE, 7, 10, 30, 40),
('Limonero', 'FLO', 'Primavera (Sep-Nov)', 'Septiembre - Noviembre', TRUE, 7, 10, 30, 40),
('Limonero', 'CUA', 'Verano (Dic-Feb)', 'Diciembre - Febrero', TRUE, 4, 7, 50, 70),
('Limonero', 'CRE', 'Verano (Dic-Feb)', 'Diciembre - Febrero', TRUE, 4, 7, 50, 70);
insert into public.gf_riego_etapas (especie, codigo, etapa_programa, meses_originales, coincide_exacta, dias_min, dias_max, litros_min, litros_max) values
('Limonero', 'MAD', 'Verano (Dic-Feb)', 'Diciembre - Febrero', TRUE, 4, 7, 50, 70),
('Limonero', 'POS', 'Otoño (Mar-May)', 'Marzo - Mayo', TRUE, 10, 10, 30, 40),
('Limonero', 'REP', 'Invierno (Jun-Ago)', 'Junio - Agosto', TRUE, 15, 15, 20, 30),
('Naranjo', 'BRO', 'Primavera (Sep-Nov)', 'Septiembre - Noviembre', TRUE, 7, 10, 40, 40),
('Naranjo', 'FLO', 'Primavera (Sep-Nov)', 'Septiembre - Noviembre', TRUE, 7, 10, 40, 40),
('Naranjo', 'CUA', 'Verano (Dic-Feb)', 'Diciembre - Febrero', TRUE, 4, 7, 60, 80),
('Naranjo', 'CRE', 'Verano (Dic-Feb)', 'Diciembre - Febrero', TRUE, 4, 7, 60, 80),
('Naranjo', 'MAD', 'Verano (Dic-Feb)', 'Diciembre - Febrero', TRUE, 4, 7, 60, 80),
('Naranjo', 'POS', 'Otoño (Mar-May)', 'Marzo - Mayo', TRUE, 10, 10, 40, 40),
('Naranjo', 'REP', 'Invierno (Jun-Ago)', 'Junio - Agosto', TRUE, 15, 15, 30, 30),
('Mandarino', 'BRO', 'Primavera', 'Septiembre - Noviembre', TRUE, 7, 10, 30, 30),
('Mandarino', 'FLO', 'Primavera', 'Septiembre - Noviembre', TRUE, 7, 10, 30, 30),
('Mandarino', 'CUA', 'Verano', 'Diciembre - Febrero', TRUE, 4, 7, 50, 60),
('Mandarino', 'CRE', 'Verano', 'Diciembre - Febrero', TRUE, 4, 7, 50, 60),
('Mandarino', 'MAD', 'Verano', 'Diciembre - Febrero', TRUE, 4, 7, 50, 60),
('Mandarino', 'POS', 'Otoño', 'Marzo - Mayo', TRUE, 10, 10, 30, 30),
('Mandarino', 'REP', 'Invierno', 'Junio - Agosto', TRUE, 15, 15, 20, 20),
('Pomelo', 'BRO', 'Primavera', 'Septiembre - Noviembre', TRUE, 7, 10, 40, 40),
('Pomelo', 'FLO', 'Primavera', 'Septiembre - Noviembre', TRUE, 7, 10, 40, 40),
('Pomelo', 'CUA', 'Verano', 'Diciembre - Febrero', TRUE, 4, 7, 70, 90),
('Pomelo', 'CRE', 'Verano', 'Diciembre - Febrero', TRUE, 4, 7, 70, 90),
('Pomelo', 'MAD', 'Verano', 'Diciembre - Febrero', TRUE, 4, 7, 70, 90),
('Pomelo', 'POS', 'Otoño', 'Marzo - Mayo', TRUE, 10, 10, 40, 40),
('Pomelo', 'REP', 'Invierno', 'Junio - Agosto', TRUE, 15, 15, 30, 30),
('Nogal', 'BRO', 'Brotación (Sep-Oct)', 'Septiembre - Octubre', TRUE, 10, 15, 40, 60),
('Nogal', 'FLO', 'Floración (Oct)', 'Octubre', TRUE, 10, 10, 50, 60),
('Nogal', 'CUA', 'Floración (Oct)', 'Octubre', FALSE, 10, 10, 50, 60),
('Nogal', 'CRE', 'Crecimiento fruto (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 7, 10, 80, 120),
('Nogal', 'MAD', 'Maduración (Mar-Abr)', 'Marzo - Abril', TRUE, 7, 10, 80, 80),
('Nogal', 'POS', 'Postcosecha (Abr-May)', 'Abril - Mayo', TRUE, 15, 15, 50, 50),
('Nogal', 'REP', 'Reposo (Jun-Ago)', 'Junio - Agosto', TRUE, 20, 20, 0, 0),
('Almendro', 'BRO', 'Brotación (Ago-Sep)', 'Agosto - Septiembre', TRUE, 10, 15, 25, 25),
('Almendro', 'FLO', 'Floración (Ago-Sep)', 'Agosto - Septiembre', TRUE, 10, 10, 30, 30),
('Almendro', 'CUA', 'Cuaja (Sep-Oct)', 'Septiembre - Octubre', TRUE, 7, 10, 40, 40),
('Almendro', 'CRE', 'Crecimiento (Oct-Dic)', 'Octubre - Diciembre', TRUE, 7, 10, 50, 60),
('Almendro', 'MAD', 'Maduración (Feb-Mar)', 'Febrero - Marzo', TRUE, 10, 15, 30, 30),
('Almendro', 'POS', 'Postcosecha-reposo (Abr-Jul)', 'Abril - Julio', TRUE, 20, 20, 0, 0),
('Almendro', 'REP', 'Postcosecha-reposo (Abr-Jul)', 'Abril - Julio', TRUE, 20, 20, 0, 0),
('Higuera', 'BRO', 'Brotación (Sep-Oct)', 'Septiembre - Octubre', TRUE, 10, 15, 20, 20),
('Higuera', 'FLO', 'Brotación (Sep-Oct)', 'Septiembre - Octubre', FALSE, 10, 15, 20, 20),
('Higuera', 'CUA', 'Crecimiento (Nov-Dic)', 'Noviembre - Diciembre', FALSE, 7, 10, 30, 40),
('Higuera', 'CRE', 'Crecimiento (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 7, 10, 30, 40),
('Higuera', 'MAD', 'Maduración 1ra cosecha (Dic-Ene)', 'Diciembre - Enero', TRUE, 5, 7, 40, 40),
('Higuera', 'POS', 'Postcosecha (Abr-May)', 'Abril - Mayo', TRUE, 15, 15, 20, 20),
('Higuera', 'REP', 'Reposo (Jun-Ago)', 'Junio - Agosto', TRUE, 20, 20, 0, 0),
('Granado', 'BRO', 'Brotación (Sep-Oct)', 'Septiembre - Octubre', TRUE, 10, 15, 20, 20),
('Granado', 'FLO', 'Floración (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 7, 10, 30, 30),
('Granado', 'CUA', 'Floración (Nov-Dic)', 'Noviembre - Diciembre', FALSE, 7, 10, 30, 30),
('Granado', 'CRE', 'Crecimiento (Dic-Feb)', 'Diciembre - Febrero', TRUE, 5, 7, 40, 50),
('Granado', 'MAD', 'Maduración (Mar-May)', 'Marzo - Mayo', TRUE, 7, 10, 30, 40),
('Granado', 'POS', 'Postcosecha (May-Jun)', 'Mayo - Junio', TRUE, 15, 15, 20, 20),
('Granado', 'REP', 'Reposo (Jul-Ago)', 'Julio - Agosto', TRUE, 20, 20, 0, 0),
('Caqui', 'BRO', 'Brotación (Sep-Oct)', 'Septiembre - Octubre', TRUE, 10, 15, 25, 25),
('Caqui', 'FLO', 'Floración (Nov)', 'Noviembre', TRUE, 7, 10, 30, 30),
('Caqui', 'CUA', 'Floración (Nov)', 'Noviembre', FALSE, 7, 10, 30, 30),
('Caqui', 'CRE', 'Crecimiento (Dic-Feb)', 'Diciembre - Febrero', TRUE, 5, 7, 50, 60),
('Caqui', 'MAD', 'Maduración (Mar-May)', 'Marzo - Mayo', TRUE, 7, 10, 40, 40),
('Caqui', 'POS', 'Postcosecha (Jun)', 'Junio', TRUE, 15, 15, 20, 20),
('Caqui', 'REP', 'Reposo (Jul-Ago)', 'Julio - Agosto', TRUE, 20, 20, 0, 0),
('Vid', 'BRO', 'Brotación (Sep)', 'Septiembre', TRUE, 10, 10, 15, 20);
insert into public.gf_riego_etapas (especie, codigo, etapa_programa, meses_originales, coincide_exacta, dias_min, dias_max, litros_min, litros_max) values
('Vid', 'FLO', 'Floración (Nov)', 'Noviembre', TRUE, 7, 10, 25, 30),
('Vid', 'CUA', 'Cuaja-crecimiento (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 5, 7, 30, 40),
('Vid', 'CRE', 'Crecimiento brotes (Oct)', 'Octubre', TRUE, 7, 10, 20, 30),
('Vid', 'MAD', 'Envero-maduración (Ene-Feb)', 'Enero - Febrero', TRUE, 7, 10, 20, 30),
('Vid', 'POS', 'Postcosecha-reposo (Abr-Ago)', 'Abril - Agosto', TRUE, 20, 20, 0, 0),
('Vid', 'REP', 'Postcosecha-reposo (Abr-Ago)', 'Abril - Agosto', TRUE, 20, 20, 0, 0),
('Arandano', 'BRO', 'Brotación (Sep)', 'Septiembre', TRUE, 3, 5, 5, 10),
('Arandano', 'FLO', 'Floración (Oct)', 'Octubre', TRUE, 3, 5, 8, 10),
('Arandano', 'CUA', 'Cuaja-crecimiento (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 2, 3, 10, 15),
('Arandano', 'CRE', 'Cuaja-crecimiento (Nov-Dic)', 'Noviembre - Diciembre', TRUE, 2, 3, 10, 15),
('Arandano', 'MAD', 'Maduración (Dic-Feb)', 'Diciembre - Febrero', TRUE, 2, 3, 10, 15),
('Arandano', 'POS', 'Postcosecha (Feb-Abr)', 'Febrero - Abril', TRUE, 5, 5, 8, 8),
('Arandano', 'REP', 'Reposo (May-Ago)', 'Mayo - Agosto', TRUE, 10, 15, 5, 5),
('Olivo', 'BRO', 'Brotación (Sep-Oct)', 'Septiembre - Octubre', TRUE, 15, 15, 20, 30),
('Olivo', 'FLO', 'Floración (Nov)', 'Noviembre', TRUE, 10, 15, 30, 30),
('Olivo', 'CUA', 'Cuaja (Dic)', 'Diciembre', TRUE, 10, 10, 40, 40),
('Olivo', 'CRE', 'Crecimiento (Ene-Feb)', 'Enero - Febrero', TRUE, 7, 10, 50, 50),
('Olivo', 'MAD', 'Envero-maduración (Mar-May)', 'Marzo - Mayo', TRUE, 10, 15, 30, 40),
('Olivo', 'POS', 'Postcosecha (Jun-Jul)', 'Junio - Julio', TRUE, 15, 20, 20, 20),
('Olivo', 'REP', 'Reposo (Jul-Ago)', 'Julio - Agosto', TRUE, 20, 20, 0, 0),
('Frutilla', 'BRO', 'Establecimiento (Abril - Mayo)', 'Abril - Mayo', TRUE, 2, 3, 2, 2),
('Frutilla', 'FLO', 'Floración (Octubre)', 'Octubre', TRUE, 2, 3, 2, 4),
('Frutilla', 'CUA', 'Crecimiento vegetativo (Agosto - Septiembre)', 'Agosto - Septiembre', FALSE, 3, 4, 2, 3),
('Frutilla', 'CRE', 'Crecimiento vegetativo (Agosto - Septiembre)', 'Agosto - Septiembre', TRUE, 3, 4, 2, 3),
('Frutilla', 'MAD', 'Fructificación y cosecha (Noviembre - Enero)', 'Noviembre - Enero', TRUE, 2, 2, 3, 4),
('Frutilla', 'POS', 'Postcosecha (Febrero - Marzo)', 'Febrero - Marzo', TRUE, 4, 5, 2, 3),
('Frutilla', 'REP', 'Reposo (Junio - Julio)', 'Junio - Julio', TRUE, 10, 15, 0, 0),
('Frambuesa', 'BRO', 'Brotación (Septiembre)', 'Septiembre', TRUE, 5, 6, 8, 12),
('Frambuesa', 'FLO', 'Floración (Noviembre - Diciembre)', 'Noviembre - Diciembre', TRUE, 3, 4, 15, 20),
('Frambuesa', 'CUA', 'Crecimiento de cañas (Octubre - Noviembre)', 'Octubre - Noviembre', FALSE, 4, 5, 12, 18),
('Frambuesa', 'CRE', 'Crecimiento de cañas (Octubre - Noviembre)', 'Octubre - Noviembre', TRUE, 4, 5, 12, 18),
('Frambuesa', 'MAD', 'Fructificación (Diciembre - Febrero)', 'Diciembre - Febrero', TRUE, 2, 3, 20, 28),
('Frambuesa', 'POS', 'Postcosecha (Marzo - Abril)', 'Marzo - Abril', TRUE, 7, 8, 10, 15),
('Frambuesa', 'REP', 'Reposo (Mayo - Agosto)', 'Mayo - Agosto', TRUE, 15, 20, 0, 0),
('Mora', 'BRO', 'Brotación (Septiembre - Octubre)', 'Septiembre - Octubre', TRUE, 6, 7, 10, 15),
('Mora', 'FLO', 'Floración (Noviembre - Diciembre)', 'Noviembre - Diciembre', TRUE, 4, 5, 18, 25),
('Mora', 'CUA', 'Crecimiento (Octubre - Noviembre)', 'Octubre - Noviembre', FALSE, 5, 6, 15, 20),
('Mora', 'CRE', 'Crecimiento (Octubre - Noviembre)', 'Octubre - Noviembre', TRUE, 5, 6, 15, 20),
('Mora', 'MAD', 'Fructificación (Enero - Febrero)', 'Enero - Febrero', TRUE, 3, 4, 25, 35),
('Mora', 'POS', 'Postcosecha (Marzo - Abril)', 'Marzo - Abril', TRUE, 8, 10, 12, 18),
('Mora', 'REP', 'Reposo (Mayo - Agosto)', 'Mayo - Agosto', TRUE, 15, 20, 0, 0),
('Kiwi', 'BRO', 'Brotación (Septiembre - Octubre)', 'Septiembre - Octubre', TRUE, 5, 6, 40, 60),
('Kiwi', 'FLO', 'Floración (Noviembre)', 'Noviembre', TRUE, 4, 5, 60, 80),
('Kiwi', 'CUA', 'Cuaja y crecimiento (Diciembre - Enero)', 'Diciembre - Enero', TRUE, 3, 4, 90, 120),
('Kiwi', 'CRE', 'Cuaja y crecimiento (Diciembre - Enero)', 'Diciembre - Enero', TRUE, 3, 4, 90, 120),
('Kiwi', 'MAD', 'Cuaja y crecimiento (Diciembre - Enero)', 'Diciembre - Enero', FALSE, 3, 4, 90, 120),
('Kiwi', 'POS', 'Cosecha y postcosecha (Abril - Mayo)', 'Abril - Mayo', TRUE, 7, 8, 50, 70),
('Kiwi', 'REP', 'Reposo (Junio - Agosto)', 'Junio - Agosto', TRUE, 20, 25, 0, 0),
('Avellano Europeo', 'BRO', 'Floración invernal (Julio - Agosto)', 'Julio - Agosto', FALSE, 12, 15, 20, 30),
('Avellano Europeo', 'FLO', 'Floración invernal (Julio - Agosto)', 'Julio - Agosto', TRUE, 12, 15, 20, 30),
('Avellano Europeo', 'CUA', 'Floración invernal (Julio - Agosto)', 'Julio - Agosto', FALSE, 12, 15, 20, 30),
('Avellano Europeo', 'CRE', 'Crecimiento vegetativo (Septiembre - Octubre)', 'Septiembre - Octubre', TRUE, 8, 10, 35, 50),
('Avellano Europeo', 'MAD', 'Maduración y caída (Febrero - Marzo)', 'Febrero - Marzo', TRUE, 8, 10, 40, 55),
('Avellano Europeo', 'POS', 'Postcosecha (Abril - Mayo)', 'Abril - Mayo', TRUE, 12, 15, 25, 35),
('Avellano Europeo', 'REP', 'Reposo (Junio)', 'Junio', TRUE, 20, 25, 0, 0),
('Níspero Japonés', 'BRO', 'Postcosecha y brotación (Noviembre - Diciembre)', 'Noviembre - Diciembre', TRUE, 7, 9, 40, 55),
('Níspero Japonés', 'FLO', 'Floración (Abril - Junio)', 'Abril - Junio', TRUE, 12, 15, 25, 35),
('Níspero Japonés', 'CUA', 'Floración (Abril - Junio)', 'Abril - Junio', FALSE, 12, 15, 25, 35),
('Níspero Japonés', 'CRE', 'Crecimiento de fruto (Julio - Agosto)', 'Julio - Agosto', TRUE, 8, 10, 35, 50),
('Níspero Japonés', 'MAD', 'Maduración y cosecha (Septiembre - Octubre)', 'Septiembre - Octubre', TRUE, 6, 8, 45, 60);
insert into public.gf_riego_etapas (especie, codigo, etapa_programa, meses_originales, coincide_exacta, dias_min, dias_max, litros_min, litros_max) values
('Níspero Japonés', 'POS', 'Postcosecha y brotación (Noviembre - Diciembre)', 'Noviembre - Diciembre', TRUE, 7, 9, 40, 55),
('Níspero Japonés', 'REP', 'Postcosecha y brotación (Noviembre - Diciembre)', 'Noviembre - Diciembre', FALSE, 7, 9, 40, 55),
('Lúcuma', 'BRO', 'Floración (Septiembre - Noviembre)', 'Septiembre - Noviembre', FALSE, 8, 10, 40, 55),
('Lúcuma', 'FLO', 'Floración (Septiembre - Noviembre)', 'Septiembre - Noviembre', TRUE, 8, 10, 40, 55),
('Lúcuma', 'CUA', 'Cuaja y crecimiento (Diciembre - Febrero)', 'Diciembre - Febrero', TRUE, 6, 8, 55, 75),
('Lúcuma', 'CRE', 'Cuaja y crecimiento (Diciembre - Febrero)', 'Diciembre - Febrero', TRUE, 6, 8, 55, 75),
('Lúcuma', 'MAD', 'Maduración (Marzo - Junio)', 'Marzo - Junio', TRUE, 8, 12, 45, 60),
('Lúcuma', 'POS', 'Maduración (Marzo - Junio)', 'Marzo - Junio', FALSE, 8, 12, 45, 60),
('Lúcuma', 'REP', 'Maduración (Marzo - Junio)', 'Marzo - Junio', FALSE, 8, 12, 45, 60),
('Palto', 'BRO', 'Floración (Septiembre - Noviembre)', 'Septiembre - Noviembre', FALSE, 6, 8, 50, 70),
('Palto', 'FLO', 'Floración (Septiembre - Noviembre)', 'Septiembre - Noviembre', TRUE, 6, 8, 50, 70),
('Palto', 'CUA', 'Cuaja (Noviembre - Diciembre)', 'Noviembre - Diciembre', TRUE, 5, 6, 70, 90),
('Palto', 'CRE', 'Crecimiento de fruto (Diciembre - Febrero)', 'Diciembre - Febrero', TRUE, 4, 5, 90, 120),
('Palto', 'MAD', 'Maduración (Marzo - Mayo)', 'Marzo - Mayo', TRUE, 6, 8, 70, 90),
('Palto', 'POS', 'Invierno (Junio - Agosto)', 'Junio - Agosto', FALSE, 12, 15, 35, 50),
('Palto', 'REP', 'Invierno (Junio - Agosto)', 'Junio - Agosto', TRUE, 12, 15, 35, 50),
('Chirimoya', 'BRO', 'Brotación y floración (Septiembre - Diciembre)', 'Septiembre - Diciembre', TRUE, 7, 9, 40, 60),
('Chirimoya', 'FLO', 'Brotación y floración (Septiembre - Diciembre)', 'Septiembre - Diciembre', TRUE, 7, 9, 40, 60),
('Chirimoya', 'CUA', 'Cuaja y crecimiento (Diciembre - Febrero)', 'Diciembre - Febrero', TRUE, 5, 7, 60, 85),
('Chirimoya', 'CRE', 'Cuaja y crecimiento (Diciembre - Febrero)', 'Diciembre - Febrero', TRUE, 5, 7, 60, 85),
('Chirimoya', 'MAD', 'Maduración (Marzo - Mayo)', 'Marzo - Mayo', TRUE, 7, 9, 50, 70),
('Chirimoya', 'POS', 'Maduración (Marzo - Mayo)', 'Marzo - Mayo', FALSE, 7, 9, 50, 70),
('Chirimoya', 'REP', 'Cosecha y reposo (Junio - Agosto)', 'Junio - Agosto', TRUE, 15, 20, 20, 30),
('Papayo Chileno', 'BRO', 'Floración y cuaja continua (Diciembre - Febrero)', 'Diciembre - Febrero', FALSE, 4, 5, 35, 50),
('Papayo Chileno', 'FLO', 'Floración y cuaja continua (Diciembre - Febrero)', 'Diciembre - Febrero', TRUE, 4, 5, 35, 50),
('Papayo Chileno', 'CUA', 'Floración y cuaja continua (Diciembre - Febrero)', 'Diciembre - Febrero', TRUE, 4, 5, 35, 50),
('Papayo Chileno', 'CRE', 'Crecimiento de primavera (Septiembre - Noviembre)', 'Septiembre - Noviembre', TRUE, 5, 6, 25, 35),
('Papayo Chileno', 'MAD', 'Maduración (Marzo - Mayo)', 'Marzo - Mayo', TRUE, 6, 8, 30, 40),
('Papayo Chileno', 'POS', 'Invierno (Junio - Agosto)', 'Junio - Agosto', FALSE, 12, 15, 15, 25),
('Papayo Chileno', 'REP', 'Invierno (Junio - Agosto)', 'Junio - Agosto', TRUE, 12, 15, 15, 25);

alter table public.gf_riego_suelos enable row level security;
drop policy if exists gf_riego_suelos_lectura_publica on public.gf_riego_suelos;
create policy gf_riego_suelos_lectura_publica on public.gf_riego_suelos for select to anon, authenticated using (true);

alter table public.gf_riego_humedad enable row level security;
drop policy if exists gf_riego_humedad_lectura_publica on public.gf_riego_humedad;
create policy gf_riego_humedad_lectura_publica on public.gf_riego_humedad for select to anon, authenticated using (true);

alter table public.gf_riego_edad enable row level security;
drop policy if exists gf_riego_edad_lectura_publica on public.gf_riego_edad;
create policy gf_riego_edad_lectura_publica on public.gf_riego_edad for select to anon, authenticated using (true);

alter table public.gf_riego_zonas enable row level security;
drop policy if exists gf_riego_zonas_lectura_publica on public.gf_riego_zonas;
create policy gf_riego_zonas_lectura_publica on public.gf_riego_zonas for select to anon, authenticated using (true);

alter table public.gf_riego_kc enable row level security;
drop policy if exists gf_riego_kc_lectura_publica on public.gf_riego_kc;
create policy gf_riego_kc_lectura_publica on public.gf_riego_kc for select to anon, authenticated using (true);

alter table public.gf_riego_especies enable row level security;
drop policy if exists gf_riego_especies_lectura_publica on public.gf_riego_especies;
create policy gf_riego_especies_lectura_publica on public.gf_riego_especies for select to anon, authenticated using (true);

alter table public.gf_riego_mensual enable row level security;
drop policy if exists gf_riego_mensual_lectura_publica on public.gf_riego_mensual;
create policy gf_riego_mensual_lectura_publica on public.gf_riego_mensual for select to anon, authenticated using (true);

alter table public.gf_riego_etapas enable row level security;
drop policy if exists gf_riego_etapas_lectura_publica on public.gf_riego_etapas;
create policy gf_riego_etapas_lectura_publica on public.gf_riego_etapas for select to anon, authenticated using (true);
